#  Statistical Significance Testing

## Main Function

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.contingency_tables import mcnemar

def find_column(df, method, metric):
    """Find the correct column name for a method and metric"""
    method_variations = {
        "SEAL RAG": ["seal_rag", "SEAL_RAG", "seal"],
        "SELF_RAG": ["self_rag", "SELF_RAG", "selfrag"],
        "CRAG_RAG": ["crag_rag", "CRAG_RAG", "crag"],
        "BASIC_RAG": ["basic_rag", "BASIC_RAG", "basic"]
    }
    
    for col in df.columns:
        for variation in method_variations.get(method, [method.lower()]):
            # More precise matching: method in column AND column ends with metric
            if variation.lower() in col.lower() and col.lower().endswith(f"_{metric.lower()}"):
                return col
    return None

def print_column_detection(df, base_method="SEAL RAG", comparison_methods=None, metrics=None):
    """Print which columns were detected for each method/metric combination"""
    
    if comparison_methods is None:
        comparison_methods = ["SELF_RAG", "CRAG_RAG", "BASIC_RAG"]
    
    if metrics is None:
        metrics = ["final_answer_correct", "precision", "recall", "f1"]
    
    print("🔍 COLUMN DETECTION RESULTS")
    print("=" * 100)
    
    all_methods = [base_method] + comparison_methods
    
    for method in all_methods:
        print(f"\n📊 {method}:")
        print("-" * 80)
        
        for metric in metrics:
            col = find_column(df, method, metric)
            if col:
                print(f"   ✅ {metric:<20} → {col}")
            else:
                print(f"   ❌ {metric:<20} → NOT FOUND")
    
    print("\n" + "=" * 100)

def compare_binary_metrics(method1_results, method2_results, method1_name, method2_name):
    """Compare binary metrics using McNemar's test"""
    
    # Convert to integers (True=1, False=0)
    a1 = [int(x) for x in method1_results]
    a2 = [int(x) for x in method2_results]
    
    # Calculate accuracies
    acc1 = sum(a1) / len(a1)
    acc2 = sum(a2) / len(a2)
    
    # Create contingency table with margins
    contingency_table = pd.crosstab(
        pd.Series(a1, name=method1_name), 
        pd.Series(a2, name=method2_name),
        margins=True
    )
    
    # Run McNemar's test
    try:
        table_for_test = contingency_table.iloc[:-1, :-1]  # Remove margins
        result = mcnemar(table_for_test, exact=False)
        p_value = result.pvalue
    except ValueError:
        p_value = 1.0
    
    # Extract counts
    if contingency_table.shape[0] > 1 and contingency_table.shape[1] > 1:
        both_wrong = contingency_table.iloc[0, 0]
        method2_wins = contingency_table.iloc[0, 1]
        method1_wins = contingency_table.iloc[1, 0]
        both_right = contingency_table.iloc[1, 1]
    else:
        both_wrong = method2_wins = method1_wins = both_right = 0
    
    return {
        'contingency_table': contingency_table,
        'p_value': p_value,
        'is_significant': p_value < 0.05,
        'method1_accuracy': acc1,
        'method2_accuracy': acc2,
        'method1_wins': method1_wins,
        'method2_wins': method2_wins,
        'both_correct': both_right,
        'both_wrong': both_wrong,
        'test_type': 'McNemar',
        'statistic_name': 'Chi-squared',
        'degrees_freedom': 1
    }

def compare_continuous_metrics(method1_values, method2_values, method1_name, method2_name):
    """Compare continuous metrics using paired t-test"""
    
    # Convert to numpy arrays
    values1 = np.array(method1_values)
    values2 = np.array(method2_values)
    
    # Remove NaN values
    mask = ~(np.isnan(values1) | np.isnan(values2))
    values1_clean = values1[mask]
    values2_clean = values2[mask]
    
    if len(values1_clean) == 0:
        return {'error': 'No valid data after removing NaN values'}
    
    # Calculate statistics
    mean1 = np.mean(values1_clean)
    mean2 = np.mean(values2_clean)
    std1 = np.std(values1_clean, ddof=1)
    std2 = np.std(values2_clean, ddof=1)
    
    # Calculate differences
    differences = values1_clean - values2_clean
    mean_diff = np.mean(differences)
    std_diff = np.std(differences, ddof=1)
    
    # Paired t-test
    t_statistic, p_value = stats.ttest_rel(values1_clean, values2_clean)
    
    # Effect size (Cohen's d for paired samples)
    cohen_d = mean_diff / std_diff if std_diff > 0 else 0
    
    return {
        'p_value': p_value,
        'is_significant': p_value < 0.05,
        'mean1': mean1,
        'mean2': mean2,
        'std1': std1,
        'std2': std2,
        'mean_difference': mean_diff,
        'cohen_d': cohen_d,
        't_statistic': t_statistic,
        'n_samples': len(values1_clean),
        'test_type': 'Paired T-test',
        'statistic_name': 'T-statistic',
        'degrees_freedom': len(values1_clean) - 1
    }

def print_contingency_matrix(table, method1_name, method2_name):
    """Print a nicely formatted 2x2 contingency matrix"""
    
    print(f"\n📋 CONTINGENCY MATRIX: {method1_name} vs {method2_name}")
    print("=" * 60)
    
    # Remove margins if they exist
    if 'All' in table.index:
        display_table = table.iloc[:-1, :-1]
    else:
        display_table = table
    
    print(f"                    {method2_name}")
    print(f"                 Wrong    Right    Total")
    print("-" * 50)
    
    if display_table.shape[0] >= 2 and display_table.shape[1] >= 2:
        both_wrong = display_table.iloc[0, 0]
        m2_wins = display_table.iloc[0, 1]
        m1_wins = display_table.iloc[1, 0]
        both_right = display_table.iloc[1, 1]
        
        row1_total = both_wrong + m2_wins
        row2_total = m1_wins + both_right
        col1_total = both_wrong + m1_wins
        col2_total = m2_wins + both_right
        grand_total = row1_total + row2_total
        
        print(f"{method1_name:<8} Wrong  {both_wrong:5d}    {m2_wins:5d}    {row1_total:5d}")
        print(f"         Right  {m1_wins:5d}    {both_right:5d}    {row2_total:5d}")
        print("-" * 50)
        print(f"         Total  {col1_total:5d}    {col2_total:5d}    {grand_total:5d}")
        
        print(f"\n🔍 INTERPRETATION:")
        print(f"   Both wrong: {both_wrong:3d} questions")
        print(f"   {method2_name} wins: {m2_wins:3d} questions (when {method1_name} fails)")
        print(f"   {method1_name} wins: {m1_wins:3d} questions (when {method2_name} fails)")
        print(f"   Both right: {both_right:3d} questions")
        print(f"   Disagreements: {m1_wins + m2_wins:3d} questions (key for statistical test)")
        
        if m1_wins + m2_wins > 0:
            if m1_wins > m2_wins:
                ratio = m1_wins / max(m2_wins, 1)
                print(f"   Head-to-head: {method1_name} wins {ratio:.1f}x more often")
            elif m2_wins > m1_wins:
                ratio = m2_wins / max(m1_wins, 1)
                print(f"   Head-to-head: {method2_name} wins {ratio:.1f}x more often")
            else:
                print(f"   Head-to-head: Tied in disagreements")
    else:
        print("   Insufficient data for 2x2 matrix")

def print_continuous_results(result, method1_name, method2_name, metric_name):
    """Print results for continuous metric comparison"""
    
    if 'error' in result:
        print(f"❌ ERROR: {result['error']}")
        return
    
    print(f"\n📈 CONTINUOUS METRIC RESULTS:")
    print(f"   {method1_name}: {result['mean1']:.4f} ± {result['std1']:.4f}")
    print(f"   {method2_name}: {result['mean2']:.4f} ± {result['std2']:.4f}")
    print(f"   Mean difference: {result['mean_difference']:+.4f}")
    print(f"   Sample size: {result['n_samples']} questions")
    
    print(f"\n📊 PAIRED T-TEST RESULTS:")
    print(f"   T-statistic: {result['t_statistic']:.4f}")
    print(f"   P-value: {result['p_value']:.6f}")
    print(f"   Effect size (Cohen's d): {result['cohen_d']:.4f}")
    
    # Significance
    if result['is_significant']:
        better_method = method1_name if result['mean1'] > result['mean2'] else method2_name
        print(f"   Result: 🟢 SIGNIFICANT - {better_method} is significantly better")
    else:
        print(f"   Result: 🔴 NOT SIGNIFICANT - No significant difference")
    
    # Effect size interpretation
    abs_cohen_d = abs(result['cohen_d'])
    if abs_cohen_d < 0.2:
        effect_size = "negligible"
    elif abs_cohen_d < 0.5:
        effect_size = "small"
    elif abs_cohen_d < 0.8:
        effect_size = "medium"
    else:
        effect_size = "large"
    
    print(f"   Effect size interpretation: {effect_size}")

def create_summary_table(results_dict, base_method, comparison_methods, metrics):
    """Create a comprehensive summary table as a DataFrame"""
    
    metric_display = {
        "final_answer_correct": "Accuracy",
        "precision": "Precision", 
        "recall": "Recall",
        "f1": "F1 Score"
    }
    
    summary_data = []
    
    for comparison_method in comparison_methods:
        for metric in metrics:
            if comparison_method in results_dict and metric in results_dict[comparison_method]:
                result = results_dict[comparison_method][metric]
                
                if 'error' not in result:
                    # Common fields
                    row = {
                        'Base_Method': base_method,
                        'Comparison_Method': comparison_method,
                        'Metric': metric_display.get(metric, metric),
                        'Test_Type': result.get('test_type', 'Unknown'),
                        'Statistic_Name': result.get('statistic_name', 'Unknown'),
                        'P_Value': result['p_value'],
                        'Is_Significant': result['is_significant'],
                        'Significance_Level': 'p < 0.001' if result['p_value'] < 0.001 else 
                                           'p < 0.01' if result['p_value'] < 0.01 else
                                           'p < 0.05' if result['p_value'] < 0.05 else 'Not Significant'
                    }
                    
                    # Metric-specific fields
                    if metric == "final_answer_correct":
                        row.update({
                            'Base_Performance': f"{result['method1_accuracy']:.1%}",
                            'Comparison_Performance': f"{result['method2_accuracy']:.1%}",
                            'Performance_Difference': f"{result['method2_accuracy'] - result['method1_accuracy']:+.1%}",
                            'Base_Wins': result['method1_wins'],
                            'Comparison_Wins': result['method2_wins'],
                            'Effect_Size': 'N/A (Binary)',
                            'Statistic_Value': f"χ² = {result.get('chi_squared', 'N/A')}"
                        })
                    else:
                        better_method = base_method if result['mean1'] > result['mean2'] else comparison_method
                        row.update({
                            'Base_Performance': f"{result['mean1']:.3f}",
                            'Comparison_Performance': f"{result['mean2']:.3f}",
                            'Performance_Difference': f"{result['mean_difference']:+.3f}",
                            'Base_Wins': 'N/A (Continuous)',
                            'Comparison_Wins': 'N/A (Continuous)',
                            'Effect_Size': f"{result['cohen_d']:.3f}",
                            'Statistic_Value': f"t = {result['t_statistic']:.3f}"
                        })
                    
                    summary_data.append(row)
                else:
                    # Error case
                    row = {
                        'Base_Method': base_method,
                        'Comparison_Method': comparison_method,
                        'Metric': metric_display.get(metric, metric),
                        'Test_Type': 'ERROR',
                        'Statistic_Name': 'ERROR',
                        'P_Value': np.nan,
                        'Is_Significant': False,
                        'Significance_Level': 'ERROR',
                        'Base_Performance': 'ERROR',
                        'Comparison_Performance': 'ERROR',
                        'Performance_Difference': 'ERROR',
                        'Base_Wins': 'ERROR',
                        'Comparison_Wins': 'ERROR',
                        'Effect_Size': 'ERROR',
                        'Statistic_Value': 'ERROR'
                    }
                    summary_data.append(row)
    
    return pd.DataFrame(summary_data)

def run_comprehensive_comparison_with_summary(df, base_method="SEAL RAG", comparison_methods=None, metrics=None, 
                                            print_detailed=True, return_summary_table=True):
    """
    Run comprehensive comparison and return summary table
    
    Parameters:
    -----------
    df : pandas.DataFrame
        DataFrame containing experiment results
    base_method : str
        Base method to compare others against
    comparison_methods : list
        Methods to compare against base
    metrics : list
        Metrics to analyze
    print_detailed : bool
        Whether to print detailed analysis
    return_summary_table : bool
        Whether to return summary table DataFrame
        
    Returns:
    --------
    dict containing:
        - 'detailed_results': Full results dictionary
        - 'summary_table': Summary DataFrame (if return_summary_table=True)
    """
    
    if comparison_methods is None:
        comparison_methods = ["SELF_RAG", "CRAG_RAG", "BASIC_RAG"]
    
    if metrics is None:
        metrics = ["final_answer_correct", "precision", "recall", "f1"]
    
    if print_detailed:
        print("🚀 COMPREHENSIVE RAG METHOD COMPARISON")
        print("=" * 80)
        print(f"📊 BASE METHOD: {base_method}")
        print("=" * 80)
        
        # Column detection
        print_column_detection(df, base_method, comparison_methods, metrics)
    
    # Store all results
    detailed_results = {}
    
    # Run all comparisons
    for comparison_method in comparison_methods:
        detailed_results[comparison_method] = {}
        
        for metric in metrics:
            # Find columns
            base_col = find_column(df, base_method, metric)
            comp_col = find_column(df, comparison_method, metric)
            
            if base_col is None or comp_col is None:
                detailed_results[comparison_method][metric] = {'error': 'Column not found'}
                continue
            
            # Different handling based on metric type
            if metric == "final_answer_correct":
                # Binary metric
                base_values = df[base_col].astype(bool).tolist()
                comp_values = df[comp_col].astype(bool).tolist()
                
                result = compare_binary_metrics(
                    base_values, comp_values, base_method, comparison_method
                )
                
            else:
                # Continuous metric
                base_values = df[base_col].astype(float)
                comp_values = df[comp_col].astype(float)
                
                result = compare_continuous_metrics(
                    base_values, comp_values, base_method, comparison_method
                )
            
            detailed_results[comparison_method][metric] = result
    
    if print_detailed:
        # Print summary table
        metric_display = {
            "final_answer_correct": "Accuracy",
            "precision": "Precision", 
            "recall": "Recall",
            "f1": "F1 Score"
        }
        
        print(f"\n📋 SUMMARY TABLE - P-VALUES")
        print("-" * 80)
        print(f"{'Metric':<20} {'Test Type':<15} {'vs SELF_RAG':<12} {'vs CRAG_RAG':<12} {'vs BASIC_RAG':<12}")
        print("-" * 80)
        
        for metric in metrics:
            test_type = "McNemar's" if metric == "final_answer_correct" else "T-Test"
            row = f"{metric_display[metric]:<20} {test_type:<15}"
            
            for method in comparison_methods:
                if metric in detailed_results[method]:
                    result = detailed_results[method][metric]
                    if 'error' not in result:
                        p_val = result['p_value']
                        if p_val < 0.001:
                            p_str = "< 0.001***"
                        elif p_val < 0.01:
                            p_str = f"{p_val:.3f}**"
                        elif p_val < 0.05:
                            p_str = f"{p_val:.3f}*"
                        else:
                            p_str = f"{p_val:.3f}"
                        row += f"{p_str:<12}"
                    else:
                        row += f"{'ERROR':<12}"
                else:
                    row += f"{'N/A':<12}"
            print(row)
        
        print("-" * 80)
        print("*** p < 0.001 (highly significant)")
        print("**  p < 0.01  (very significant)")
        print("*   p < 0.05  (significant)")
        
        # Detailed results
        for comparison_method in comparison_methods:
            print(f"\n\n🎯 DETAILED ANALYSIS: {base_method} vs {comparison_method}")
            print("=" * 80)
            
            for metric in metrics:
                print(f"\n📊 METRIC: {metric_display.get(metric, metric).upper()}")
                print("-" * 60)
                
                if metric not in detailed_results[comparison_method]:
                    print("❌ ERROR: Analysis not performed")
                    continue
                    
                result = detailed_results[comparison_method][metric]
                
                if 'error' in result:
                    print(f"❌ ERROR: {result['error']}")
                    continue
                
                # Print column info
                base_col = find_column(df, base_method, metric)
                comp_col = find_column(df, comparison_method, metric)
                print(f"📁 COLUMNS USED:")
                print(f"   {base_method}: {base_col}")
                print(f"   {comparison_method}: {comp_col}")
                
                if metric == "final_answer_correct":
                    # Binary metric results
                    print(f"\n🔍 TEST TYPE: McNemar's Test (Binary Data)")
                    print(f"   {base_method}: {result['method1_accuracy']:.1%} accuracy")
                    print(f"   {comparison_method}: {result['method2_accuracy']:.1%} accuracy")
                    print(f"   Difference: {result['method2_accuracy'] - result['method1_accuracy']:+.1%}")
                    print(f"   P-value: {result['p_value']:.6f}")
                    print(f"   Significant: {'🟢 YES' if result['is_significant'] else '🔴 NO'}")
                    
                    print_contingency_matrix(result['contingency_table'], base_method, comparison_method)
                    
                else:
                    # Continuous metric results
                    print(f"\n🔍 TEST TYPE: Paired T-Test (Continuous Data)")
                    print_continuous_results(result, base_method, comparison_method, metric)
    
    # Create summary table
    output = {'detailed_results': detailed_results}
    
    if return_summary_table:
        summary_table = create_summary_table(detailed_results, base_method, comparison_methods, metrics)
        output['summary_table'] = summary_table
        
        if print_detailed:
            print(f"\n\n📊 SUMMARY TABLE (DataFrame)")
            print("=" * 120)
            print(summary_table.to_string(index=False))
    
    return output

# Main function to use
def analyze_rag_experiments_complete(df, base_method="SEAL RAG", comparison_methods=None, 
                                   metrics=None, print_detailed=True):
    """
    Complete analysis function that returns both detailed results and summary table
    
    Usage:
    ------
    results = analyze_rag_experiments_complete(df)
    
    # Access summary table
    summary_df = results['summary_table']
    
    # Access detailed results
    detailed = results['detailed_results']
    """
    
    return run_comprehensive_comparison_with_summary(
        df=df,
        base_method=base_method,
        comparison_methods=comparison_methods,
        metrics=metrics,
        print_detailed=print_detailed,
        return_summary_table=True
    )

# Usage examples:
# results = analyze_rag_experiments_complete(df)
# summary_table = results['summary_table']
# detailed_results = results['detailed_results']

# Save summary table to CSV
# summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter significant results only
# significant_results = summary_table[summary_table['Is_Significant'] == True]

## 2WikiMultihopQA Dataset

In [7]:
import os
os.getcwd()

'/Users/moshelahmy/Documents/personal/thesis/seal_rag_iclr'

### Model 4o | K = 1

In [8]:
df = pd.read_csv("src/files/experiment_comparison/2WikiMultihopQA/seal_rag_k_1_model_4o.csv")
#df = df.iloc[:, 30:]
df
#/Users/moshelahmy/Documents/personal/thesis/seal_rag_iclr/src/files/experiment_comparison/2WikiMultihopQA/seal_rag_k_1_model_4o.csv

,id,inputs,reference_outputs,basic_rag_200_k_1_model_4o_v1-43ebdafd_outputs,crag_rag_200_k_1_model_4o_v11-51fd11f6_outputs,seal_rag_200_k_1_model_4o-3aba8ef8_outputs,self_rag_200_k_1_model_4o_v1-bad290e1_outputs,basic_rag_200_k_1_model_4o_v1-43ebdafd_run,crag_rag_200_k_1_model_4o_v11-51fd11f6_run,seal_rag_200_k_1_model_4o-3aba8ef8_run,...,seal_rag_200_k_1_model_4o-3aba8ef8_recall,self_rag_200_k_1_model_4o_v1-bad290e1_recall,basic_rag_200_k_1_model_4o_v1-43ebdafd_f1,crag_rag_200_k_1_model_4o_v11-51fd11f6_f1,seal_rag_200_k_1_model_4o-3aba8ef8_f1,self_rag_200_k_1_model_4o_v1-bad290e1_f1,basic_rag_200_k_1_model_4o_v1-43ebdafd_final_answer_correct,crag_rag_200_k_1_model_4o_v11-51fd11f6_final_answer_correct,seal_rag_200_k_1_model_4o-3aba8ef8_final_answer_correct,self_rag_200_k_1_model_4o_v1-bad290e1_final_answer_correct
0,002de458-f6e2-4ef7-991f-6c31359ec71c,"{""context"": ""{'title': ['Richard Annesley, 3rd...","{""answer"": ""2 September 1770""}","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""Annesley, William Richard (1...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [], ""response"": ""I don't know....","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.00,0.0,0.6667,0.0000,1.0000,0.0000,0.0,0.0,1.0,0.0
1,009279eb-aa2f-4e9a-a388-0570b3d0fad7,"{""context"": ""{'title': ['Caspar Babypants', 'B...","{""answer"": ""Liverpool""}","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Lennon: John Winston On...","{""docs_to_use"": [], ""response"": ""Liverpool, En...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.0,0.6667,0.6667,0.6667,0.0000,0.0,0.0,1.0,1.0
2,01afabb2-0984-4333-bfff-0b3ad45cc593,"{""context"": ""{'title': ['M. Venkataraju', 'Wor...","{""answer"": ""United States""}","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough is a 1...","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [], ""response"": ""I don't know....","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.0,0.6667,0.0000,0.6667,0.0000,0.0,0.0,0.0,0.0
3,04491c40-8385-4c7c-9d07-665afd6ef52d,"{""context"": ""{'title': ['James Woolley (clockm...","{""answer"": ""Madame Pasca""}","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""D6. James A. Donohoe (August...","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""James A. Donohoe: James A. D...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.5,0.0000,0.0000,0.5000,0.6667,0.0,1.0,1.0,1.0
4,097adb49-d636-4e90-b9cf-ffed265452f6,"{""context"": ""{'title': ['Takayama Tomoteru', '...","{""answer"": ""Galați""}","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.5,0.6667,0.6667,0.6667,0.6667,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,fc20c2aa-4e58-4517-ad1a-a050f0283457,"{""context"": ""{'title': ['Language Management',...","{""answer"": ""yes""}","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland is a German hyperma...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.00,0.5,0.6667,0.0000,1.0000,0.6667,0.0,1.0,1.0,1.0
196,fc9ea4fb-5063-4d64-9bd3-e52efb03ecbe,"{""context"": ""{'title': ['Jayam Manade', 'Bulld...","{""answer"": ""Bulldog Drummond'S Revenge""}","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Nimmala Shankar is an Indian...","{""docs_to_use"": [""Bulldog Drummond's Revenge: ...","{""docs_to_use"": [], ""response"": ""\""Jayam Manad...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.75,0.0,0.4000,0.0000,0.8571,0.0000,0.0,0.0,1.0,0.0
197,fd41bcf3-aeb3-4d4e-80f7-580d7864172a,"{""context"": ""{'title': ['Control engineering',...","{""answer"": ""yes""}","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems is an un...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.00,0.5,0.6667,0.0000,1.0000,0.6667,1.0,0.0,1.0,1.0
198,fd8c17b6-5955-4adc-911f-a3d54ab6487e,"{""context"": ""{'title': ['Isipum of Geumgwan Ga...","{""answer"": ""India""}","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.5,0.6667,0.6667,0.6667,0.6667,0.0,0.0,0.0,1.0
199,fed9201d-05bd-4208-aa29-11b94b32d17f,"{""context"": ""{'title': ['Marcel Brands', 'Eric...","{""answer"": ""Víctor Bó""}","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""| Directed by | Armando Bó |...","{""docs_to_use"": [""Armando Bó: Armando Bó (3 Ma...","{""docs_to_use"": [], ""response"": ""I don't know....","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.0,0.6667,0.0000,0.6667,0.0000,0.0,0.0,1.0,0.0

In [9]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_outputs',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_outputs',
 'seal_rag_200_k_1_model_4o-3aba8ef8_outputs',
 'self_rag_200_k_1_model_4o_v1-bad290e1_outputs',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_run',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_run',
 'seal_rag_200_k_1_model_4o-3aba8ef8_run',
 'self_rag_200_k_1_model_4o_v1-bad290e1_run',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_status',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_status',
 'seal_rag_200_k_1_model_4o-3aba8ef8_status',
 'self_rag_200_k_1_model_4o_v1-bad290e1_status',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_error',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_error',
 'seal_rag_200_k_1_model_4o-3aba8ef8_error',
 'self_rag_200_k_1_model_4o_v1-bad290e1_error',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_latency',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_latency',
 'seal_rag_200_k_1_model_4o-3aba8ef8_latency',
 'self_rag_200_k_1_model_4o_v1-bad290e1_latency',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_tokens',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_tokens',
 'seal_rag_200_k_1_model_4o-3aba8ef8_tokens',
 'self_rag_200_k_1_model_4o_v1-bad290e1_tokens',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_total_cost',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_total_cost',
 'seal_rag_200_k_1_model_4o-3aba8ef8_total_cost',
 'self_rag_200_k_1_model_4o_v1-bad290e1_total_cost',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_precision',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_precision',
 'seal_rag_200_k_1_model_4o-3aba8ef8_precision',
 'self_rag_200_k_1_model_4o_v1-bad290e1_precision',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_recall',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_recall',
 'seal_rag_200_k_1_model_4o-3aba8ef8_recall',
 'self_rag_200_k_1_model_4o_v1-bad290e1_recall',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_f1',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_f1',
 'seal_rag_200_k_1_model_4o-3aba8ef8_f1',
 'self_rag_200_k_1_model_4o_v1-bad290e1_f1',
 'basic_rag_200_k_1_model_4o_v1-43ebdafd_final_answer_correct',
 'crag_rag_200_k_1_model_4o_v11-51fd11f6_final_answer_correct',
 'seal_rag_200_k_1_model_4o-3aba8ef8_final_answer_correct',
 'self_rag_200_k_1_model_4o_v1-bad290e1_final_answer_correct']

In [10]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_200_k_1_model_4o-3aba8ef8_final_answer_correct
   ✅ precision            → seal_rag_200_k_1_model_4o-3aba8ef8_precision
   ✅ recall               → seal_rag_200_k_1_model_4o-3aba8ef8_recall
   ✅ f1                   → seal_rag_200_k_1_model_4o-3aba8ef8_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_200_k_1_model_4o_v1-bad290e1_final_answer_correct
   ✅ precision            → self_rag_200_k_1_model_4o_v1-bad290e1_precision
   ✅ recall               → self_rag_200_k_1_model_4o_v1-bad290e1_recall
   ✅ f1                   → self_rag_200_k_1_model_4o_v1-bad290e1_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_200_k_1_model_4o_v11-51fd11f6_final_answer_correct
   ✅ precision            → crag_rag_200_k_1_model_4o_v11-51fd11f6_precision
   ✅ recall               → crag_rag_200_k_1_model_4o_v11-51fd11f6_recall
   ✅ f1                   → crag_rag_200_k_1_model_4o_v11-51fd11f6_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_200_k_1_model_4o_v1-43ebdafd_final_answer_correct
   ✅ precision            → basic_rag_200_k_1_model_4o_v1-43ebdafd_precision
   ✅ recall               → basic_rag_200_k_1_model_4o_v1-43ebdafd_recall
   ✅ f1                   → basic_rag_200_k_1_model_4o_v1-43ebdafd_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  0.012*
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_final_answer_correct
   SELF_RAG: self_rag_200_k_1_model_4o_v1-bad290e1_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.0% accuracy
   SELF_RAG: 36.5% accuracy
   Difference: -39.5%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     41        7       48
         Right     86       66      152
--------------------------------------------------
         Total    127       73      200

🔍 INTERPRETATION:
   Both wrong:  41 questions
   SELF_RAG wins:   7 questions (when SEAL RAG fails)
   SEAL RAG wins:  86 questions (when SELF_RAG fails)
   Both right:  66 questions
   Disagreements:  93 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 12.3x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_precision
   SELF_RAG: self_rag_200_k_1_model_4o_v1-bad290e1_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9500 ± 0.1941
   SELF_RAG: 0.4150 ± 0.4940
   Mean difference: +0.5350
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 14.8361
   P-value: 0.000000
   Effect size (Cohen's d): 1.0491
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_recall
   SELF_RAG: self_rag_200_k_1_model_4o_v1-bad290e1_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7538 ± 0.2819
   SELF_RAG: 0.1938 ± 0.2370
   Mean difference: +0.5600
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 23.6025
   P-value: 0.000000
   Effect size (Cohen's d): 1.6689
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_f1
   SELF_RAG: self_rag_200_k_1_model_4o_v1-bad290e1_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8190 ± 0.2307
   SELF_RAG: 0.2620 ± 0.3173
   Mean difference: +0.5570
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 21.8654
   P-value: 0.000000
   Effect size (Cohen's d): 1.5461
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_final_answer_correct
   CRAG_RAG: crag_rag_200_k_1_model_4o_v11-51fd11f6_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.0% accuracy
   CRAG_RAG: 28.5% accuracy
   Difference: -47.5%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     41        7       48
         Right    102       50      152
--------------------------------------------------
         Total    143       57      200

🔍 INTERPRETATION:
   Both wrong:  41 questions
   CRAG_RAG wins:   7 questions (when SEAL RAG fails)
   SEAL RAG wins: 102 questions (when CRAG_RAG fails)
   Both right:  50 questions
   Disagreements: 109 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 14.6x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_precision
   CRAG_RAG: crag_rag_200_k_1_model_4o_v11-51fd11f6_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9500 ± 0.1941
   CRAG_RAG: 0.2100 ± 0.4083
   Mean difference: +0.7400
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 24.4425
   P-value: 0.000000
   Effect size (Cohen's d): 1.7283
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_recall
   CRAG_RAG: crag_rag_200_k_1_model_4o_v11-51fd11f6_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7538 ± 0.2819
   CRAG_RAG: 0.1037 ± 0.2025
   Mean difference: +0.6500
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 27.4141
   P-value: 0.000000
   Effect size (Cohen's d): 1.9385
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_f1
   CRAG_RAG: crag_rag_200_k_1_model_4o_v11-51fd11f6_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8190 ± 0.2307
   CRAG_RAG: 0.1387 ± 0.2703
   Mean difference: +0.6803
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 28.4524
   P-value: 0.000000
   Effect size (Cohen's d): 2.0119
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_final_answer_correct
   BASIC_RAG: basic_rag_200_k_1_model_4o_v1-43ebdafd_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.0% accuracy
   BASIC_RAG: 14.5% accuracy
   Difference: -61.5%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     44        4       48
         Right    127       25      152
--------------------------------------------------
         Total    171       29      200

🔍 INTERPRETATION:
   Both wrong:  44 questions
   BASIC_RAG wins:   4 questions (when SEAL RAG fails)
   SEAL RAG wins: 127 questions (when BASIC_RAG fails)
   Both right:  25 questions
   Disagreements: 131 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 31.8x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_precision
   BASIC_RAG: basic_rag_200_k_1_model_4o_v1-43ebdafd_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9500 ± 0.1941
   BASIC_RAG: 0.9250 ± 0.2641
   Mean difference: +0.0250
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 2.5336
   P-value: 0.012059
   Effect size (Cohen's d): 0.1792
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: negligible

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_recall
   BASIC_RAG: basic_rag_200_k_1_model_4o_v1-43ebdafd_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7538 ± 0.2819
   BASIC_RAG: 0.4138 ± 0.1537
   Mean difference: +0.3400
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 18.4575
   P-value: 0.000000
   Effect size (Cohen's d): 1.3051
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o-3aba8ef8_f1
   BASIC_RAG: basic_rag_200_k_1_model_4o_v1-43ebdafd_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8190 ± 0.2307
   BASIC_RAG: 0.5647 ± 0.1923
   Mean difference: +0.2543
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 17.7629
   P-value: 0.000000
   Effect size (Cohen's d): 1.2560
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name      P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared 6.054138e-16            True          p < 0.001            76.0%                  36.5%                 -39.5%               86                7 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic 5.060562e-34            True          p < 0.001            0.950                  0.415                 +0.535 N/A (Continuous) N/A (Continuous)        1.049      t = 14.836
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic 1.368244e-59            True          p < 0.001            0.754                  0.194                 +0.560 N/A (Continuous) N/A (Continuous)        1.669      t = 23.602
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic 8.181487e-55            True          p < 0.001            0.819                  0.262                 +0.557 N/A (Continuous) N/A (Continuous)        1.546      t = 21.865
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared 2.185004e-19            True          p < 0.001            76.0%                  28.5%                 -47.5%              102                7 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 7.674097e-62            True          p < 0.001            0.950                  0.210                 +0.740 N/A (Continuous) N/A (Continuous)        1.728      t = 24.443
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 1.700809e-69            True          p < 0.001            0.754                  0.104                 +0.650 N/A (Continuous) N/A (Continuous)        1.938      t = 27.414
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 4.651584e-72            True          p < 0.001            0.819                  0.139                 +0.680 N/A (Continuous) N/A (Continuous)        2.012      t = 28.452
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared 1.579681e-26            True          p < 0.001            76.0%                  14.5%                 -61.5%              127                4 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 1.205897e-02            True           p < 0.05            0.950                  0.925                 +0.025 N/A (Continuous) N/A (Continuous)        0.179       t = 2.534
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 5.482097e-45            True          p < 0.001            0.754                  0.414                 +0.340 N/A (Continuous) N/A (Continuous)        1.305      t = 18.458
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic 6.429250e-43            True          p < 0.001            0.819                  0.565                 +0.254 N/A (Continuous) N/A (Continuous)        1.256      t = 17.763
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   6.054138e-16            True          p < 0.001            76.0%
1   5.060562e-34            True          p < 0.001            0.950
2   1.368244e-59            True          p < 0.001            0.754
3   8.181487e-55            True          p < 0.001            0.819
4   2.185004e-19            True          p < 0.001            76.0%
5   7.674097e-62            True          p < 0.001            0.950
6   1.700809e-69            True          p < 0.001            0.754
7   4.651584e-72            True          p < 0.001            0.819
8   1.579681e-26            True          p < 0.001            76.0%
9   1.205897e-02            True           p < 0.05            0.950
10  5.482097e-45            True          p < 0.001            0.754
11  6.429250e-43            True          p < 0.001            0.819

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   36.5%                 -39.5%                86
1                   0.415                 +0.535  N/A (Continuous)
2                   0.194                 +0.560  N/A (Continuous)
3                   0.262                 +0.557  N/A (Continuous)
4                   28.5%                 -47.5%               102
5                   0.210                 +0.740  N/A (Continuous)
6                   0.104                 +0.650  N/A (Continuous)
7                   0.139                 +0.680  N/A (Continuous)
8                   14.5%                 -61.5%               127
9                   0.925                 +0.025  N/A (Continuous)
10                  0.414                 +0.340  N/A (Continuous)
11                  0.565                 +0.254  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                  7  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         1.049      t = 14.836
2   N/A (Continuous)         1.669      t = 23.602
3   N/A (Continuous)         1.546      t = 21.865
4                  7  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         1.728      t = 24.443
6   N/A (Continuous)         1.938      t = 27.414
7   N/A (Continuous)         2.012      t = 28.452
8                  4  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         0.179       t = 2.534
10  N/A (Continuous)         1.305      t = 18.458
11  N/A (Continuous)         1.256      t = 17.763

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   6.054138e-16            True          p < 0.001            76.0%
1   5.060562e-34            True          p < 0.001            0.950
2   1.368244e-59            True          p < 0.001            0.754
3   8.181487e-55            True          p < 0.001            0.819

### Model 4o | k = 3

In [11]:
df = pd.read_csv("src/files/experiment_comparison/2WikiMultihopQA/seal_rag_k_3_model_4o.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,basic_rag_200_k_3_model_4o_v3-aee57205_outputs,crag_rag_200_k_3_model_4o_v10-cdeb6d45_outputs,seal_rag_200_k_3_model_4o_v6-1a1c278d_outputs,self_rag_200_k_3_model_4o_v6-9b67a3a9_outputs,basic_rag_200_k_3_model_4o_v3-aee57205_run,crag_rag_200_k_3_model_4o_v10-cdeb6d45_run,seal_rag_200_k_3_model_4o_v6-1a1c278d_run,...,seal_rag_200_k_3_model_4o_v6-1a1c278d_final_answer_correct,self_rag_200_k_3_model_4o_v6-9b67a3a9_final_answer_correct,basic_rag_200_k_3_model_4o_v3-aee57205_f1,crag_rag_200_k_3_model_4o_v10-cdeb6d45_f1,seal_rag_200_k_3_model_4o_v6-1a1c278d_f1,self_rag_200_k_3_model_4o_v6-9b67a3a9_f1,basic_rag_200_k_3_model_4o_v3-aee57205_recall,crag_rag_200_k_3_model_4o_v10-cdeb6d45_recall,seal_rag_200_k_3_model_4o_v6-1a1c278d_recall,self_rag_200_k_3_model_4o_v6-9b67a3a9_recall
0,002de458-f6e2-4ef7-991f-6c31359ec71c,"{""context"": ""{'title': ['Richard Annesley, 3rd...","{""answer"": ""2 September 1770""}","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""On 02 Sep 1770 [his father] ...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [], ""response"": ""No informatio...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,0.0,0.4000,0.0,0.6667,0.0000,0.5,0.0,0.5,0.00
1,009279eb-aa2f-4e9a-a388-0570b3d0fad7,"{""context"": ""{'title': ['Caspar Babypants', 'B...","{""answer"": ""Liverpool""}","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Lennon: John Winston On...","{""docs_to_use"": [""John Lennon: John Winston On...","{""docs_to_use"": [""John Lennon: John Winston On...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,0.8000,0.5,0.6667,0.6667,1.0,0.5,0.5,0.50
2,01afabb2-0984-4333-bfff-0b3ad45cc593,"{""context"": ""{'title': ['M. Venkataraju', 'Wor...","{""answer"": ""United States""}","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough is a 1...","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough: World...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,1.0,0.4000,0.0,0.6667,0.6667,0.5,0.0,0.5,0.50
3,04491c40-8385-4c7c-9d07-665afd6ef52d,"{""context"": ""{'title': ['James Woolley (clockm...","{""answer"": ""Madame Pasca""}","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""D6. James A. Donohoe (August...","{""docs_to_use"": [""James A. Donohoe: James A. D...","{""docs_to_use"": [""Madame Pasca: Alice Marie An...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,0.8000,0.0,1.0000,0.6667,1.0,0.0,1.0,0.50
4,097adb49-d636-4e90-b9cf-ffed265452f6,"{""context"": ""{'title': ['Takayama Tomoteru', '...","{""answer"": ""Galați""}","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,0.8000,0.5,0.6667,0.6667,1.0,0.5,0.5,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,fc20c2aa-4e58-4517-ad1a-a050f0283457,"{""context"": ""{'title': ['Language Management',...","{""answer"": ""yes""}","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""OTRAG: OTRAG( or), was a Ger...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,0.8000,0.5,1.0000,1.0000,1.0,0.5,1.0,1.00
196,fc9ea4fb-5063-4d64-9bd3-e52efb03ecbe,"{""context"": ""{'title': ['Jayam Manade', 'Bulld...","{""answer"": ""Bulldog Drummond'S Revenge""}","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Nimmala Shankar is an Indian...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Bulldog Drummond's Revenge: ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,0.0,0.5714,0.0,1.0000,0.4000,0.5,0.0,1.0,0.25
197,fd41bcf3-aeb3-4d4e-80f7-580d7864172a,"{""context"": ""{'title': ['Control engineering',...","{""answer"": ""yes""}","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,0.8000,0.8,1.0000,1.0000,1.0,1.0,1.0,1.00
198,fd8c17b6-5955-4adc-911f-a3d54ab6487e,"{""context"": ""{'title': ['Isipum of Geumgwan Ga...","{""answer"": ""India""}","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,0.0,0.4000,0.4,1.0000,0.5000,0.5,0.5,1.0,0.50
199,fed9201d-05bd-4208-aa29-11b94b32d17f,"{""context"": ""{'title': ['Marcel Brands', 'Eric...","{""answer"": ""Víctor Bó""}","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""| Directed by | Armando Bó |...","{""docs_to_use"": [""Armando Bó: Armando Bó (3 Ma...","{""docs_to_use"": [], ""response"": ""I don't know....","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,0.0,0.4000,0.0,0.6667,0.0000,0.5,0.0,0.5,0.00

In [12]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'basic_rag_200_k_3_model_4o_v3-aee57205_outputs',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_outputs',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_outputs',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_outputs',
 'basic_rag_200_k_3_model_4o_v3-aee57205_run',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_run',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_run',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_run',
 'basic_rag_200_k_3_model_4o_v3-aee57205_status',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_status',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_status',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_status',
 'basic_rag_200_k_3_model_4o_v3-aee57205_error',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_error',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_error',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_error',
 'basic_rag_200_k_3_model_4o_v3-aee57205_latency',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_latency',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_latency',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_latency',
 'basic_rag_200_k_3_model_4o_v3-aee57205_tokens',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_tokens',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_tokens',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_tokens',
 'basic_rag_200_k_3_model_4o_v3-aee57205_total_cost',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_total_cost',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_total_cost',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_total_cost',
 'basic_rag_200_k_3_model_4o_v3-aee57205_precision',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_precision',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_precision',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_precision',
 'basic_rag_200_k_3_model_4o_v3-aee57205_final_answer_correct',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_final_answer_correct',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_final_answer_correct',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_final_answer_correct',
 'basic_rag_200_k_3_model_4o_v3-aee57205_f1',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_f1',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_f1',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_f1',
 'basic_rag_200_k_3_model_4o_v3-aee57205_recall',
 'crag_rag_200_k_3_model_4o_v10-cdeb6d45_recall',
 'seal_rag_200_k_3_model_4o_v6-1a1c278d_recall',
 'self_rag_200_k_3_model_4o_v6-9b67a3a9_recall']

In [13]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_200_k_3_model_4o_v6-1a1c278d_final_answer_correct
   ✅ precision            → seal_rag_200_k_3_model_4o_v6-1a1c278d_precision
   ✅ recall               → seal_rag_200_k_3_model_4o_v6-1a1c278d_recall
   ✅ f1                   → seal_rag_200_k_3_model_4o_v6-1a1c278d_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_200_k_3_model_4o_v6-9b67a3a9_final_answer_correct
   ✅ precision            → self_rag_200_k_3_model_4o_v6-9b67a3a9_precision
   ✅ recall               → self_rag_200_k_3_model_4o_v6-9b67a3a9_recall
   ✅ f1                   → self_rag_200_k_3_model_4o_v6-9b67a3a9_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_200_k_3_model_4o_v10-cdeb6d45_final_answer_correct
   ✅ precision            → crag_rag_200_k_3_model_4o_v10-cdeb6d45_precision
   ✅ recall               → crag_rag_200_k_3_model_4o_v10-cdeb6d45_recall
   ✅ f1                   → crag_rag_200_k_3_model_4o_v10-cdeb6d45_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_200_k_3_model_4o_v3-aee57205_final_answer_correct
   ✅ precision            → basic_rag_200_k_3_model_4o_v3-aee57205_precision
   ✅ recall               → basic_rag_200_k_3_model_4o_v3-aee57205_recall
   ✅ f1                   → basic_rag_200_k_3_model_4o_v3-aee57205_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_final_answer_correct
   SELF_RAG: self_rag_200_k_3_model_4o_v6-9b67a3a9_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.5% accuracy
   SELF_RAG: 56.5% accuracy
   Difference: -20.0%
   P-value: 0.000001
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     35       12       47
         Right     52      101      153
--------------------------------------------------
         Total     87      113      200

🔍 INTERPRETATION:
   Both wrong:  35 questions
   SELF_RAG wins:  12 questions (when SEAL RAG fails)
   SEAL RAG wins:  52 questions (when SELF_RAG fails)
   Both right: 101 questions
   Disagreements:  64 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 4.3x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_precision
   SELF_RAG: self_rag_200_k_3_model_4o_v6-9b67a3a9_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9708 ± 0.1451
   SELF_RAG: 0.6033 ± 0.4716
   Mean difference: +0.3675
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 10.8210
   P-value: 0.000000
   Effect size (Cohen's d): 0.7652
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_recall
   SELF_RAG: self_rag_200_k_3_model_4o_v6-9b67a3a9_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7725 ± 0.2643
   SELF_RAG: 0.3463 ± 0.3245
   Mean difference: +0.4263
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 15.9010
   P-value: 0.000000
   Effect size (Cohen's d): 1.1244
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_f1
   SELF_RAG: self_rag_200_k_3_model_4o_v6-9b67a3a9_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8384 ± 0.2025
   SELF_RAG: 0.4172 ± 0.3494
   Mean difference: +0.4212
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 15.9635
   P-value: 0.000000
   Effect size (Cohen's d): 1.1288
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_final_answer_correct
   CRAG_RAG: crag_rag_200_k_3_model_4o_v10-cdeb6d45_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.5% accuracy
   CRAG_RAG: 60.0% accuracy
   Difference: -16.5%
   P-value: 0.000055
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     32       15       47
         Right     48      105      153
--------------------------------------------------
         Total     80      120      200

🔍 INTERPRETATION:
   Both wrong:  32 questions
   CRAG_RAG wins:  15 questions (when SEAL RAG fails)
   SEAL RAG wins:  48 questions (when CRAG_RAG fails)
   Both right: 105 questions
   Disagreements:  63 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 3.2x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_precision
   CRAG_RAG: crag_rag_200_k_3_model_4o_v10-cdeb6d45_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9708 ± 0.1451
   CRAG_RAG: 0.1800 ± 0.2475
   Mean difference: +0.7908
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 41.2747
   P-value: 0.000000
   Effect size (Cohen's d): 2.9186
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_recall
   CRAG_RAG: crag_rag_200_k_3_model_4o_v10-cdeb6d45_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7725 ± 0.2643
   CRAG_RAG: 0.1913 ± 0.2824
   Mean difference: +0.5813
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 22.3714
   P-value: 0.000000
   Effect size (Cohen's d): 1.5819
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_f1
   CRAG_RAG: crag_rag_200_k_3_model_4o_v10-cdeb6d45_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8384 ± 0.2025
   CRAG_RAG: 0.1822 ± 0.2567
   Mean difference: +0.6562
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 29.9645
   P-value: 0.000000
   Effect size (Cohen's d): 2.1188
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_final_answer_correct
   BASIC_RAG: basic_rag_200_k_3_model_4o_v3-aee57205_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.5% accuracy
   BASIC_RAG: 56.0% accuracy
   Difference: -20.5%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     36       11       47
         Right     52      101      153
--------------------------------------------------
         Total     88      112      200

🔍 INTERPRETATION:
   Both wrong:  36 questions
   BASIC_RAG wins:  11 questions (when SEAL RAG fails)
   SEAL RAG wins:  52 questions (when BASIC_RAG fails)
   Both right: 101 questions
   Disagreements:  63 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 4.7x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_precision
   BASIC_RAG: basic_rag_200_k_3_model_4o_v3-aee57205_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9708 ± 0.1451
   BASIC_RAG: 0.5267 ± 0.1716
   Mean difference: +0.4442
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 29.3281
   P-value: 0.000000
   Effect size (Cohen's d): 2.0738
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_recall
   BASIC_RAG: basic_rag_200_k_3_model_4o_v3-aee57205_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7725 ± 0.2643
   BASIC_RAG: 0.6937 ± 0.2524
   Mean difference: +0.0788
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 3.4638
   P-value: 0.000652
   Effect size (Cohen's d): 0.2449
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_v6-1a1c278d_f1
   BASIC_RAG: basic_rag_200_k_3_model_4o_v3-aee57205_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8384 ± 0.2025
   BASIC_RAG: 0.5880 ± 0.1879
   Mean difference: +0.2504
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 14.8078
   P-value: 0.000000
   Effect size (Cohen's d): 1.0471
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name      P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared 1.088085e-06            True          p < 0.001            76.5%                  56.5%                 -20.0%               52               12 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic 9.294547e-22            True          p < 0.001            0.971                  0.603                 +0.367 N/A (Continuous) N/A (Continuous)        0.765      t = 10.821
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic 2.760523e-37            True          p < 0.001            0.772                  0.346                 +0.426 N/A (Continuous) N/A (Continuous)        1.124      t = 15.901
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic 1.779168e-37            True          p < 0.001            0.838                  0.417                 +0.421 N/A (Continuous) N/A (Continuous)        1.129      t = 15.964
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared 5.539345e-05            True          p < 0.001            76.5%                  60.0%                 -16.5%               48               15 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 1.646159e-99            True          p < 0.001            0.971                  0.180                 +0.791 N/A (Continuous) N/A (Continuous)        2.919      t = 41.275
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 3.195515e-56            True          p < 0.001            0.772                  0.191                 +0.581 N/A (Continuous) N/A (Continuous)        1.582      t = 22.371
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 1.084773e-75            True          p < 0.001            0.838                  0.182                 +0.656 N/A (Continuous) N/A (Continuous)        2.119      t = 29.965
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared 4.666855e-07            True          p < 0.001            76.5%                  56.0%                 -20.5%               52               11 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 3.546723e-74            True          p < 0.001            0.971                  0.527                 +0.444 N/A (Continuous) N/A (Continuous)        2.074      t = 29.328
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 6.521145e-04            True          p < 0.001            0.772                  0.694                 +0.079 N/A (Continuous) N/A (Continuous)        0.245       t = 3.464
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic 6.181219e-34            True          p < 0.001            0.838                  0.588                 +0.250 N/A (Continuous) N/A (Continuous)        1.047      t = 14.808
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   1.088085e-06            True          p < 0.001            76.5%
1   9.294547e-22            True          p < 0.001            0.971
2   2.760523e-37            True          p < 0.001            0.772
3   1.779168e-37            True          p < 0.001            0.838
4   5.539345e-05            True          p < 0.001            76.5%
5   1.646159e-99            True          p < 0.001            0.971
6   3.195515e-56            True          p < 0.001            0.772
7   1.084773e-75            True          p < 0.001            0.838
8   4.666855e-07            True          p < 0.001            76.5%
9   3.546723e-74            True          p < 0.001            0.971
10  6.521145e-04            True          p < 0.001            0.772
11  6.181219e-34            True          p < 0.001            0.838

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   56.5%                 -20.0%                52
1                   0.603                 +0.367  N/A (Continuous)
2                   0.346                 +0.426  N/A (Continuous)
3                   0.417                 +0.421  N/A (Continuous)
4                   60.0%                 -16.5%                48
5                   0.180                 +0.791  N/A (Continuous)
6                   0.191                 +0.581  N/A (Continuous)
7                   0.182                 +0.656  N/A (Continuous)
8                   56.0%                 -20.5%                52
9                   0.527                 +0.444  N/A (Continuous)
10                  0.694                 +0.079  N/A (Continuous)
11                  0.588                 +0.250  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 12  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.765      t = 10.821
2   N/A (Continuous)         1.124      t = 15.901
3   N/A (Continuous)         1.129      t = 15.964
4                 15  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         2.919      t = 41.275
6   N/A (Continuous)         1.582      t = 22.371
7   N/A (Continuous)         2.119      t = 29.965
8                 11  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         2.074      t = 29.328
10  N/A (Continuous)         0.245       t = 3.464
11  N/A (Continuous)         1.047      t = 14.808

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   1.088085e-06            True          p < 0.001            76.5%
1   9.294547e-22            True          p < 0.001            0.971
2   2.760523e-37            True          p < 0.001            0.772
3   1.779168e-37            True          p < 0.001            0.838

### Model 4o | k = 5

In [14]:
df = pd.read_csv("src/files/experiment_comparison/2WikiMultihopQA/seal_rag_k_5_model_4o.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,basic_rag_200_k_5_model_4o_v11-e2cb6199_outputs,crag_rag_200_k_5_model_4o_v12-37eb0218_outputs,seal_rag_200_k_5_model_4o_v12-ee7046b6_outputs,self_rag_200_k_5_model_4o_v13-7e02b577_outputs,basic_rag_200_k_5_model_4o_v11-e2cb6199_run,crag_rag_200_k_5_model_4o_v12-37eb0218_run,seal_rag_200_k_5_model_4o_v12-ee7046b6_run,...,seal_rag_200_k_5_model_4o_v12-ee7046b6_f1,self_rag_200_k_5_model_4o_v13-7e02b577_f1,basic_rag_200_k_5_model_4o_v11-e2cb6199_precision,crag_rag_200_k_5_model_4o_v12-37eb0218_precision,seal_rag_200_k_5_model_4o_v12-ee7046b6_precision,self_rag_200_k_5_model_4o_v13-7e02b577_precision,basic_rag_200_k_5_model_4o_v11-e2cb6199_final_answer_correct,crag_rag_200_k_5_model_4o_v12-37eb0218_final_answer_correct,seal_rag_200_k_5_model_4o_v12-ee7046b6_final_answer_correct,self_rag_200_k_5_model_4o_v13-7e02b577_final_answer_correct
0,002de458-f6e2-4ef7-991f-6c31359ec71c,"{""context"": ""{'title': ['Richard Annesley, 3rd...","{""answer"": ""2 September 1770""}","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""On 02 Sep 1770 [his father] ...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [], ""response"": ""I don't know....","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.6667,0.0000,0.2,0.0000,1.0,0.0,0.0,1.0,0.0,0.0
1,009279eb-aa2f-4e9a-a388-0570b3d0fad7,"{""context"": ""{'title': ['Caspar Babypants', 'B...","{""answer"": ""Liverpool""}","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Lennon: John Winston On...","{""docs_to_use"": [""John Lennon: John Winston On...","{""docs_to_use"": [""John Lennon: John Winston On...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.6667,0.6667,0.4,0.5000,1.0,1.0,1.0,1.0,1.0,1.0
2,01afabb2-0984-4333-bfff-0b3ad45cc593,"{""context"": ""{'title': ['M. Venkataraju', 'Wor...","{""answer"": ""United States""}","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""You're viewing the Frameline...","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough: World...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.6667,0.6667,0.2,0.0000,1.0,1.0,0.0,1.0,0.0,0.0
3,04491c40-8385-4c7c-9d07-665afd6ef52d,"{""context"": ""{'title': ['James Woolley (clockm...","{""answer"": ""Madame Pasca""}","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""D6. James A. Donohoe (August...","{""docs_to_use"": [""James A. Donohoe: James A. D...","{""docs_to_use"": [""James A. Donohoe: James A. D...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0000,1.0000,0.4,0.0000,1.0,1.0,1.0,1.0,1.0,1.0
4,097adb49-d636-4e90-b9cf-ffed265452f6,"{""context"": ""{'title': ['Takayama Tomoteru', '...","{""answer"": ""Galați""}","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.6667,0.6667,0.4,0.5000,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,fc20c2aa-4e58-4517-ad1a-a050f0283457,"{""context"": ""{'title': ['Language Management',...","{""answer"": ""yes""}","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""OTRAG: OTRAG( or), was a Ger...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0000,1.0000,0.4,0.5000,1.0,1.0,1.0,1.0,1.0,1.0
196,fc9ea4fb-5063-4d64-9bd3-e52efb03ecbe,"{""context"": ""{'title': ['Jayam Manade', 'Bulld...","{""answer"": ""Bulldog Drummond'S Revenge""}","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Nimmala Shankar is an Indian...","{""docs_to_use"": [""Bulldog Drummond's Revenge: ...","{""docs_to_use"": [""Bulldog Drummond's Revenge: ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.8571,0.4000,0.4,0.0000,1.0,1.0,1.0,0.0,1.0,0.0
197,fd41bcf3-aeb3-4d4e-80f7-580d7864172a,"{""context"": ""{'title': ['Control engineering',...","{""answer"": ""yes""}","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0000,1.0000,0.4,0.6667,1.0,1.0,1.0,1.0,1.0,1.0
198,fd8c17b6-5955-4adc-911f-a3d54ab6487e,"{""context"": ""{'title': ['Isipum of Geumgwan Ga...","{""answer"": ""India""}","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0000,0.6667,0.4,0.6667,1.0,0.5,1.0,1.0,1.0,1.0
199,fed9201d-05bd-4208-aa29-11b94b32d17f,"{""context"": ""{'title': ['Marcel Brands', 'Eric...","{""answer"": ""Víctor Bó""}","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""| Directed by | Armando Bó |...","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [], ""response"": ""I don't know....","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0000,0.0000,0.2,0.0000,1.0,0.0,0.0,0.0,1.0,0.0

In [15]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_outputs',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_outputs',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_outputs',
 'self_rag_200_k_5_model_4o_v13-7e02b577_outputs',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_run',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_run',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_run',
 'self_rag_200_k_5_model_4o_v13-7e02b577_run',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_status',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_status',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_status',
 'self_rag_200_k_5_model_4o_v13-7e02b577_status',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_error',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_error',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_error',
 'self_rag_200_k_5_model_4o_v13-7e02b577_error',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_latency',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_latency',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_latency',
 'self_rag_200_k_5_model_4o_v13-7e02b577_latency',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_tokens',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_tokens',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_tokens',
 'self_rag_200_k_5_model_4o_v13-7e02b577_tokens',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_total_cost',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_total_cost',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_total_cost',
 'self_rag_200_k_5_model_4o_v13-7e02b577_total_cost',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_recall',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_recall',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_recall',
 'self_rag_200_k_5_model_4o_v13-7e02b577_recall',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_f1',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_f1',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_f1',
 'self_rag_200_k_5_model_4o_v13-7e02b577_f1',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_precision',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_precision',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_precision',
 'self_rag_200_k_5_model_4o_v13-7e02b577_precision',
 'basic_rag_200_k_5_model_4o_v11-e2cb6199_final_answer_correct',
 'crag_rag_200_k_5_model_4o_v12-37eb0218_final_answer_correct',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_final_answer_correct',
 'self_rag_200_k_5_model_4o_v13-7e02b577_final_answer_correct']

In [16]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_200_k_5_model_4o_v12-ee7046b6_final_answer_correct
   ✅ precision            → seal_rag_200_k_5_model_4o_v12-ee7046b6_precision
   ✅ recall               → seal_rag_200_k_5_model_4o_v12-ee7046b6_recall
   ✅ f1                   → seal_rag_200_k_5_model_4o_v12-ee7046b6_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_200_k_5_model_4o_v13-7e02b577_final_answer_correct
   ✅ precision            → self_rag_200_k_5_model_4o_v13-7e02b577_precision
   ✅ recall               → self_rag_200_k_5_model_4o_v13-7e02b577_recall
   ✅ f1                   → self_rag_200_k_5_model_4o_v13-7e02b577_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_200_k_5_model_4o_v12-37eb0218_final_answer_correct
   ✅ precision            → crag_rag_200_k_5_model_4o_v12-37eb0218_precision
   ✅ recall               → crag_rag_200_k_5_model_4o_v12-37eb0218_recall
   ✅ f1                   → crag_rag_200_k_5_model_4o_v12-37eb0218_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_200_k_5_model_4o_v11-e2cb6199_final_answer_correct
   ✅ precision            → basic_rag_200_k_5_model_4o_v11-e2cb6199_precision
   ✅ recall               → basic_rag_200_k_5_model_4o_v11-e2cb6199_recall
   ✅ f1                   → basic_rag_200_k_5_model_4o_v11-e2cb6199_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  0.007**     0.001**
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  < 0.001***  0.354
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_final_answer_correct
   SELF_RAG: self_rag_200_k_5_model_4o_v13-7e02b577_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 74.5% accuracy
   SELF_RAG: 60.0% accuracy
   Difference: -14.5%
   P-value: 0.000044
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     42        9       51
         Right     38      111      149
--------------------------------------------------
         Total     80      120      200

🔍 INTERPRETATION:
   Both wrong:  42 questions
   SELF_RAG wins:   9 questions (when SEAL RAG fails)
   SEAL RAG wins:  38 questions (when SELF_RAG fails)
   Both right: 111 questions
   Disagreements:  47 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 4.2x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_precision
   SELF_RAG: self_rag_200_k_5_model_4o_v13-7e02b577_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9625 ± 0.1803
   SELF_RAG: 0.6328 ± 0.4604
   Mean difference: +0.3297
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 10.0120
   P-value: 0.000000
   Effect size (Cohen's d): 0.7080
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_recall
   SELF_RAG: self_rag_200_k_5_model_4o_v13-7e02b577_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7725 ± 0.2782
   SELF_RAG: 0.3825 ± 0.3352
   Mean difference: +0.3900
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 14.4905
   P-value: 0.000000
   Effect size (Cohen's d): 1.0246
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_f1
   SELF_RAG: self_rag_200_k_5_model_4o_v13-7e02b577_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8356 ± 0.2237
   SELF_RAG: 0.4479 ± 0.3475
   Mean difference: +0.3877
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 14.7696
   P-value: 0.000000
   Effect size (Cohen's d): 1.0444
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_final_answer_correct
   CRAG_RAG: crag_rag_200_k_5_model_4o_v12-37eb0218_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 74.5% accuracy
   CRAG_RAG: 64.5% accuracy
   Difference: -10.0%
   P-value: 0.007210
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     36       15       51
         Right     35      114      149
--------------------------------------------------
         Total     71      129      200

🔍 INTERPRETATION:
   Both wrong:  36 questions
   CRAG_RAG wins:  15 questions (when SEAL RAG fails)
   SEAL RAG wins:  35 questions (when CRAG_RAG fails)
   Both right: 114 questions
   Disagreements:  50 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.3x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_precision
   CRAG_RAG: crag_rag_200_k_5_model_4o_v12-37eb0218_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9625 ± 0.1803
   CRAG_RAG: 0.2192 ± 0.2555
   Mean difference: +0.7433
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 35.9612
   P-value: 0.000000
   Effect size (Cohen's d): 2.5428
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_recall
   CRAG_RAG: crag_rag_200_k_5_model_4o_v12-37eb0218_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7725 ± 0.2782
   CRAG_RAG: 0.2338 ± 0.2934
   Mean difference: +0.5387
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 19.9975
   P-value: 0.000000
   Effect size (Cohen's d): 1.4140
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_f1
   CRAG_RAG: crag_rag_200_k_5_model_4o_v12-37eb0218_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8356 ± 0.2237
   CRAG_RAG: 0.2219 ± 0.2646
   Mean difference: +0.6136
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 26.5134
   P-value: 0.000000
   Effect size (Cohen's d): 1.8748
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_final_answer_correct
   BASIC_RAG: basic_rag_200_k_5_model_4o_v11-e2cb6199_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 74.5% accuracy
   BASIC_RAG: 63.0% accuracy
   Difference: -11.5%
   P-value: 0.001332
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     39       12       51
         Right     35      114      149
--------------------------------------------------
         Total     74      126      200

🔍 INTERPRETATION:
   Both wrong:  39 questions
   BASIC_RAG wins:  12 questions (when SEAL RAG fails)
   SEAL RAG wins:  35 questions (when BASIC_RAG fails)
   Both right: 114 questions
   Disagreements:  47 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.9x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_precision
   BASIC_RAG: basic_rag_200_k_5_model_4o_v11-e2cb6199_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9625 ± 0.1803
   BASIC_RAG: 0.3430 ± 0.1049
   Mean difference: +0.6195
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 45.0867
   P-value: 0.000000
   Effect size (Cohen's d): 3.1881
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_recall
   BASIC_RAG: basic_rag_200_k_5_model_4o_v11-e2cb6199_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7725 ± 0.2782
   BASIC_RAG: 0.7512 ± 0.2500
   Mean difference: +0.0213
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 0.9285
   P-value: 0.354279
   Effect size (Cohen's d): 0.0657
   Result: 🔴 NOT SIGNIFICANT - No significant difference
   Effect size interpretation: negligible

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_v12-ee7046b6_f1
   BASIC_RAG: basic_rag_200_k_5_model_4o_v11-e2cb6199_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8356 ± 0.2237
   BASIC_RAG: 0.4630 ± 0.1330
   Mean difference: +0.3726
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 23.0071
   P-value: 0.000000
   Effect size (Cohen's d): 1.6268
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name       P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared  4.422516e-05            True          p < 0.001            74.5%                  60.0%                 -14.5%               38                9 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic  2.275384e-19            True          p < 0.001            0.963                  0.633                 +0.330 N/A (Continuous) N/A (Continuous)        0.708      t = 10.012
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic  5.844653e-33            True          p < 0.001            0.772                  0.383                 +0.390 N/A (Continuous) N/A (Continuous)        1.025      t = 14.491
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic  8.099654e-34            True          p < 0.001            0.836                  0.448                 +0.388 N/A (Continuous) N/A (Continuous)        1.044      t = 14.770
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared  7.209571e-03            True           p < 0.01            74.5%                  64.5%                 -10.0%               35               15 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic  5.278320e-89            True          p < 0.001            0.963                  0.219                 +0.743 N/A (Continuous) N/A (Continuous)        2.543      t = 35.961
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic  1.689129e-49            True          p < 0.001            0.772                  0.234                 +0.539 N/A (Continuous) N/A (Continuous)        1.414      t = 19.998
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic  3.164537e-67            True          p < 0.001            0.836                  0.222                 +0.614 N/A (Continuous) N/A (Continuous)        1.875      t = 26.513
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared  1.331837e-03            True           p < 0.01            74.5%                  63.0%                 -11.5%               35               12 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 2.072382e-106            True          p < 0.001            0.963                  0.343                 +0.619 N/A (Continuous) N/A (Continuous)        3.188      t = 45.087
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic  3.542788e-01           False    Not Significant            0.772                  0.751                 +0.021 N/A (Continuous) N/A (Continuous)        0.066       t = 0.928
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic  5.686208e-58            True          p < 0.001            0.836                  0.463                 +0.373 N/A (Continuous) N/A (Continuous)        1.627      t = 23.007
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    4.422516e-05            True          p < 0.001            74.5%
1    2.275384e-19            True          p < 0.001            0.963
2    5.844653e-33            True          p < 0.001            0.772
3    8.099654e-34            True          p < 0.001            0.836
4    7.209571e-03            True           p < 0.01            74.5%
5    5.278320e-89            True          p < 0.001            0.963
6    1.689129e-49            True          p < 0.001            0.772
7    3.164537e-67            True          p < 0.001            0.836
8    1.331837e-03            True           p < 0.01            74.5%
9   2.072382e-106            True          p < 0.001            0.963
10   3.542788e-01           False    Not Significant            0.772
11   5.686208e-58            True          p < 0.001            0.836

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   60.0%                 -14.5%                38
1                   0.633                 +0.330  N/A (Continuous)
2                   0.383                 +0.390  N/A (Continuous)
3                   0.448                 +0.388  N/A (Continuous)
4                   64.5%                 -10.0%                35
5                   0.219                 +0.743  N/A (Continuous)
6                   0.234                 +0.539  N/A (Continuous)
7                   0.222                 +0.614  N/A (Continuous)
8                   63.0%                 -11.5%                35
9                   0.343                 +0.619  N/A (Continuous)
10                  0.751                 +0.021  N/A (Continuous)
11                  0.463                 +0.373  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                  9  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.708      t = 10.012
2   N/A (Continuous)         1.025      t = 14.491
3   N/A (Continuous)         1.044      t = 14.770
4                 15  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         2.543      t = 35.961
6   N/A (Continuous)         1.414      t = 19.998
7   N/A (Continuous)         1.875      t = 26.513
8                 12  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         3.188      t = 45.087
10  N/A (Continuous)         0.066       t = 0.928
11  N/A (Continuous)         1.627      t = 23.007

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    4.422516e-05            True          p < 0.001            74.5%
1    2.275384e-19            True          p < 0.001            0.963
2    5.844653e-33            True          p < 0.001            0.772
3    8.099654e-34            True          p < 0.001            0.836

### Model 4o-mini | k = 1

In [18]:
df = pd.read_csv("src/files/experiment_comparison/2WikiMultihopQA/seal_rag_k_1_model_4o_mini.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,basic_rag_200_k_1_model_4o_mini_v1-51d127d7_outputs,crag_rag_200_k_1_model_4o_mini_v1-71b745a4_outputs,seal_rag_200_k_1_model_4o_mini_v2-7489ec26_outputs,self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_outputs,basic_rag_200_k_1_model_4o_mini_v1-51d127d7_run,crag_rag_200_k_1_model_4o_mini_v1-71b745a4_run,seal_rag_200_k_1_model_4o_mini_v2-7489ec26_run,...,seal_rag_200_k_1_model_4o_mini_v2-7489ec26_recall,self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_recall,basic_rag_200_k_1_model_4o_mini_v1-51d127d7_f1,crag_rag_200_k_1_model_4o_mini_v1-71b745a4_f1,seal_rag_200_k_1_model_4o_mini_v2-7489ec26_f1,self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_f1,basic_rag_200_k_1_model_4o_mini_v1-51d127d7_precision,crag_rag_200_k_1_model_4o_mini_v1-71b745a4_precision,seal_rag_200_k_1_model_4o_mini_v2-7489ec26_precision,self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_precision
0,002de458-f6e2-4ef7-991f-6c31359ec71c,"{""context"": ""{'title': ['Richard Annesley, 3rd...","{""answer"": ""2 September 1770""}","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""Annesley, Richard (1745-1824...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [], ""response"": ""Don't know."",...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.00,0.6667,0.0000,0.6667,0.0000,1.0,0.0,1.0,0.0
1,009279eb-aa2f-4e9a-a388-0570b3d0fad7,"{""context"": ""{'title': ['Caspar Babypants', 'B...","{""answer"": ""Liverpool""}","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Winston Lennon was born...","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [], ""response"": ""Not mentioned...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.00,0.6667,0.0000,0.6667,0.0000,1.0,0.0,1.0,0.0
2,01afabb2-0984-4333-bfff-0b3ad45cc593,"{""context"": ""{'title': ['M. Venkataraju', 'Wor...","{""answer"": ""United States""}","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""You're viewing the Frameline...","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough: World...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.50,0.6667,0.0000,0.6667,0.6667,1.0,0.0,1.0,1.0
3,04491c40-8385-4c7c-9d07-665afd6ef52d,"{""context"": ""{'title': ['James Woolley (clockm...","{""answer"": ""Madame Pasca""}","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""D6. James A. Donohoe (August...","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [], ""response"": ""James A. Dono...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.00,0.00,0.0000,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.0
4,097adb49-d636-4e90-b9cf-ffed265452f6,"{""context"": ""{'title': ['Takayama Tomoteru', '...","{""answer"": ""Galați""}","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.50,0.6667,0.6667,0.6667,0.6667,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,fc20c2aa-4e58-4517-ad1a-a050f0283457,"{""context"": ""{'title': ['Language Management',...","{""answer"": ""yes""}","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland is a German hyperma...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [], ""response"": ""Yes, Germany....","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.00,0.6667,0.0000,0.6667,0.0000,1.0,0.0,1.0,0.0
196,fc9ea4fb-5063-4d64-9bd3-e52efb03ecbe,"{""context"": ""{'title': ['Jayam Manade', 'Bulld...","{""answer"": ""Bulldog Drummond'S Revenge""}","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Jayam Manade (transl. Victor...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.25,0.25,0.4000,0.0000,0.4000,0.4000,1.0,0.0,1.0,1.0
197,fd41bcf3-aeb3-4d4e-80f7-580d7864172a,"{""context"": ""{'title': ['Control engineering',...","{""answer"": ""yes""}","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems is an un...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [], ""response"": ""Yes, Canada.""...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.00,0.00,0.6667,0.0000,1.0000,0.0000,1.0,0.0,1.0,0.0
198,fd8c17b6-5955-4adc-911f-a3d54ab6487e,"{""context"": ""{'title': ['Isipum of Geumgwan Ga...","{""answer"": ""India""}","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung, also called Geodeu...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [], ""response"": ""Korean"", ""ret...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.00,0.6667,0.0000,0.6667,0.0000,1.0,0.0,1.0,0.0
199,fed9201d-05bd-4208-aa29-11b94b32d17f,"{""context"": ""{'title': ['Marcel Brands', 'Eric...","{""answer"": ""Víctor Bó""}","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""| Directed by | Armando Bó |...","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [], ""response"": ""Not known."", ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.50,0.00,0.6667,0.0000,0.6667,0.0000,1.0,0.0,1.0,0.0

In [19]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_outputs',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_outputs',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_outputs',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_outputs',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_run',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_run',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_run',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_run',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_status',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_status',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_status',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_status',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_error',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_error',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_error',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_error',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_latency',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_latency',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_latency',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_latency',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_tokens',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_tokens',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_tokens',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_tokens',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_total_cost',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_total_cost',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_total_cost',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_total_cost',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_final_answer_correct',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_final_answer_correct',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_final_answer_correct',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_final_answer_correct',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_recall',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_recall',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_recall',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_recall',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_f1',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_f1',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_f1',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_f1',
 'basic_rag_200_k_1_model_4o_mini_v1-51d127d7_precision',
 'crag_rag_200_k_1_model_4o_mini_v1-71b745a4_precision',
 'seal_rag_200_k_1_model_4o_mini_v2-7489ec26_precision',
 'self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_precision']

In [20]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_200_k_1_model_4o_mini_v2-7489ec26_final_answer_correct
   ✅ precision            → seal_rag_200_k_1_model_4o_mini_v2-7489ec26_precision
   ✅ recall               → seal_rag_200_k_1_model_4o_mini_v2-7489ec26_recall
   ✅ f1                   → seal_rag_200_k_1_model_4o_mini_v2-7489ec26_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_final_answer_correct
   ✅ precision            → self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_precision
   ✅ recall               → self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_recall
   ✅ f1                   → self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_200_k_1_model_4o_mini_v1-71b745a4_final_answer_correct
   ✅ precision            → crag_rag_200_k_1_model_4o_mini_v1-71b745a4_precision
   ✅ recall               → crag_rag_200_k_1_model_4o_mini_v1-71b745a4_recall
   ✅ f1                   → crag_rag_200_k_1_model_4o_mini_v1-71b745a4_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_200_k_1_model_4o_mini_v1-51d127d7_final_answer_correct
   ✅ precision            → basic_rag_200_k_1_model_4o_mini_v1-51d127d7_precision
   ✅ recall               → basic_rag_200_k_1_model_4o_mini_v1-51d127d7_recall
   ✅ f1                   → basic_rag_200_k_1_model_4o_mini_v1-51d127d7_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  0.319
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_final_answer_correct
   SELF_RAG: self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 61.5% accuracy
   SELF_RAG: 25.5% accuracy
   Difference: -36.0%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     65       12       77
         Right     84       39      123
--------------------------------------------------
         Total    149       51      200

🔍 INTERPRETATION:
   Both wrong:  65 questions
   SELF_RAG wins:  12 questions (when SEAL RAG fails)
   SEAL RAG wins:  84 questions (when SELF_RAG fails)
   Both right:  39 questions
   Disagreements:  96 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 7.0x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_precision
   SELF_RAG: self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9200 ± 0.2720
   SELF_RAG: 0.2700 ± 0.4451
   Mean difference: +0.6500
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 19.2242
   P-value: 0.000000
   Effect size (Cohen's d): 1.3594
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_recall
   SELF_RAG: self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4500 ± 0.1876
   SELF_RAG: 0.1037 ± 0.1829
   Mean difference: +0.3463
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 19.3760
   P-value: 0.000000
   Effect size (Cohen's d): 1.3701
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_f1
   SELF_RAG: self_rag_200_k_1_model_4o_mini_v1-91f7e4ea_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5945 ± 0.2095
   SELF_RAG: 0.1467 ± 0.2515
   Mean difference: +0.4479
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 20.0351
   P-value: 0.000000
   Effect size (Cohen's d): 1.4167
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_final_answer_correct
   CRAG_RAG: crag_rag_200_k_1_model_4o_mini_v1-71b745a4_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 61.5% accuracy
   CRAG_RAG: 30.5% accuracy
   Difference: -31.0%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     61       16       77
         Right     78       45      123
--------------------------------------------------
         Total    139       61      200

🔍 INTERPRETATION:
   Both wrong:  61 questions
   CRAG_RAG wins:  16 questions (when SEAL RAG fails)
   SEAL RAG wins:  78 questions (when CRAG_RAG fails)
   Both right:  45 questions
   Disagreements:  94 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 4.9x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_precision
   CRAG_RAG: crag_rag_200_k_1_model_4o_mini_v1-71b745a4_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9200 ± 0.2720
   CRAG_RAG: 0.1200 ± 0.3258
   Mean difference: +0.8000
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 28.2135
   P-value: 0.000000
   Effect size (Cohen's d): 1.9950
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_recall
   CRAG_RAG: crag_rag_200_k_1_model_4o_mini_v1-71b745a4_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4500 ± 0.1876
   CRAG_RAG: 0.0525 ± 0.1474
   Mean difference: +0.3975
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 24.7408
   P-value: 0.000000
   Effect size (Cohen's d): 1.7494
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_f1
   CRAG_RAG: crag_rag_200_k_1_model_4o_mini_v1-71b745a4_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5945 ± 0.2095
   CRAG_RAG: 0.0720 ± 0.1995
   Mean difference: +0.5225
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 26.9254
   P-value: 0.000000
   Effect size (Cohen's d): 1.9039
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_final_answer_correct
   BASIC_RAG: basic_rag_200_k_1_model_4o_mini_v1-51d127d7_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 61.5% accuracy
   BASIC_RAG: 18.5% accuracy
   Difference: -43.0%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     69        8       77
         Right     94       29      123
--------------------------------------------------
         Total    163       37      200

🔍 INTERPRETATION:
   Both wrong:  69 questions
   BASIC_RAG wins:   8 questions (when SEAL RAG fails)
   SEAL RAG wins:  94 questions (when BASIC_RAG fails)
   Both right:  29 questions
   Disagreements: 102 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 11.8x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_precision
   BASIC_RAG: basic_rag_200_k_1_model_4o_mini_v1-51d127d7_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9200 ± 0.2720
   BASIC_RAG: 0.9250 ± 0.2641
   Mean difference: -0.0050
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -1.0000
   P-value: 0.318525
   Effect size (Cohen's d): -0.0707
   Result: 🔴 NOT SIGNIFICANT - No significant difference
   Effect size interpretation: negligible

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_recall
   BASIC_RAG: basic_rag_200_k_1_model_4o_mini_v1-51d127d7_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4500 ± 0.1876
   BASIC_RAG: 0.4138 ± 0.1537
   Mean difference: +0.0362
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 4.0588
   P-value: 0.000071
   Effect size (Cohen's d): 0.2870
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_1_model_4o_mini_v2-7489ec26_f1
   BASIC_RAG: basic_rag_200_k_1_model_4o_mini_v1-51d127d7_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5945 ± 0.2095
   BASIC_RAG: 0.5647 ± 0.1923
   Mean difference: +0.0299
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 3.8031
   P-value: 0.000190
   Effect size (Cohen's d): 0.2689
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name      P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared 4.279723e-13            True          p < 0.001            61.5%                  25.5%                 -36.0%               84               12 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic 3.013879e-47            True          p < 0.001            0.920                  0.270                 +0.650 N/A (Continuous) N/A (Continuous)        1.359      t = 19.224
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic 1.084055e-47            True          p < 0.001            0.450                  0.104                 +0.346 N/A (Continuous) N/A (Continuous)        1.370      t = 19.376
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic 1.315217e-49            True          p < 0.001            0.595                  0.147                 +0.448 N/A (Continuous) N/A (Continuous)        1.417      t = 20.035
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared 3.140694e-10            True          p < 0.001            61.5%                  30.5%                 -31.0%               78               16 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 1.788006e-71            True          p < 0.001            0.920                  0.120                 +0.800 N/A (Continuous) N/A (Continuous)        1.995      t = 28.213
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 1.244296e-62            True          p < 0.001            0.450                  0.052                 +0.398 N/A (Continuous) N/A (Continuous)        1.749      t = 24.741
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 2.861054e-68            True          p < 0.001            0.595                  0.072                 +0.523 N/A (Continuous) N/A (Continuous)        1.904      t = 26.925
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared 3.887136e-17            True          p < 0.001            61.5%                  18.5%                 -43.0%               94                8 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 3.185249e-01           False    Not Significant            0.920                  0.925                 -0.005 N/A (Continuous) N/A (Continuous)       -0.071      t = -1.000
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 7.084810e-05            True          p < 0.001            0.450                  0.414                 +0.036 N/A (Continuous) N/A (Continuous)        0.287       t = 4.059
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic 1.900476e-04            True          p < 0.001            0.595                  0.565                 +0.030 N/A (Continuous) N/A (Continuous)        0.269       t = 3.803
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   4.279723e-13            True          p < 0.001            61.5%
1   3.013879e-47            True          p < 0.001            0.920
2   1.084055e-47            True          p < 0.001            0.450
3   1.315217e-49            True          p < 0.001            0.595
4   3.140694e-10            True          p < 0.001            61.5%
5   1.788006e-71            True          p < 0.001            0.920
6   1.244296e-62            True          p < 0.001            0.450
7   2.861054e-68            True          p < 0.001            0.595
8   3.887136e-17            True          p < 0.001            61.5%
9   3.185249e-01           False    Not Significant            0.920
10  7.084810e-05            True          p < 0.001            0.450
11  1.900476e-04            True          p < 0.001            0.595

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   25.5%                 -36.0%                84
1                   0.270                 +0.650  N/A (Continuous)
2                   0.104                 +0.346  N/A (Continuous)
3                   0.147                 +0.448  N/A (Continuous)
4                   30.5%                 -31.0%                78
5                   0.120                 +0.800  N/A (Continuous)
6                   0.052                 +0.398  N/A (Continuous)
7                   0.072                 +0.523  N/A (Continuous)
8                   18.5%                 -43.0%                94
9                   0.925                 -0.005  N/A (Continuous)
10                  0.414                 +0.036  N/A (Continuous)
11                  0.565                 +0.030  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 12  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         1.359      t = 19.224
2   N/A (Continuous)         1.370      t = 19.376
3   N/A (Continuous)         1.417      t = 20.035
4                 16  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         1.995      t = 28.213
6   N/A (Continuous)         1.749      t = 24.741
7   N/A (Continuous)         1.904      t = 26.925
8                  8  N/A (Binary)        χ² = N/A
9   N/A (Continuous)        -0.071      t = -1.000
10  N/A (Continuous)         0.287       t = 4.059
11  N/A (Continuous)         0.269       t = 3.803

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   4.279723e-13            True          p < 0.001            61.5%
1   3.013879e-47            True          p < 0.001            0.920

### Model 4o-mini | k = 3

In [21]:
df = pd.read_csv("src/files/experiment_comparison/2WikiMultihopQA/seal_rag_k_3_model_4o_mini.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,basic_rag_200_k_3_model_4o_mini_v2-047bf519_outputs,crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_outputs,seal_rag_200_k_3_model_4o_mini_v2-5526b439_outputs,self_rag_200_k_3_model_4o_mini_v3-66fa37d3_outputs,basic_rag_200_k_3_model_4o_mini_v2-047bf519_run,crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_run,seal_rag_200_k_3_model_4o_mini_v2-5526b439_run,...,seal_rag_200_k_3_model_4o_mini_v2-5526b439_final_answer_correct,self_rag_200_k_3_model_4o_mini_v3-66fa37d3_final_answer_correct,basic_rag_200_k_3_model_4o_mini_v2-047bf519_precision,crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_precision,seal_rag_200_k_3_model_4o_mini_v2-5526b439_precision,self_rag_200_k_3_model_4o_mini_v3-66fa37d3_precision,basic_rag_200_k_3_model_4o_mini_v2-047bf519_f1,crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_f1,seal_rag_200_k_3_model_4o_mini_v2-5526b439_f1,self_rag_200_k_3_model_4o_mini_v3-66fa37d3_f1
0,002de458-f6e2-4ef7-991f-6c31359ec71c,"{""context"": ""{'title': ['Richard Annesley, 3rd...","{""answer"": ""2 September 1770""}","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""Annesley, Richard (1745-1824...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [], ""response"": ""Don't know."",...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,0.0,0.3333,0.0,1.0,0.0,0.4000,0.0,0.6667,0.0000
1,009279eb-aa2f-4e9a-a388-0570b3d0fad7,"{""context"": ""{'title': ['Caspar Babypants', 'B...","{""answer"": ""Liverpool""}","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Lennon: John Winston On...","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Lennon: John Winston On...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,0.6667,0.5,1.0,1.0,0.8000,0.5,0.6667,0.6667
2,01afabb2-0984-4333-bfff-0b3ad45cc593,"{""context"": ""{'title': ['M. Venkataraju', 'Wor...","{""answer"": ""United States""}","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough is a 1...","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""Ian Barry (director): Ian Ba...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,0.0,0.3333,0.0,1.0,0.0,0.4000,0.0,0.6667,0.0000
3,04491c40-8385-4c7c-9d07-665afd6ef52d,"{""context"": ""{'title': ['James Woolley (clockm...","{""answer"": ""Madame Pasca""}","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""D6. James A. Donohoe (August...","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [], ""response"": ""Madame Pasca""...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,0.6667,0.0,0.0,0.0,0.8000,0.0,0.0000,0.0000
4,097adb49-d636-4e90-b9cf-ffed265452f6,"{""context"": ""{'title': ['Takayama Tomoteru', '...","{""answer"": ""Galați""}","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ștefan I. Nenițescu: Ștefan ...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,1.0,0.6667,0.5,1.0,1.0,0.8000,0.5,0.6667,0.6667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,fc20c2aa-4e58-4517-ad1a-a050f0283457,"{""context"": ""{'title': ['Language Management',...","{""answer"": ""yes""}","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland is a German hyperma...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [], ""response"": ""Yes, both are...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,1.0,0.6667,0.0,1.0,0.0,0.8000,0.0,0.6667,0.0000
196,fc9ea4fb-5063-4d64-9bd3-e52efb03ecbe,"{""context"": ""{'title': ['Jayam Manade', 'Bulld...","{""answer"": ""Bulldog Drummond'S Revenge""}","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Jayam Manade (transl. Victor...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [], ""response"": ""\""Bulldog Dru...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,1.0,0.6667,0.0,1.0,0.0,0.5714,0.0,0.4000,0.0000
197,fd41bcf3-aeb3-4d4e-80f7-580d7864172a,"{""context"": ""{'title': ['Control engineering',...","{""answer"": ""yes""}","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems is an un...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""Telus: Telus Communications(...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,1.0,0.6667,0.0,1.0,1.0,0.8000,0.0,0.6667,0.6667
198,fd8c17b6-5955-4adc-911f-a3d54ab6487e,"{""context"": ""{'title': ['Isipum of Geumgwan Ga...","{""answer"": ""India""}","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""2. century\n\n1 reference\n\...","{""docs_to_use"": [""Mapum of Geumgwan Gaya: Mapu...","{""docs_to_use"": [""Queen Mojong: Queen Mojong w...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,0.0,0.3333,0.0,0.0,0.0,0.4000,0.0,0.0000,0.0000
199,fed9201d-05bd-4208-aa29-11b94b32d17f,"{""context"": ""{'title': ['Marcel Brands', 'Eric...","{""answer"": ""Víctor Bó""}","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""| Directed by | Armando Bó |...","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [], ""response"": ""Not available...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,0.0,0.3333,0.0,1.0,0.0,0.4000,0.0,0.6667,0.0000

In [22]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_outputs',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_outputs',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_outputs',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_outputs',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_run',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_run',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_run',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_run',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_status',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_status',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_status',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_status',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_error',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_error',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_error',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_error',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_latency',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_latency',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_latency',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_latency',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_tokens',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_tokens',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_tokens',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_tokens',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_total_cost',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_total_cost',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_total_cost',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_total_cost',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_recall',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_recall',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_recall',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_recall',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_final_answer_correct',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_final_answer_correct',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_final_answer_correct',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_final_answer_correct',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_precision',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_precision',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_precision',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_precision',
 'basic_rag_200_k_3_model_4o_mini_v2-047bf519_f1',
 'crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_f1',
 'seal_rag_200_k_3_model_4o_mini_v2-5526b439_f1',
 'self_rag_200_k_3_model_4o_mini_v3-66fa37d3_f1']

In [23]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_200_k_3_model_4o_mini_v2-5526b439_final_answer_correct
   ✅ precision            → seal_rag_200_k_3_model_4o_mini_v2-5526b439_precision
   ✅ recall               → seal_rag_200_k_3_model_4o_mini_v2-5526b439_recall
   ✅ f1                   → seal_rag_200_k_3_model_4o_mini_v2-5526b439_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_200_k_3_model_4o_mini_v3-66fa37d3_final_answer_correct
   ✅ precision            → self_rag_200_k_3_model_4o_mini_v3-66fa37d3_precision
   ✅ recall               → self_rag_200_k_3_model_4o_mini_v3-66fa37d3_recall
   ✅ f1                   → self_rag_200_k_3_model_4o_mini_v3-66fa37d3_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_final_answer_correct
   ✅ precision            → crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_precision
   ✅ recall               → crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_recall
   ✅ f1                   → crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_200_k_3_model_4o_mini_v2-047bf519_final_answer_correct
   ✅ precision            → basic_rag_200_k_3_model_4o_mini_v2-047bf519_precision
   ✅ recall               → basic_rag_200_k_3_model_4o_mini_v2-047bf519_recall
   ✅ f1                   → basic_rag_200_k_3_model_4o_mini_v2-047bf519_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      0.005**     0.073       < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  0.548
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_final_answer_correct
   SELF_RAG: self_rag_200_k_3_model_4o_mini_v3-66fa37d3_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 64.0% accuracy
   SELF_RAG: 51.5% accuracy
   Difference: -12.5%
   P-value: 0.004970
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     48       24       72
         Right     49       79      128
--------------------------------------------------
         Total     97      103      200

🔍 INTERPRETATION:
   Both wrong:  48 questions
   SELF_RAG wins:  24 questions (when SEAL RAG fails)
   SEAL RAG wins:  49 questions (when SELF_RAG fails)
   Both right:  79 questions
   Disagreements:  73 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.0x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_precision
   SELF_RAG: self_rag_200_k_3_model_4o_mini_v3-66fa37d3_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9100 ± 0.2825
   SELF_RAG: 0.4067 ± 0.4876
   Mean difference: +0.5033
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 13.7216
   P-value: 0.000000
   Effect size (Cohen's d): 0.9703
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_recall
   SELF_RAG: self_rag_200_k_3_model_4o_mini_v3-66fa37d3_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4575 ± 0.1943
   SELF_RAG: 0.1850 ± 0.2459
   Mean difference: +0.2725
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 13.2245
   P-value: 0.000000
   Effect size (Cohen's d): 0.9351
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_f1
   SELF_RAG: self_rag_200_k_3_model_4o_mini_v3-66fa37d3_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5993 ± 0.2169
   SELF_RAG: 0.2455 ± 0.3073
   Mean difference: +0.3538
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 14.2223
   P-value: 0.000000
   Effect size (Cohen's d): 1.0057
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_final_answer_correct
   CRAG_RAG: crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 64.0% accuracy
   CRAG_RAG: 56.0% accuracy
   Difference: -8.0%
   P-value: 0.072998
   Significant: 🔴 NO

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     45       27       72
         Right     43       85      128
--------------------------------------------------
         Total     88      112      200

🔍 INTERPRETATION:
   Both wrong:  45 questions
   CRAG_RAG wins:  27 questions (when SEAL RAG fails)
   SEAL RAG wins:  43 questions (when CRAG_RAG fails)
   Both right:  85 questions
   Disagreements:  70 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 1.6x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_precision
   CRAG_RAG: crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9100 ± 0.2825
   CRAG_RAG: 0.0892 ± 0.1919
   Mean difference: +0.8208
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 34.6541
   P-value: 0.000000
   Effect size (Cohen's d): 2.4504
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_recall
   CRAG_RAG: crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4575 ± 0.1943
   CRAG_RAG: 0.0850 ± 0.1849
   Mean difference: +0.3725
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 20.3208
   P-value: 0.000000
   Effect size (Cohen's d): 1.4369
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_f1
   CRAG_RAG: crag_rag_200_k_3_model_4o_mini_v3-6de19cf9_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5993 ± 0.2169
   CRAG_RAG: 0.0860 ± 0.1857
   Mean difference: +0.5133
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 26.3496
   P-value: 0.000000
   Effect size (Cohen's d): 1.8632
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_final_answer_correct
   BASIC_RAG: basic_rag_200_k_3_model_4o_mini_v2-047bf519_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 64.0% accuracy
   BASIC_RAG: 50.0% accuracy
   Difference: -14.0%
   P-value: 0.000889
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     53       19       72
         Right     47       81      128
--------------------------------------------------
         Total    100      100      200

🔍 INTERPRETATION:
   Both wrong:  53 questions
   BASIC_RAG wins:  19 questions (when SEAL RAG fails)
   SEAL RAG wins:  47 questions (when BASIC_RAG fails)
   Both right:  81 questions
   Disagreements:  66 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.5x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_precision
   BASIC_RAG: basic_rag_200_k_3_model_4o_mini_v2-047bf519_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9100 ± 0.2825
   BASIC_RAG: 0.5267 ± 0.1716
   Mean difference: +0.3833
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 17.1951
   P-value: 0.000000
   Effect size (Cohen's d): 1.2159
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_recall
   BASIC_RAG: basic_rag_200_k_3_model_4o_mini_v2-047bf519_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4575 ± 0.1943
   BASIC_RAG: 0.6937 ± 0.2524
   Mean difference: -0.2362
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -11.6385
   P-value: 0.000000
   Effect size (Cohen's d): -0.8230
   Result: 🟢 SIGNIFICANT - BASIC_RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_3_model_4o_mini_v2-5526b439_f1
   BASIC_RAG: basic_rag_200_k_3_model_4o_mini_v2-047bf519_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5993 ± 0.2169
   BASIC_RAG: 0.5880 ± 0.1879
   Mean difference: +0.0113
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 0.6016
   P-value: 0.548144
   Effect size (Cohen's d): 0.0425
   Result: 🔴 NOT SIGNIFICANT - No significant difference
   Effect size interpretation: negligible


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name      P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared 4.969757e-03            True           p < 0.01            64.0%                  51.5%                 -12.5%               49               24 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic 1.360080e-30            True          p < 0.001            0.910                  0.407                 +0.503 N/A (Continuous) N/A (Continuous)        0.970      t = 13.722
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic 4.597936e-29            True          p < 0.001            0.458                  0.185                 +0.273 N/A (Continuous) N/A (Continuous)        0.935      t = 13.225
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic 3.909674e-32            True          p < 0.001            0.599                  0.246                 +0.354 N/A (Continuous) N/A (Continuous)        1.006      t = 14.222
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared 7.299805e-02           False    Not Significant            64.0%                  56.0%                  -8.0%               43               27 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 3.047210e-86            True          p < 0.001            0.910                  0.089                 +0.821 N/A (Continuous) N/A (Continuous)        2.450      t = 34.654
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 1.972422e-50            True          p < 0.001            0.458                  0.085                 +0.372 N/A (Continuous) N/A (Continuous)        1.437      t = 20.321
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 8.274250e-67            True          p < 0.001            0.599                  0.086                 +0.513 N/A (Continuous) N/A (Continuous)        1.863      t = 26.350
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared 8.890490e-04            True          p < 0.001            64.0%                  50.0%                 -14.0%               47               19 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 3.263102e-41            True          p < 0.001            0.910                  0.527                 +0.383 N/A (Continuous) N/A (Continuous)        1.216      t = 17.195
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 3.232657e-24            True          p < 0.001            0.458                  0.694                 -0.236 N/A (Continuous) N/A (Continuous)       -0.823     t = -11.638
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic 5.481442e-01           False    Not Significant            0.599                  0.588                 +0.011 N/A (Continuous) N/A (Continuous)        0.043       t = 0.602
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   4.969757e-03            True           p < 0.01            64.0%
1   1.360080e-30            True          p < 0.001            0.910
2   4.597936e-29            True          p < 0.001            0.458
3   3.909674e-32            True          p < 0.001            0.599
4   7.299805e-02           False    Not Significant            64.0%
5   3.047210e-86            True          p < 0.001            0.910
6   1.972422e-50            True          p < 0.001            0.458
7   8.274250e-67            True          p < 0.001            0.599
8   8.890490e-04            True          p < 0.001            64.0%
9   3.263102e-41            True          p < 0.001            0.910
10  3.232657e-24            True          p < 0.001            0.458
11  5.481442e-01           False    Not Significant            0.599

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   51.5%                 -12.5%                49
1                   0.407                 +0.503  N/A (Continuous)
2                   0.185                 +0.273  N/A (Continuous)
3                   0.246                 +0.354  N/A (Continuous)
4                   56.0%                  -8.0%                43
5                   0.089                 +0.821  N/A (Continuous)
6                   0.085                 +0.372  N/A (Continuous)
7                   0.086                 +0.513  N/A (Continuous)
8                   50.0%                 -14.0%                47
9                   0.527                 +0.383  N/A (Continuous)
10                  0.694                 -0.236  N/A (Continuous)
11                  0.588                 +0.011  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 24  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.970      t = 13.722
2   N/A (Continuous)         0.935      t = 13.225
3   N/A (Continuous)         1.006      t = 14.222
4                 27  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         2.450      t = 34.654
6   N/A (Continuous)         1.437      t = 20.321
7   N/A (Continuous)         1.863      t = 26.350
8                 19  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         1.216      t = 17.195
10  N/A (Continuous)        -0.823     t = -11.638
11  N/A (Continuous)         0.043       t = 0.602

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   4.969757e-03            True           p < 0.01            64.0%
1   1.360080e-30            True          p < 0.001            0.910
2   4.597936e-29            True          p < 0.001            0.458

### Model 4o-mini | k = 5

In [24]:
df = pd.read_csv("src/files/experiment_comparison/2WikiMultihopQA/seal_rag_k_5_model_4o_mini.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,basic_rag_200_k_5_model_4o_mini_v3-04652ca8_outputs,crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_outputs,seal_rag_200_k_5_model_4o_mini_v2-8080c870_outputs,self_rag_200_k_5_model_4o_mini_v3-44e5efc9_outputs,basic_rag_200_k_5_model_4o_mini_v3-04652ca8_run,crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_run,seal_rag_200_k_5_model_4o_mini_v2-8080c870_run,...,seal_rag_200_k_5_model_4o_mini_v2-8080c870_final_answer_correct,self_rag_200_k_5_model_4o_mini_v3-44e5efc9_final_answer_correct,basic_rag_200_k_5_model_4o_mini_v3-04652ca8_recall,crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_recall,seal_rag_200_k_5_model_4o_mini_v2-8080c870_recall,self_rag_200_k_5_model_4o_mini_v3-44e5efc9_recall,basic_rag_200_k_5_model_4o_mini_v3-04652ca8_precision,crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_precision,seal_rag_200_k_5_model_4o_mini_v2-8080c870_precision,self_rag_200_k_5_model_4o_mini_v3-44e5efc9_precision
0,002de458-f6e2-4ef7-991f-6c31359ec71c,"{""context"": ""{'title': ['Richard Annesley, 3rd...","{""answer"": ""2 September 1770""}","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""Annesley, Richard (1745-1824...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [], ""response"": ""Don't know."",...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,0.0,0.5,0.0,0.50,0.00,0.2,0.0,1.0,0.0
1,009279eb-aa2f-4e9a-a388-0570b3d0fad7,"{""context"": ""{'title': ['Caspar Babypants', 'B...","{""answer"": ""Liverpool""}","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Lennon: John Winston On...","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Lennon: John Winston On...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,1.0,0.5,0.50,0.50,0.4,0.5,1.0,1.0
2,01afabb2-0984-4333-bfff-0b3ad45cc593,"{""context"": ""{'title': ['M. Venkataraju', 'Wor...","{""answer"": ""United States""}","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough is a 1...","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough: World...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,1.0,0.5,0.0,0.50,0.50,0.2,0.0,1.0,0.5
3,04491c40-8385-4c7c-9d07-665afd6ef52d,"{""context"": ""{'title': ['James Woolley (clockm...","{""answer"": ""Madame Pasca""}","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""D6. James A. Donohoe (August...","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [], ""response"": ""Madame Pasca""...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,1.0,0.0,0.00,0.00,0.4,0.0,0.0,0.0
4,097adb49-d636-4e90-b9cf-ffed265452f6,"{""context"": ""{'title': ['Takayama Tomoteru', '...","{""answer"": ""Galați""}","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ștefan I. Nenițescu: Ștefan ...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,1.0,1.0,0.5,0.50,0.50,0.4,0.5,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,fc20c2aa-4e58-4517-ad1a-a050f0283457,"{""context"": ""{'title': ['Language Management',...","{""answer"": ""yes""}","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland is a German hyperma...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [], ""response"": ""No, different...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,0.0,1.0,0.0,0.50,0.00,0.4,0.0,1.0,0.0
196,fc9ea4fb-5063-4d64-9bd3-e52efb03ecbe,"{""context"": ""{'title': ['Jayam Manade', 'Bulld...","{""answer"": ""Bulldog Drummond'S Revenge""}","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Jayam Manade (transl. Victor...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,1.0,0.5,0.0,0.25,0.25,0.4,0.0,1.0,1.0
197,fd41bcf3-aeb3-4d4e-80f7-580d7864172a,"{""context"": ""{'title': ['Control engineering',...","{""answer"": ""yes""}","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems is an un...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""Telus: Telus Communications(...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,1.0,1.0,0.0,0.50,0.50,0.4,0.0,1.0,1.0
198,fd8c17b6-5955-4adc-911f-a3d54ab6487e,"{""context"": ""{'title': ['Isipum of Geumgwan Ga...","{""answer"": ""India""}","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Queen Mojong: Queen Mojong w...","{""docs_to_use"": [""Mapum of Geumgwan Gaya: Mapu...","{""docs_to_use"": [""Queen Mojong: Queen Mojong w...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,0.0,0.0,1.0,0.0,0.00,0.00,0.4,0.0,0.0,0.0
199,fed9201d-05bd-4208-aa29-11b94b32d17f,"{""context"": ""{'title': ['Marcel Brands', 'Eric...","{""answer"": ""Víctor Bó""}","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""| Directed by | Armando Bó |...","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [], ""response"": ""Not mentioned...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",...,1.0,0.0,0.5,0.0,0.50,0.00,0.2,0.0,1.0,0.0

In [25]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_outputs',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_outputs',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_outputs',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_outputs',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_run',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_run',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_run',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_run',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_status',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_status',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_status',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_status',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_error',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_error',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_error',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_error',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_latency',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_latency',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_latency',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_latency',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_tokens',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_tokens',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_tokens',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_tokens',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_total_cost',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_total_cost',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_total_cost',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_total_cost',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_f1',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_f1',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_f1',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_f1',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_final_answer_correct',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_final_answer_correct',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_final_answer_correct',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_final_answer_correct',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_recall',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_recall',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_recall',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_recall',
 'basic_rag_200_k_5_model_4o_mini_v3-04652ca8_precision',
 'crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_precision',
 'seal_rag_200_k_5_model_4o_mini_v2-8080c870_precision',
 'self_rag_200_k_5_model_4o_mini_v3-44e5efc9_precision']

In [26]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_200_k_5_model_4o_mini_v2-8080c870_final_answer_correct
   ✅ precision            → seal_rag_200_k_5_model_4o_mini_v2-8080c870_precision
   ✅ recall               → seal_rag_200_k_5_model_4o_mini_v2-8080c870_recall
   ✅ f1                   → seal_rag_200_k_5_model_4o_mini_v2-8080c870_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_200_k_5_model_4o_mini_v3-44e5efc9_final_answer_correct
   ✅ precision            → self_rag_200_k_5_model_4o_mini_v3-44e5efc9_precision
   ✅ recall               → self_rag_200_k_5_model_4o_mini_v3-44e5efc9_recall
   ✅ f1                   → self_rag_200_k_5_model_4o_mini_v3-44e5efc9_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_final_answer_correct
   ✅ precision            → crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_precision
   ✅ recall               → crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_recall
   ✅ f1                   → crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_200_k_5_model_4o_mini_v3-04652ca8_final_answer_correct
   ✅ precision            → basic_rag_200_k_5_model_4o_mini_v3-04652ca8_precision
   ✅ recall               → basic_rag_200_k_5_model_4o_mini_v3-04652ca8_recall
   ✅ f1                   → basic_rag_200_k_5_model_4o_mini_v3-04652ca8_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      0.005**     0.009**     0.023*
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_final_answer_correct
   SELF_RAG: self_rag_200_k_5_model_4o_mini_v3-44e5efc9_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 66.5% accuracy
   SELF_RAG: 54.5% accuracy
   Difference: -12.0%
   P-value: 0.005285
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     45       22       67
         Right     46       87      133
--------------------------------------------------
         Total     91      109      200

🔍 INTERPRETATION:
   Both wrong:  45 questions
   SELF_RAG wins:  22 questions (when SEAL RAG fails)
   SEAL RAG wins:  46 questions (when SELF_RAG fails)
   Both right:  87 questions
   Disagreements:  68 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.1x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_precision
   SELF_RAG: self_rag_200_k_5_model_4o_mini_v3-44e5efc9_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9058 ± 0.2843
   SELF_RAG: 0.4495 ± 0.4937
   Mean difference: +0.4563
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 12.2397
   P-value: 0.000000
   Effect size (Cohen's d): 0.8655
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_recall
   SELF_RAG: self_rag_200_k_5_model_4o_mini_v3-44e5efc9_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4512 ± 0.1870
   SELF_RAG: 0.1988 ± 0.2447
   Mean difference: +0.2525
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 12.5450
   P-value: 0.000000
   Effect size (Cohen's d): 0.8871
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_f1
   SELF_RAG: self_rag_200_k_5_model_4o_mini_v3-44e5efc9_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5935 ± 0.2128
   SELF_RAG: 0.2647 ± 0.3045
   Mean difference: +0.3288
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 13.2779
   P-value: 0.000000
   Effect size (Cohen's d): 0.9389
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_final_answer_correct
   CRAG_RAG: crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 66.5% accuracy
   CRAG_RAG: 55.0% accuracy
   Difference: -11.5%
   P-value: 0.009030
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     43       24       67
         Right     47       86      133
--------------------------------------------------
         Total     90      110      200

🔍 INTERPRETATION:
   Both wrong:  43 questions
   CRAG_RAG wins:  24 questions (when SEAL RAG fails)
   SEAL RAG wins:  47 questions (when CRAG_RAG fails)
   Both right:  86 questions
   Disagreements:  71 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.0x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_precision
   CRAG_RAG: crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9058 ± 0.2843
   CRAG_RAG: 0.1092 ± 0.2077
   Mean difference: +0.7967
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 33.4585
   P-value: 0.000000
   Effect size (Cohen's d): 2.3659
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_recall
   CRAG_RAG: crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4512 ± 0.1870
   CRAG_RAG: 0.1050 ± 0.2057
   Mean difference: +0.3463
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 19.0963
   P-value: 0.000000
   Effect size (Cohen's d): 1.3503
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_f1
   CRAG_RAG: crag_rag_200_k_5_model_4o_mini_v3-e8fe9982_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5935 ± 0.2128
   CRAG_RAG: 0.1054 ± 0.2023
   Mean difference: +0.4881
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 25.3633
   P-value: 0.000000
   Effect size (Cohen's d): 1.7935
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_final_answer_correct
   BASIC_RAG: basic_rag_200_k_5_model_4o_mini_v3-04652ca8_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 66.5% accuracy
   BASIC_RAG: 57.0% accuracy
   Difference: -9.5%
   P-value: 0.023342
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong     45       22       67
         Right     41       92      133
--------------------------------------------------
         Total     86      114      200

🔍 INTERPRETATION:
   Both wrong:  45 questions
   BASIC_RAG wins:  22 questions (when SEAL RAG fails)
   SEAL RAG wins:  41 questions (when BASIC_RAG fails)
   Both right:  92 questions
   Disagreements:  63 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 1.9x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_precision
   BASIC_RAG: basic_rag_200_k_5_model_4o_mini_v3-04652ca8_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9058 ± 0.2843
   BASIC_RAG: 0.3430 ± 0.1049
   Mean difference: +0.5628
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 27.2132
   P-value: 0.000000
   Effect size (Cohen's d): 1.9243
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_recall
   BASIC_RAG: basic_rag_200_k_5_model_4o_mini_v3-04652ca8_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4512 ± 0.1870
   BASIC_RAG: 0.7512 ± 0.2500
   Mean difference: -0.3000
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -15.1409
   P-value: 0.000000
   Effect size (Cohen's d): -1.0706
   Result: 🟢 SIGNIFICANT - BASIC_RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_200_k_5_model_4o_mini_v2-8080c870_f1
   BASIC_RAG: basic_rag_200_k_5_model_4o_mini_v3-04652ca8_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5935 ± 0.2128
   BASIC_RAG: 0.4630 ± 0.1330
   Mean difference: +0.1305
   Sample size: 200 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 7.7535
   P-value: 0.000000
   Effect size (Cohen's d): 0.5483
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name      P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared 5.284500e-03            True           p < 0.01            66.5%                  54.5%                 -12.0%               46               22 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic 4.796325e-26            True          p < 0.001            0.906                  0.450                 +0.456 N/A (Continuous) N/A (Continuous)        0.865      t = 12.240
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic 5.593658e-27            True          p < 0.001            0.451                  0.199                 +0.253 N/A (Continuous) N/A (Continuous)        0.887      t = 12.545
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic 3.151520e-29            True          p < 0.001            0.593                  0.265                 +0.329 N/A (Continuous) N/A (Continuous)        0.939      t = 13.278
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared 9.029911e-03            True           p < 0.01            66.5%                  55.0%                 -11.5%               47               24 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 1.191017e-83            True          p < 0.001            0.906                  0.109                 +0.797 N/A (Continuous) N/A (Continuous)        2.366      t = 33.459
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 7.150054e-47            True          p < 0.001            0.451                  0.105                 +0.346 N/A (Continuous) N/A (Continuous)        1.350      t = 19.096
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 2.896748e-64            True          p < 0.001            0.593                  0.105                 +0.488 N/A (Continuous) N/A (Continuous)        1.793      t = 25.363
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared 2.334220e-02            True           p < 0.05            66.5%                  57.0%                  -9.5%               41               22 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 5.406892e-69            True          p < 0.001            0.906                  0.343                 +0.563 N/A (Continuous) N/A (Continuous)        1.924      t = 27.213
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 5.861399e-35            True          p < 0.001            0.451                  0.751                 -0.300 N/A (Continuous) N/A (Continuous)       -1.071     t = -15.141
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic 4.523034e-13            True          p < 0.001            0.593                  0.463                 +0.130 N/A (Continuous) N/A (Continuous)        0.548       t = 7.753
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   5.284500e-03            True           p < 0.01            66.5%
1   4.796325e-26            True          p < 0.001            0.906
2   5.593658e-27            True          p < 0.001            0.451
3   3.151520e-29            True          p < 0.001            0.593
4   9.029911e-03            True           p < 0.01            66.5%
5   1.191017e-83            True          p < 0.001            0.906
6   7.150054e-47            True          p < 0.001            0.451
7   2.896748e-64            True          p < 0.001            0.593
8   2.334220e-02            True           p < 0.05            66.5%
9   5.406892e-69            True          p < 0.001            0.906
10  5.861399e-35            True          p < 0.001            0.451
11  4.523034e-13            True          p < 0.001            0.593

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   54.5%                 -12.0%                46
1                   0.450                 +0.456  N/A (Continuous)
2                   0.199                 +0.253  N/A (Continuous)
3                   0.265                 +0.329  N/A (Continuous)
4                   55.0%                 -11.5%                47
5                   0.109                 +0.797  N/A (Continuous)
6                   0.105                 +0.346  N/A (Continuous)
7                   0.105                 +0.488  N/A (Continuous)
8                   57.0%                  -9.5%                41
9                   0.343                 +0.563  N/A (Continuous)
10                  0.751                 -0.300  N/A (Continuous)
11                  0.463                 +0.130  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 22  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.865      t = 12.240
2   N/A (Continuous)         0.887      t = 12.545
3   N/A (Continuous)         0.939      t = 13.278
4                 24  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         2.366      t = 33.459
6   N/A (Continuous)         1.350      t = 19.096
7   N/A (Continuous)         1.793      t = 25.363
8                 22  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         1.924      t = 27.213
10  N/A (Continuous)        -1.071     t = -15.141
11  N/A (Continuous)         0.548       t = 7.753

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   5.284500e-03            True           p < 0.01            66.5%

### Model 4o | seal-rag k = 5 | adaptive k

In [28]:
df = pd.read_csv("src/files/experiment_comparison/2WikiMultihopQA/adaptive_k_vs_seal_rag/seal_rag_4o.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_outputs,adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_outputs,seal_rag_200_k_5_model_4o_v12-ee7046b6_outputs,adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_run,adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_run,seal_rag_200_k_5_model_4o_v12-ee7046b6_run,adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_status,...,seal_rag_200_k_5_model_4o_v12-ee7046b6_final_answer_correct,adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_f1,adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_f1,seal_rag_200_k_5_model_4o_v12-ee7046b6_f1,adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_recall,adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_recall,seal_rag_200_k_5_model_4o_v12-ee7046b6_recall,adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_precision,adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_precision,seal_rag_200_k_5_model_4o_v12-ee7046b6_precision
0,002de458-f6e2-4ef7-991f-6c31359ec71c,"{""context"": ""{'title': ['Richard Annesley, 3rd...","{""answer"": ""2 September 1770""}","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.0,0.3636,0.3333,0.6667,1.0,0.5,0.50,0.2222,0.2500,1.0
1,009279eb-aa2f-4e9a-a388-0570b3d0fad7,"{""context"": ""{'title': ['Caspar Babypants', 'B...","{""answer"": ""Liverpool""}","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""John Lennon: John Winston On...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,1.0,0.4444,1.0000,0.6667,1.0,1.0,0.50,0.2857,1.0000,1.0
2,01afabb2-0984-4333-bfff-0b3ad45cc593,"{""context"": ""{'title': ['M. Venkataraju', 'Wor...","{""answer"": ""United States""}","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough: World...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.0,0.2500,0.6667,0.6667,0.5,0.5,0.50,0.1667,1.0000,1.0
3,04491c40-8385-4c7c-9d07-665afd6ef52d,"{""context"": ""{'title': ['James Woolley (clockm...","{""answer"": ""Madame Pasca""}","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""James A. Donohoe: James A. D...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,1.0,0.4000,0.8000,1.0000,1.0,1.0,1.00,0.2500,0.6667,1.0
4,097adb49-d636-4e90-b9cf-ffed265452f6,"{""context"": ""{'title': ['Takayama Tomoteru', '...","{""answer"": ""Galați""}","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,1.0,0.4444,1.0000,0.6667,1.0,1.0,0.50,0.2857,1.0000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,fc20c2aa-4e58-4517-ad1a-a050f0283457,"{""context"": ""{'title': ['Language Management',...","{""answer"": ""yes""}","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,1.0,0.5000,0.6667,1.0000,1.0,0.5,1.00,0.3333,1.0000,1.0
196,fc9ea4fb-5063-4d64-9bd3-e52efb03ecbe,"{""context"": ""{'title': ['Jayam Manade', 'Bulld...","{""answer"": ""Bulldog Drummond'S Revenge""}","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Bulldog Drummond's Revenge: ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,1.0,0.2353,0.3333,0.8571,0.5,0.5,0.75,0.1538,0.2500,1.0
197,fd41bcf3-aeb3-4d4e-80f7-580d7864172a,"{""context"": ""{'title': ['Control engineering',...","{""answer"": ""yes""}","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,1.0,0.4444,1.0000,1.0000,1.0,1.0,1.00,0.2857,1.0000,1.0
198,fd8c17b6-5955-4adc-911f-a3d54ab6487e,"{""context"": ""{'title': ['Isipum of Geumgwan Ga...","{""answer"": ""India""}","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,1.0,0.2353,0.3333,1.0000,1.0,1.0,1.00,0.1333,0.2000,1.0
199,fed9201d-05bd-4208-aa29-11b94b32d17f,"{""context"": ""{'title': ['Marcel Brands', 'Eric...","{""answer"": ""Víctor Bó""}","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""La Leona (film): La Leona is...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,1.0,0.2500,0.6667,1.0000,0.5,0.5,1.00,0.1667,1.0000,1.0

In [29]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_outputs',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_outputs',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_outputs',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_run',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_run',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_run',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_status',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_status',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_status',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_error',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_error',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_error',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_latency',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_latency',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_latency',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_tokens',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_tokens',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_tokens',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_total_cost',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_total_cost',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_total_cost',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_final_answer_correct',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_final_answer_correct',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_final_answer_correct',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_f1',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_f1',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_f1',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_recall',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_recall',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_recall',
 'adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2_precision',
 'adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a_precision',
 'seal_rag_200_k_5_model_4o_v12-ee7046b6_precision']

In [32]:
import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.contingency_tables import mcnemar

# --- METRIC COMPARISON FUNCTIONS (REUSED) ---

def compare_binary_metrics(method1_results, method2_results, method1_name, method2_name):
    """Compare binary metrics using McNemar's test"""
    # Convert to integers (True=1, False=0)
    a1 = [int(x) for x in method1_results]
    a2 = [int(x) for x in method2_results]
    
    acc1 = sum(a1) / len(a1)
    acc2 = sum(a2) / len(a2)
    
    # Create contingency table
    contingency_table = pd.crosstab(
        pd.Series(a1, name=method1_name), 
        pd.Series(a2, name=method2_name)
    )
    
    # Run McNemar's test
    try:
        if contingency_table.shape == (2, 2):
            result = mcnemar(contingency_table, exact=False)
            p_value = result.pvalue
        else:
            # Handle edge cases (e.g., perfect agreement)
            p_value = 1.0
    except ValueError:
        p_value = 1.0
    
    # Extract counts for reporting
    if contingency_table.shape == (2, 2):
        # Table layout:
        #          Method2
        #          0    1
        # Method1 0 [0,0] [0,1] (Method2 wins)
        #         1 [1,0] [1,1]
        # (Method1 wins)
        
        # Note: pd.crosstab indices are sorted (0, 1)
        both_wrong = contingency_table.iloc[0, 0]
        method2_wins = contingency_table.iloc[0, 1]
        method1_wins = contingency_table.iloc[1, 0]
        both_right = contingency_table.iloc[1, 1]
    else:
        both_wrong = method2_wins = method1_wins = both_right = 0
    
    return {
        'p_value': p_value,
        'is_significant': p_value < 0.05,
        'method1_accuracy': acc1,
        'method2_accuracy': acc2,
        'method1_wins': method1_wins,
        'method2_wins': method2_wins,
        'diff': acc1 - acc2
    }

def compare_continuous_metrics(method1_values, method2_values, method1_name, method2_name):
    """Compare continuous metrics using paired t-test"""
    # Convert to numpy arrays and handle NaNs
    v1 = np.array(method1_values, dtype=float)
    v2 = np.array(method2_values, dtype=float)
    
    mask = ~(np.isnan(v1) | np.isnan(v2))
    v1_clean = v1[mask]
    v2_clean = v2[mask]
    
    if len(v1_clean) == 0:
        return {'error': 'No valid data'}
    
    mean1 = np.mean(v1_clean)
    mean2 = np.mean(v2_clean)
    
    # Paired t-test
    t_stat, p_value = stats.ttest_rel(v1_clean, v2_clean)
    
    return {
        'p_value': p_value,
        'is_significant': p_value < 0.05,
        'mean1': mean1,
        'mean2': mean2,
        'diff': mean1 - mean2
    }

# --- MAIN ANALYSIS FUNCTION ---

def analyze_seal_vs_adaptive(csv_path):
    print(f"🚀 LOADING DATA from {csv_path}...")
    df = pd.read_csv(csv_path)
    
    # --- CONFIGURATION: Method Prefixes ---
    # Extracted from your provided column list
    methods = {
        "SEAL_RAG": "seal_rag_200_k_5_model_4o_v12-ee7046b6",
        "Adaptive_K (Buffer)": "adaptive_k_rag_200_k_50_model_4o_with_buffer_v1-2128f8b2",
        "Adaptive_K (No Buffer)": "adaptive_k_rag_200_k_50_model_4o_without_buffer_v1-6a1ad24a"
    }
    
    metrics = ["final_answer_correct", "precision", "recall", "f1"]
    
    print("\n📊 COMPARISON RESULTS (Base: SEAL_RAG)")
    print("=" * 100)
    
    # Iterate over comparisons
    base_name = "SEAL_RAG"
    base_prefix = methods[base_name]
    
    comparisons = [
        "Adaptive_K (Buffer)", 
        "Adaptive_K (No Buffer)"
    ]
    
    results_table = []
    
    for comp_name in comparisons:
        comp_prefix = methods[comp_name]
        print(f"\n⚔️  {base_name} vs {comp_name}")
        print("-" * 80)
        
        for metric in metrics:
            # Construct column names
            col_base = f"{base_prefix}_{metric}"
            col_comp = f"{comp_prefix}_{metric}"
            
            # Check if columns exist
            if col_base not in df.columns or col_comp not in df.columns:
                print(f"⚠️  Missing columns for {metric}")
                continue
                
            # Run appropriate test
            if metric == "final_answer_correct":
                # Binary
                res = compare_binary_metrics(
                    df[col_base], df[col_comp], base_name, comp_name
                )
                
                # Print row
                significance = "**" if res['is_significant'] else ""
                print(f"   {metric:<20} | {base_name}: {res['method1_accuracy']:.1%} | {comp_name}: {res['method2_accuracy']:.1%} | Diff: {res['diff']:+.1%} | p={res['p_value']:.4f} {significance}")
                
                # Add to summary list
                results_table.append({
                    "Comparison": f"{base_name} vs {comp_name}",
                    "Metric": "Accuracy",
                    "Base Score": res['method1_accuracy'],
                    "Comp Score": res['method2_accuracy'],
                    "Diff": res['diff'],
                    "P-Value": res['p_value'],
                    "Significant": res['is_significant']
                })
                
            else:
                # Continuous
                res = compare_continuous_metrics(
                    df[col_base], df[col_comp], base_name, comp_name
                )
                
                # Print row
                significance = "**" if res['is_significant'] else ""
                print(f"   {metric:<20} | {base_name}: {res['mean1']:.3f} | {comp_name}: {res['mean2']:.3f} | Diff: {res['diff']:+.3f} | p={res['p_value']:.4f} {significance}")

                # Add to summary list
                results_table.append({
                    "Comparison": f"{base_name} vs {comp_name}",
                    "Metric": metric.capitalize(),
                    "Base Score": res['mean1'],
                    "Comp Score": res['mean2'],
                    "Diff": res['diff'],
                    "P-Value": res['p_value'],
                    "Significant": res['is_significant']
                })

    print("\n" + "=" * 100)
    
    # Return summary DataFrame
    return pd.DataFrame(results_table)

# --- USAGE ---
df_summary = analyze_seal_vs_adaptive("src/files/experiment_comparison/2WikiMultihopQA/adaptive_k_vs_seal_rag/seal_rag_4o.csv")
print("\nSUMMARY DATAFRAME:")
print(df_summary)

🚀 LOADING DATA from src/files/experiment_comparison/2WikiMultihopQA/adaptive_k_vs_seal_rag/seal_rag_4o.csv...

📊 COMPARISON RESULTS (Base: SEAL_RAG)
====================================================================================================

⚔️  SEAL_RAG vs Adaptive_K (Buffer)
--------------------------------------------------------------------------------
   final_answer_correct | SEAL_RAG: 74.5% | Adaptive_K (Buffer): 66.5% | Diff: +8.0% | p=0.0206 **
   precision            | SEAL_RAG: 0.963 | Adaptive_K (Buffer): 0.257 | Diff: +0.706 | p=0.0000 **
   recall               | SEAL_RAG: 0.772 | Adaptive_K (Buffer): 0.770 | Diff: +0.002 | p=0.9134
   f1                   | SEAL_RAG: 0.836 | Adaptive_K (Buffer): 0.377 | Diff: +0.459 | p=0.0000 **

⚔️  SEAL_RAG vs Adaptive_K (No Buffer)
--------------------------------------------------------------------------------
   final_answer_correct | SEAL_RAG: 74.5% | Adaptive_K (No Buffer): 41.5% | Diff: +33.0% | p=0.0000 **
   precision            | SEAL_RAG: 0.963 | Adaptive_K (No Buffer): 0.856 | Diff: +0.107 | p=0.0000 **
   recall               | SEAL_RAG: 0.772 | Adaptive_K (No Buffer): 0.610 | Diff: +0.162 | p=0.0000 **
   f1                   | SEAL_RAG: 0.836 | Adaptive_K (No Buffer): 0.652 | Diff: +0.183 | p=0.0000 **

====================================================================================================

SUMMARY DATAFRAME:
                           Comparison     Metric  Base Score  Comp Score  \
0     SEAL_RAG vs Adaptive_K (Buffer)   Accuracy    0.745000    0.665000
1     SEAL_RAG vs Adaptive_K (Buffer)  Precision    0.962500    0.256703
2     SEAL_RAG vs Adaptive_K (Buffer)     Recall    0.772500    0.770000
3     SEAL_RAG vs Adaptive_K (Buffer)         F1    0.835558    0.376516
4  SEAL_RAG vs Adaptive_K (No Buffer)   Accuracy    0.745000    0.415000
5  SEAL_RAG vs Adaptive_K (No Buffer)  Precision    0.962500    0.855850
6  SEAL_RAG vs Adaptive_K (No Buffer)     Recall    0.772500    0.610000
7  SEAL_RAG vs Adaptive_K (No Buffer)         F1    0.835558    0.652474

       Diff        P-Value  Significant
0  0.080000   2.063756e-02         True
1  0.705798  2.252590e-118         True
2  0.002500   9.134398e-01        False
3  0.459043   1.068979e-70         True
4  0.330000   7.071312e-13         True
5  0.106650   3.940723e-06         True
6  0.162500   2.739086e-11         True
7  0.183084   7.926359e-18         True

### Model 4o-mini | seal-rag k = 5 | adaptive k

In [36]:
df = pd.read_csv("src/files/experiment_comparison/2WikiMultihopQA/adaptive_k_vs_seal_rag/seal_rag_4o_mini.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_outputs,adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_outputs,seal_rag_200_k_5_model_4o_mini_v10-390ea694_outputs,adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_run,adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_run,seal_rag_200_k_5_model_4o_mini_v10-390ea694_run,adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_status,...,seal_rag_200_k_5_model_4o_mini_v10-390ea694_f1,adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_recall,adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_recall,seal_rag_200_k_5_model_4o_mini_v10-390ea694_recall,adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_precision,adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_precision,seal_rag_200_k_5_model_4o_mini_v10-390ea694_precision,adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_final_answer_correct,adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_final_answer_correct,seal_rag_200_k_5_model_4o_mini_v10-390ea694_final_answer_correct
0,002de458-f6e2-4ef7-991f-6c31359ec71c,"{""context"": ""{'title': ['Richard Annesley, 3rd...","{""answer"": ""2 September 1770""}","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""Richard Annesley, 2nd Earl A...","{""docs_to_use"": [""George Annesley, 2nd Earl of...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.0000,1.0,0.5,0.00,0.2222,0.2500,0.0,1.0,0.0,0.0
1,009279eb-aa2f-4e9a-a388-0570b3d0fad7,"{""context"": ""{'title': ['Caspar Babypants', 'B...","{""answer"": ""Liverpool""}","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""docs_to_use"": [""God (John Lennon song): \""Go...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.6667,1.0,1.0,0.50,0.2857,1.0000,1.0,1.0,1.0,1.0
2,01afabb2-0984-4333-bfff-0b3ad45cc593,"{""context"": ""{'title': ['M. Venkataraju', 'Wor...","{""answer"": ""United States""}","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough: World...","{""docs_to_use"": [""World and Time Enough: World...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.6667,0.5,0.5,0.50,0.1667,1.0000,1.0,1.0,1.0,0.0
3,04491c40-8385-4c7c-9d07-665afd6ef52d,"{""context"": ""{'title': ['James Woolley (clockm...","{""answer"": ""Madame Pasca""}","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""docs_to_use"": [""James T. O'Donohoe: James T....","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.0000,1.0,1.0,0.00,0.2500,0.6667,0.0,1.0,1.0,1.0
4,097adb49-d636-4e90-b9cf-ffed265452f6,"{""context"": ""{'title': ['Takayama Tomoteru', '...","{""answer"": ""Galați""}","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ioan S. Nenițescu: Ioan S. N...","{""docs_to_use"": [""Ștefan I. Nenițescu: Ștefan ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.6667,1.0,1.0,0.50,0.2857,1.0000,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,fc20c2aa-4e58-4517-ad1a-a050f0283457,"{""context"": ""{'title': ['Language Management',...","{""answer"": ""yes""}","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""docs_to_use"": [""Kaufland: Kaufland is a Germ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.6667,1.0,0.5,0.50,0.3333,1.0000,1.0,1.0,0.0,1.0
196,fc9ea4fb-5063-4d64-9bd3-e52efb03ecbe,"{""context"": ""{'title': ['Jayam Manade', 'Bulld...","{""answer"": ""Bulldog Drummond'S Revenge""}","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""docs_to_use"": [""Jayam Manade: Jayam Manade i...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.4000,0.5,0.5,0.25,0.1538,0.2500,1.0,1.0,1.0,1.0
197,fd41bcf3-aeb3-4d4e-80f7-580d7864172a,"{""context"": ""{'title': ['Control engineering',...","{""answer"": ""yes""}","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""docs_to_use"": [""ZTR Control Systems: ZTR Con...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.6667,1.0,1.0,0.50,0.2857,1.0000,1.0,1.0,0.0,0.0
198,fd8c17b6-5955-4adc-911f-a3d54ab6487e,"{""context"": ""{'title': ['Isipum of Geumgwan Ga...","{""answer"": ""India""}","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""docs_to_use"": [""Geodeung of Geumgwan Gaya: G...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.6667,1.0,1.0,0.50,0.1333,0.2000,1.0,1.0,1.0,0.0
199,fed9201d-05bd-4208-aa29-11b94b32d17f,"{""context"": ""{'title': ['Marcel Brands', 'Eric...","{""answer"": ""Víctor Bó""}","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""La Leona (film): La Leona is...","{""docs_to_use"": [""La Leona (film): La Leona is...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,...,0.6667,0.5,0.5,0.50,0.1667,1.0000,1.0,0.0,0.0,1.0

In [37]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_outputs',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_outputs',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_outputs',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_run',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_run',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_run',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_status',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_status',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_status',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_error',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_error',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_error',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_latency',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_latency',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_latency',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_tokens',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_tokens',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_tokens',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_total_cost',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_total_cost',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_total_cost',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_f1',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_f1',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_f1',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_recall',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_recall',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_recall',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_precision',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_precision',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_precision',
 'adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6_final_answer_correct',
 'adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1_final_answer_correct',
 'seal_rag_200_k_5_model_4o_mini_v10-390ea694_final_answer_correct']

In [39]:
import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.contingency_tables import mcnemar

# --- METRIC COMPARISON FUNCTIONS (REUSED) ---

def compare_binary_metrics(method1_results, method2_results, method1_name, method2_name):
    """Compare binary metrics using McNemar's test"""
    a1 = [int(x) for x in method1_results]
    a2 = [int(x) for x in method2_results]
    
    acc1 = sum(a1) / len(a1)
    acc2 = sum(a2) / len(a2)
    
    contingency_table = pd.crosstab(
        pd.Series(a1, name=method1_name), 
        pd.Series(a2, name=method2_name)
    )
    
    try:
        if contingency_table.shape == (2, 2):
            result = mcnemar(contingency_table, exact=False)
            p_value = result.pvalue
        else:
            p_value = 1.0
    except ValueError:
        p_value = 1.0
    
    return {
        'p_value': p_value,
        'is_significant': p_value < 0.05,
        'method1_accuracy': acc1,
        'method2_accuracy': acc2,
        'diff': acc1 - acc2
    }

def compare_continuous_metrics(method1_values, method2_values, method1_name, method2_name):
    """Compare continuous metrics using paired t-test"""
    v1 = np.array(method1_values, dtype=float)
    v2 = np.array(method2_values, dtype=float)
    
    mask = ~(np.isnan(v1) | np.isnan(v2))
    v1_clean = v1[mask]
    v2_clean = v2[mask]
    
    if len(v1_clean) == 0:
        return {'error': 'No valid data'}
    
    mean1 = np.mean(v1_clean)
    mean2 = np.mean(v2_clean)
    
    t_stat, p_value = stats.ttest_rel(v1_clean, v2_clean)
    
    return {
        'p_value': p_value,
        'is_significant': p_value < 0.05,
        'mean1': mean1,
        'mean2': mean2,
        'diff': mean1 - mean2
    }

# --- MAIN ANALYSIS FUNCTION FOR 4o-mini (UPDATED) ---

def analyze_seal_vs_adaptive_mini(csv_path):
    print(f"🚀 LOADING DATA from {csv_path}...")
    df = pd.read_csv(csv_path)
    
    # --- CONFIGURATION: Method Prefixes (UPDATED based on user input) ---
    methods = {
        "SEAL_RAG": "seal_rag_200_k_5_model_4o_mini_v10-390ea694",
        "Adaptive_K (Buffer)": "adaptive_k_rag_200_k_50_model_4o_mini_with_buffer_v3-772915b6",
        "Adaptive_K (No Buffer)": "adaptive_k_rag_200_k_50_model_4o_mini_without_buffer_v1-e49a13e1"
    }
    
    metrics = ["final_answer_correct", "precision", "recall", "f1"]
    
    print("\n📊 COMPARISON RESULTS (Base: SEAL_RAG [4o-mini])")
    print("=" * 100)
    
    base_name = "SEAL_RAG"
    base_prefix = methods[base_name]
    
    comparisons = [
        "Adaptive_K (Buffer)", 
        "Adaptive_K (No Buffer)"
    ]
    
    results_table = []
    
    for comp_name in comparisons:
        comp_prefix = methods[comp_name]
        print(f"\n⚔️  {base_name} vs {comp_name}")
        print("-" * 80)
        
        for metric in metrics:
            col_base = f"{base_prefix}_{metric}"
            col_comp = f"{comp_prefix}_{metric}"
            
            if col_base not in df.columns or col_comp not in df.columns:
                print(f"⚠️  Missing columns for {metric}")
                continue
                
            if metric == "final_answer_correct":
                res = compare_binary_metrics(df[col_base], df[col_comp], base_name, comp_name)
                significance = "**" if res['is_significant'] else ""
                print(f"   {metric:<20} | {base_name}: {res['method1_accuracy']:.1%} | {comp_name}: {res['method2_accuracy']:.1%} | Diff: {res['diff']:+.1%} | p={res['p_value']:.4f} {significance}")
                
                results_table.append({
                    "Comparison": f"{base_name} vs {comp_name}",
                    "Metric": "Accuracy",
                    "Base Score": res['method1_accuracy'],
                    "Comp Score": res['method2_accuracy'],
                    "Diff": res['diff'],
                    "P-Value": res['p_value'],
                    "Significant": res['is_significant']
                })
                
            else:
                res = compare_continuous_metrics(df[col_base], df[col_comp], base_name, comp_name)
                significance = "**" if res['is_significant'] else ""
                print(f"   {metric:<20} | {base_name}: {res['mean1']:.3f} | {comp_name}: {res['mean2']:.3f} | Diff: {res['diff']:+.3f} | p={res['p_value']:.4f} {significance}")

                results_table.append({
                    "Comparison": f"{base_name} vs {comp_name}",
                    "Metric": metric.capitalize(),
                    "Base Score": res['mean1'],
                    "Comp Score": res['mean2'],
                    "Diff": res['diff'],
                    "P-Value": res['p_value'],
                    "Significant": res['is_significant']
                })

    print("\n" + "=" * 100)
    return pd.DataFrame(results_table)

# --- USAGE ---
df_summary_mini = analyze_seal_vs_adaptive_mini("src/files/experiment_comparison/2WikiMultihopQA/adaptive_k_vs_seal_rag/seal_rag_4o_mini.csv")
print(df_summary_mini)

🚀 LOADING DATA from src/files/experiment_comparison/2WikiMultihopQA/adaptive_k_vs_seal_rag/seal_rag_4o_mini.csv...

📊 COMPARISON RESULTS (Base: SEAL_RAG [4o-mini])
====================================================================================================

⚔️  SEAL_RAG vs Adaptive_K (Buffer)
--------------------------------------------------------------------------------
   final_answer_correct | SEAL_RAG: 68.0% | Adaptive_K (Buffer): 60.5% | Diff: +7.5% | p=0.0778
   precision            | SEAL_RAG: 0.887 | Adaptive_K (Buffer): 0.257 | Diff: +0.631 | p=0.0000 **
   recall               | SEAL_RAG: 0.454 | Adaptive_K (Buffer): 0.770 | Diff: -0.316 | p=0.0000 **
   f1                   | SEAL_RAG: 0.591 | Adaptive_K (Buffer): 0.377 | Diff: +0.214 | p=0.0000 **

⚔️  SEAL_RAG vs Adaptive_K (No Buffer)
--------------------------------------------------------------------------------
   final_answer_correct | SEAL_RAG: 68.0% | Adaptive_K (No Buffer): 40.5% | Diff: +27.5% | p=0.0000 **
   precision            | SEAL_RAG: 0.887 | Adaptive_K (No Buffer): 0.856 | Diff: +0.032 | p=0.1348
   recall               | SEAL_RAG: 0.454 | Adaptive_K (No Buffer): 0.610 | Diff: -0.156 | p=0.0000 **
   f1                   | SEAL_RAG: 0.591 | Adaptive_K (No Buffer): 0.652 | Diff: -0.062 | p=0.0004 **

====================================================================================================
                           Comparison     Metric  Base Score  Comp Score  \
0     SEAL_RAG vs Adaptive_K (Buffer)   Accuracy    0.680000    0.605000
1     SEAL_RAG vs Adaptive_K (Buffer)  Precision    0.887500    0.256703
2     SEAL_RAG vs Adaptive_K (Buffer)     Recall    0.453750    0.770000
3     SEAL_RAG vs Adaptive_K (Buffer)         F1    0.590544    0.376516
4  SEAL_RAG vs Adaptive_K (No Buffer)   Accuracy    0.680000    0.405000
5  SEAL_RAG vs Adaptive_K (No Buffer)  Precision    0.887500    0.855850
6  SEAL_RAG vs Adaptive_K (No Buffer)     Recall    0.453750    0.610000
7  SEAL_RAG vs Adaptive_K (No Buffer)         F1    0.590544    0.652474

       Diff       P-Value  Significant
0  0.075000  7.775990e-02        False
1  0.630797  1.309016e-75         True
2 -0.316250  1.958248e-33         True
3  0.214028  3.396172e-27         True
4  0.275000  1.973175e-09         True
5  0.031650  1.348388e-01        False
6 -0.156250  6.324750e-12         True
7 -0.061930  4.351765e-04         True

## k = 1 | gpt 4.1-mini

In [ ]:
df = pd.read_csv("files/experiment_comarison/k_1/seal_k_1_model_4_1_mini.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_outputs,self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_outputs,crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_run,self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_run,crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_status,self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_status,crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_error,...,basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_total_cost,seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_total_cost,basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_final_answer_correct,seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_final_answer_correct,basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_f1,seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_f1,basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_recall,seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_recall,basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_precision,seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_precision
0,0004211d-fdd0-46a4-ba01-3a5d916924e9,"{""context"": ""{'title': ['Clayton Oliver', 'Ste...","{""answer"": ""1.95 m""}","{""response"": ""195 cm"", ""retrieved_docs_list"": ...","{""response"": ""Unknown from context"", ""retrieve...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000094,0.004675,0,1,0.6667,0.6667,0.5,0.5,1,1.0
1,009df37c-3a8f-4a00-b8ed-342f7754257e,"{""context"": ""{'title': [\""2012\u201313 VCU Ram...","{""answer"": ""1838""}","{""response"": ""1968"", ""retrieved_docs_list"": [""...","{""response"": ""Not provided"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000147,0.005162,0,1,0.6667,0.6667,0.5,0.5,1,1.0
2,00e0d7de-631c-47fc-b651-3e69c2029606,"{""context"": ""{'title': ['All I Wanna Do Is Mak...","{""answer"": ""2000""}","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""response"": ""Not provided"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000114,0.002539,1,1,0.6667,0.6667,0.5,0.5,1,1.0
3,0169d92a-754a-407c-afd8-5372b4b493a5,"{""context"": ""{'title': ['Alle tiders kupp', 'V...","{""answer"": ""Fomento Econ\u00f3mico Mexicano""}","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000085,0.002220,0,0,0.6667,0.6667,0.5,0.5,1,1.0
4,016dfba5-d311-462a-8ce5-c9db85d2159e,"{""context"": ""{'title': ['Baidu Baike', 'Social...","{""answer"": ""Wikimedia Foundation""}","{""response"": ""Qihoo 360 operates the website r...","{""response"": ""Chinese Wikipedia"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000120,0.007985,0,0,0.6667,0.6667,0.5,0.5,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,fdf4d662-d51a-4c36-a798-e5f9bc5bcc38,"{""context"": ""{'title': ['Archdeaconry of St An...","{""answer"": ""87""}","{""response"": ""87 parish churches"", ""retrieved_...","{""response"": ""Two parish churches"", ""retrieved...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000103,0.004451,0,0,0.6667,0.0000,0.5,0.0,1,0.0
996,fe72dc28-9b5f-41a7-ab23-bdb8e2ecaa97,"{""context"": ""{'title': ['Tralee Speedway', 'Di...","{""answer"": ""Dirt track racing""}","{""response"": ""Dirt track racing"", ""retrieved_d...","{""response"": ""Dirt track racing"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000102,0.002269,1,1,0.6667,0.6667,0.5,0.5,1,1.0
997,feab479e-056d-4066-9cf8-b687d34398b0,"{""context"": ""{'title': [\""2015 Rogers Cup \u20...","{""answer"": ""Roberta Vinci""}","{""response"": ""Jorge Lozano had the best single...","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000232,0.005086,0,1,0.6667,0.6667,0.5,0.5,1,1.0
998,ff316509-701e-4e84-ae05-17e9b2b3c080,"{""context"": ""{'title': ['Lana Del Rey (EP)', '...","{""answer"": ""Taylor Swift""}","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""response"": ""Kacey Musgraves"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000114,0.008798,0,0,0.6667,0.6667,0.5,0.5,1,1.0
999,ffd0e20e-29db-4cb6-bbbe-c6d4f0f2ac85,"{""context"": ""{'title': ['Fat Cat Brewery', 'Th...","{""answer"": ""46 Albert Square, Walford, London ...","{""response"": ""46 Albert Square"", ""retrieved_do...","{""response"": ""The Queen Victoria"", ""retrieved_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000147,0.004848,0,1,0.6667,0.6667,0.5,0.5,1,1.0

In [16]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_outputs',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_outputs',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_run',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_run',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_status',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_status',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_error',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_error',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_latency',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_latency',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_tokens',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_tokens',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_total_cost',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_total_cost',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_precision',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_precision',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_f1',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_f1',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_recall',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_recall',
 'crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_final_answer_correct',
 'self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_final_answer_correct',
 'id.1',
 'inputs.1',
 'reference_outputs.1',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_outputs',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_outputs',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_run',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_run',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_status',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_status',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_error',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_error',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_latency',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_latency',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_tokens',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_tokens',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_total_cost',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_total_cost',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_final_answer_correct',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_final_answer_correct',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_f1',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_f1',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_recall',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_recall',
 'basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_precision',
 'seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_precision']

In [17]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_final_answer_correct
   ✅ precision            → seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_precision
   ✅ recall               → seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_recall
   ✅ f1                   → seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_final_answer_correct
   ✅ precision            → self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_precision
   ✅ recall               → self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_recall
   ✅ f1                   → self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_final_answer_correct
   ✅ precision            → crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_precision
   ✅ recall               → crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_recall
   ✅ f1                   → crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_final_answer_correct
   ✅ precision            → basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_precision
   ✅ recall               → basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_recall
   ✅ f1                   → basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  0.004**
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_final_answer_correct
   SELF_RAG: self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 70.7% accuracy
   SELF_RAG: 49.2% accuracy
   Difference: -21.5%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    241       52      293
         Right    267      440      707
--------------------------------------------------
         Total    508      492     1000

🔍 INTERPRETATION:
   Both wrong: 241 questions
   SELF_RAG wins:  52 questions (when SEAL RAG fails)
   SEAL RAG wins: 267 questions (when SELF_RAG fails)
   Both right: 440 questions
   Disagreements: 319 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 5.1x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_precision
   SELF_RAG: self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8740 ± 0.3267
   SELF_RAG: 0.7250 ± 0.4467
   Mean difference: +0.1490
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 11.5485
   P-value: 0.000000
   Effect size (Cohen's d): 0.3652
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_recall
   SELF_RAG: self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4835 ± 0.2259
   SELF_RAG: 0.3625 ± 0.2234
   Mean difference: +0.1210
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 14.6275
   P-value: 0.000000
   Effect size (Cohen's d): 0.4626
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_f1
   SELF_RAG: self_rag_k_1_model_gpt-4.1_mini_v_319-8f373d89_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6137 ± 0.2451
   SELF_RAG: 0.4834 ± 0.2978
   Mean difference: +0.1303
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 13.8288
   P-value: 0.000000
   Effect size (Cohen's d): 0.4373
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_final_answer_correct
   CRAG_RAG: crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 70.7% accuracy
   CRAG_RAG: 52.5% accuracy
   Difference: -18.2%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    206       87      293
         Right    269      438      707
--------------------------------------------------
         Total    475      525     1000

🔍 INTERPRETATION:
   Both wrong: 206 questions
   CRAG_RAG wins:  87 questions (when SEAL RAG fails)
   SEAL RAG wins: 269 questions (when CRAG_RAG fails)
   Both right: 438 questions
   Disagreements: 356 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 3.1x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_precision
   CRAG_RAG: crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8740 ± 0.3267
   CRAG_RAG: 0.5690 ± 0.4955
   Mean difference: +0.3050
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 20.1680
   P-value: 0.000000
   Effect size (Cohen's d): 0.6378
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_recall
   CRAG_RAG: crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4835 ± 0.2259
   CRAG_RAG: 0.2845 ± 0.2477
   Mean difference: +0.1990
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 21.5233
   P-value: 0.000000
   Effect size (Cohen's d): 0.6806
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_f1
   CRAG_RAG: crag_rag_k_1_model_gpt-4.1_mini_v_318-e38f155c_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6137 ± 0.2451
   CRAG_RAG: 0.3794 ± 0.3303
   Mean difference: +0.2343
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 21.5888
   P-value: 0.000000
   Effect size (Cohen's d): 0.6827
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_final_answer_correct
   BASIC_RAG: basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 70.7% accuracy
   BASIC_RAG: 38.9% accuracy
   Difference: -31.8%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    248       45      293
         Right    363      344      707
--------------------------------------------------
         Total    611      389     1000

🔍 INTERPRETATION:
   Both wrong: 248 questions
   BASIC_RAG wins:  45 questions (when SEAL RAG fails)
   SEAL RAG wins: 363 questions (when BASIC_RAG fails)
   Both right: 344 questions
   Disagreements: 408 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 8.1x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_precision
   BASIC_RAG: basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8740 ± 0.3267
   BASIC_RAG: 0.8500 ± 0.3573
   Mean difference: +0.0240
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 2.9106
   P-value: 0.003687
   Effect size (Cohen's d): 0.0920
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: negligible

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_recall
   BASIC_RAG: basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4835 ± 0.2259
   BASIC_RAG: 0.4250 ± 0.1786
   Mean difference: +0.0585
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 9.3237
   P-value: 0.000000
   Effect size (Cohen's d): 0.2948
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_mini_v_316-9cbf4772_f1
   BASIC_RAG: basic_rag_k_1_model_gpt-4.1_mini_v_316-c794823e_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6137 ± 0.2451
   BASIC_RAG: 0.5667 ± 0.2382
   Mean difference: +0.0470
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 7.3299
   P-value: 0.000000
   Effect size (Cohen's d): 0.2318
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name      P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared 4.431436e-33            True          p < 0.001            70.7%                  49.2%                 -21.5%              267               52 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic 4.782766e-29            True          p < 0.001            0.874                  0.725                 +0.149 N/A (Continuous) N/A (Continuous)        0.365      t = 11.548
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic 4.761515e-44            True          p < 0.001            0.483                  0.362                 +0.121 N/A (Continuous) N/A (Continuous)        0.463      t = 14.628
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic 6.329742e-40            True          p < 0.001            0.614                  0.483                 +0.130 N/A (Continuous) N/A (Continuous)        0.437      t = 13.829
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared 8.557623e-22            True          p < 0.001            70.7%                  52.5%                 -18.2%              269               87 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 3.743740e-76            True          p < 0.001            0.874                  0.569                 +0.305 N/A (Continuous) N/A (Continuous)        0.638      t = 20.168
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 1.011194e-84            True          p < 0.001            0.483                  0.284                 +0.199 N/A (Continuous) N/A (Continuous)        0.681      t = 21.523
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 3.850468e-85            True          p < 0.001            0.614                  0.379                 +0.234 N/A (Continuous) N/A (Continuous)        0.683      t = 21.589
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared 1.666652e-55            True          p < 0.001            70.7%                  38.9%                 -31.8%              363               45 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 3.687456e-03            True           p < 0.01            0.874                  0.850                 +0.024 N/A (Continuous) N/A (Continuous)        0.092       t = 2.911
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 7.000346e-20            True          p < 0.001            0.483                  0.425                 +0.059 N/A (Continuous) N/A (Continuous)        0.295       t = 9.324
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic 4.748566e-13            True          p < 0.001            0.614                  0.567                 +0.047 N/A (Continuous) N/A (Continuous)        0.232       t = 7.330
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

         P_Value  Is_Significant Significance_Level Base_Performance  \
0   4.431436e-33            True          p < 0.001            70.7%
1   4.782766e-29            True          p < 0.001            0.874
2   4.761515e-44            True          p < 0.001            0.483
3   6.329742e-40            True          p < 0.001            0.614
4   8.557623e-22            True          p < 0.001            70.7%
5   3.743740e-76            True          p < 0.001            0.874
6   1.011194e-84            True          p < 0.001            0.483
7   3.850468e-85            True          p < 0.001            0.614
8   1.666652e-55            True          p < 0.001            70.7%
9   3.687456e-03            True           p < 0.01            0.874
10  7.000346e-20            True          p < 0.001            0.483
11  4.748566e-13            True          p < 0.001            0.614

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   49.2%                 -21.5%               267
1                   0.725                 +0.149  N/A (Continuous)
2                   0.362                 +0.121  N/A (Continuous)
3                   0.483                 +0.130  N/A (Continuous)
4                   52.5%                 -18.2%               269
5                   0.569                 +0.305  N/A (Continuous)
6                   0.284                 +0.199  N/A (Continuous)
7                   0.379                 +0.234  N/A (Continuous)
8                   38.9%                 -31.8%               363
9                   0.850                 +0.024  N/A (Continuous)
10                  0.425                 +0.059  N/A (Continuous)
11                  0.567                 +0.047  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 52  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.365      t = 11.548
2   N/A (Continuous)         0.463      t = 14.628
3   N/A (Continuous)         0.437      t = 13.829
4                 87  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         0.638      t = 20.168
6   N/A (Continuous)         0.681      t = 21.523
7   N/A (Continuous)         0.683      t = 21.589
8                 45  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         0.092       t = 2.911
10  N/A (Continuous)         0.295       t = 9.324
11  N/A (Continuous)         0.232       t = 7.330

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic


## k = 1 | gpt 4o-mini

In [ ]:
df = pd.read_csv("files/experiment_comarison/k_1/seal_k_1_model_4_o_mini.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_outputs,self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_outputs,basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_run,self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_run,basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_status,self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_status,basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_error,...,crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_total_cost,seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_total_cost,crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_precision,seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_precision,crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_final_answer_correct,seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_final_answer_correct,crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_recall,seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_recall,crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_f1,seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_f1
0,0004211d-fdd0-46a4-ba01-3a5d916924e9,"{""context"": ""{'title': ['Clayton Oliver', 'Ste...","{""answer"": ""1.95 m""}","{""response"": ""I don't know."", ""retrieved_docs_...","{""response"": ""Don't know."", ""retrieved_docs_li...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000265,0.001773,0,1.0,0,1,0.0,0.5,0.0000,0.6667
1,009df37c-3a8f-4a00-b8ed-342f7754257e,"{""context"": ""{'title': [\""2012\u201313 VCU Ram...","{""answer"": ""1838""}","{""response"": ""The year is not provided."", ""ret...","{""response"": ""Not specified in context."", ""ret...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000270,0.001872,0,1.0,1,1,0.0,0.5,0.0000,0.6667
2,00e0d7de-631c-47fc-b651-3e69c2029606,"{""context"": ""{'title': ['All I Wanna Do Is Mak...","{""answer"": ""2000""}","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""response"": ""I don't know."", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000346,0.003182,0,1.0,1,1,0.0,0.5,0.0000,0.6667
3,0169d92a-754a-407c-afd8-5372b4b493a5,"{""context"": ""{'title': ['Alle tiders kupp', 'V...","{""answer"": ""Fomento Econ\u00f3mico Mexicano""}","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000066,0.000809,1,1.0,0,0,0.5,0.5,0.6667,0.6667
4,016dfba5-d311-462a-8ce5-c9db85d2159e,"{""context"": ""{'title': ['Baidu Baike', 'Social...","{""answer"": ""Wikimedia Foundation""}","{""response"": ""Baidu."", ""retrieved_docs_list"": ...","{""response"": ""Chinese government"", ""retrieved_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000274,0.003052,0,1.0,0,0,0.0,0.5,0.0000,0.6667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,fdf4d662-d51a-4c36-a798-e5f9bc5bcc38,"{""context"": ""{'title': ['Archdeaconry of St An...","{""answer"": ""87""}","{""response"": ""The context does not specify the...","{""response"": ""Five parish churches."", ""retriev...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000285,0.001638,0,0.0,1,0,0.0,0.0,0.0000,0.0000
996,fe72dc28-9b5f-41a7-ab23-bdb8e2ecaa97,"{""context"": ""{'title': ['Tralee Speedway', 'Di...","{""answer"": ""Dirt track racing""}","{""response"": ""Dirt track racing"", ""retrieved_d...","{""response"": ""Dirt track racing"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000079,0.000830,1,1.0,1,1,0.5,0.5,0.6667,0.6667
997,feab479e-056d-4066-9cf8-b687d34398b0,"{""context"": ""{'title': [\""2015 Rogers Cup \u20...","{""answer"": ""Roberta Vinci""}","{""response"": ""Roberta Vinci."", ""retrieved_docs...","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000561,0.001922,0,1.0,0,1,0.0,0.5,0.0000,0.6667
998,ff316509-701e-4e84-ae05-17e9b2b3c080,"{""context"": ""{'title': ['Lana Del Rey (EP)', '...","{""answer"": ""Taylor Swift""}","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000309,0.000843,0,1.0,1,1,0.0,0.5,0.0000,0.6667
999,ffd0e20e-29db-4cb6-bbbe-c6d4f0f2ac85,"{""context"": ""{'title': ['Fat Cat Brewery', 'Th...","{""answer"": ""46 Albert Square, Walford, London ...","{""response"": ""The Queen Victoria public house....","{""response"": ""The Queen Victoria"", ""retrieved_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000362,0.000920,0,1.0,1,0,0.0,0.5,0.0000,0.6667

In [19]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_outputs',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_outputs',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_run',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_run',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_status',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_status',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_error',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_error',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_latency',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_latency',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_tokens',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_tokens',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_total_cost',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_total_cost',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_recall',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_recall',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_final_answer_correct',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_final_answer_correct',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_f1',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_f1',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_wrapper',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_wrapper',
 'basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_precision',
 'self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_precision',
 'id.1',
 'inputs.1',
 'reference_outputs.1',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_outputs',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_outputs',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_run',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_run',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_status',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_status',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_error',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_error',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_latency',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_latency',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_tokens',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_tokens',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_total_cost',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_total_cost',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_precision',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_precision',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_final_answer_correct',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_final_answer_correct',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_recall',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_recall',
 'crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_f1',
 'seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_f1']

In [20]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_final_answer_correct
   ✅ precision            → seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_precision
   ✅ recall               → seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_recall
   ✅ f1                   → seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_final_answer_correct
   ✅ precision            → self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_precision
   ✅ recall               → self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_recall
   ✅ f1                   → self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_final_answer_correct
   ✅ precision            → crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_precision
   ✅ recall               → crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_recall
   ✅ f1                   → crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_final_answer_correct
   ✅ precision            → basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_precision
   ✅ recall               → basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_recall
   ✅ f1                   → basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  0.200
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  0.005**
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_final_answer_correct
   SELF_RAG: self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 62.0% accuracy
   SELF_RAG: 48.4% accuracy
   Difference: -13.6%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    304       76      380
         Right    212      408      620
--------------------------------------------------
         Total    516      484     1000

🔍 INTERPRETATION:
   Both wrong: 304 questions
   SELF_RAG wins:  76 questions (when SEAL RAG fails)
   SEAL RAG wins: 212 questions (when SELF_RAG fails)
   Both right: 408 questions
   Disagreements: 288 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.8x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_precision
   SELF_RAG: self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8580 ± 0.3478
   SELF_RAG: 0.6110 ± 0.4878
   Mean difference: +0.2470
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 16.5324
   P-value: 0.000000
   Effect size (Cohen's d): 0.5228
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_recall
   SELF_RAG: self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4400 ± 0.1909
   SELF_RAG: 0.3055 ± 0.2439
   Mean difference: +0.1345
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 16.9155
   P-value: 0.000000
   Effect size (Cohen's d): 0.5349
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_f1
   SELF_RAG: self_rag_k_1_model_gpt-4o_mini_v_315-f5117a60_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5794 ± 0.2387
   SELF_RAG: 0.4074 ± 0.3252
   Mean difference: +0.1720
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 16.9051
   P-value: 0.000000
   Effect size (Cohen's d): 0.5346
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_final_answer_correct
   CRAG_RAG: crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 62.0% accuracy
   CRAG_RAG: 54.9% accuracy
   Difference: -7.1%
   P-value: 0.000032
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    274      106      380
         Right    177      443      620
--------------------------------------------------
         Total    451      549     1000

🔍 INTERPRETATION:
   Both wrong: 274 questions
   CRAG_RAG wins: 106 questions (when SEAL RAG fails)
   SEAL RAG wins: 177 questions (when CRAG_RAG fails)
   Both right: 443 questions
   Disagreements: 283 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 1.7x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_precision
   CRAG_RAG: crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8580 ± 0.3478
   CRAG_RAG: 0.4220 ± 0.4941
   Mean difference: +0.4360
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 27.6219
   P-value: 0.000000
   Effect size (Cohen's d): 0.8735
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_recall
   CRAG_RAG: crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4400 ± 0.1909
   CRAG_RAG: 0.2110 ± 0.2471
   Mean difference: +0.2290
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 27.1524
   P-value: 0.000000
   Effect size (Cohen's d): 0.8586
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_f1
   CRAG_RAG: crag_rag_k_1_model_gpt-4o_mini_v_317-7c831dda_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5794 ± 0.2387
   CRAG_RAG: 0.2813 ± 0.3294
   Mean difference: +0.2980
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 27.6315
   P-value: 0.000000
   Effect size (Cohen's d): 0.8738
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_final_answer_correct
   BASIC_RAG: basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 62.0% accuracy
   BASIC_RAG: 41.4% accuracy
   Difference: -20.6%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    326       54      380
         Right    260      360      620
--------------------------------------------------
         Total    586      414     1000

🔍 INTERPRETATION:
   Both wrong: 326 questions
   BASIC_RAG wins:  54 questions (when SEAL RAG fails)
   SEAL RAG wins: 260 questions (when BASIC_RAG fails)
   Both right: 360 questions
   Disagreements: 314 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 4.8x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_precision
   BASIC_RAG: basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8580 ± 0.3478
   BASIC_RAG: 0.8500 ± 0.3573
   Mean difference: +0.0080
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 1.2814
   P-value: 0.200338
   Effect size (Cohen's d): 0.0405
   Result: 🔴 NOT SIGNIFICANT - No significant difference
   Effect size interpretation: negligible

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_recall
   BASIC_RAG: basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4400 ± 0.1909
   BASIC_RAG: 0.4250 ± 0.1786
   Mean difference: +0.0150
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 3.8360
   P-value: 0.000133
   Effect size (Cohen's d): 0.1213
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: negligible

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_mini_v_315-6cc06d2d_f1
   BASIC_RAG: basic_rag_k_1_model_gpt-4o_mini_v_315-57fe8196_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5794 ± 0.2387
   BASIC_RAG: 0.5667 ± 0.2382
   Mean difference: +0.0127
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 2.8342
   P-value: 0.004686
   Effect size (Cohen's d): 0.0896
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: negligible


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name       P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared  1.792020e-15            True          p < 0.001            62.0%                  48.4%                 -13.6%              212               76 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic  1.868324e-54            True          p < 0.001            0.858                  0.611                 +0.247 N/A (Continuous) N/A (Continuous)        0.523      t = 16.532
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic  1.230110e-56            True          p < 0.001            0.440                  0.305                 +0.135 N/A (Continuous) N/A (Continuous)        0.535      t = 16.915
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic  1.411817e-56            True          p < 0.001            0.579                  0.407                 +0.172 N/A (Continuous) N/A (Continuous)        0.535      t = 16.905
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared  3.167626e-05            True          p < 0.001            62.0%                  54.9%                  -7.1%              177              106 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 3.091166e-125            True          p < 0.001            0.858                  0.422                 +0.436 N/A (Continuous) N/A (Continuous)        0.873      t = 27.622
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 4.825603e-122            True          p < 0.001            0.440                  0.211                 +0.229 N/A (Continuous) N/A (Continuous)        0.859      t = 27.152
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 2.659648e-125            True          p < 0.001            0.579                  0.281                 +0.298 N/A (Continuous) N/A (Continuous)        0.874      t = 27.631
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared  5.929300e-31            True          p < 0.001            62.0%                  41.4%                 -20.6%              260               54 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic  2.003378e-01           False    Not Significant            0.858                  0.850                 +0.008 N/A (Continuous) N/A (Continuous)        0.041       t = 1.281
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic  1.328725e-04            True          p < 0.001            0.440                  0.425                 +0.015 N/A (Continuous) N/A (Continuous)        0.121       t = 3.836
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic  4.686023e-03            True           p < 0.01            0.579                  0.567                 +0.013 N/A (Continuous) N/A (Continuous)        0.090       t = 2.834
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    1.792020e-15            True          p < 0.001            62.0%
1    1.868324e-54            True          p < 0.001            0.858
2    1.230110e-56            True          p < 0.001            0.440
3    1.411817e-56            True          p < 0.001            0.579
4    3.167626e-05            True          p < 0.001            62.0%
5   3.091166e-125            True          p < 0.001            0.858
6   4.825603e-122            True          p < 0.001            0.440
7   2.659648e-125            True          p < 0.001            0.579
8    5.929300e-31            True          p < 0.001            62.0%
9    2.003378e-01           False    Not Significant            0.858
10   1.328725e-04            True          p < 0.001            0.440
11   4.686023e-03            True           p < 0.01            0.579

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   48.4%                 -13.6%               212
1                   0.611                 +0.247  N/A (Continuous)
2                   0.305                 +0.135  N/A (Continuous)
3                   0.407                 +0.172  N/A (Continuous)
4                   54.9%                  -7.1%               177
5                   0.422                 +0.436  N/A (Continuous)
6                   0.211                 +0.229  N/A (Continuous)
7                   0.281                 +0.298  N/A (Continuous)
8                   41.4%                 -20.6%               260
9                   0.850                 +0.008  N/A (Continuous)
10                  0.425                 +0.015  N/A (Continuous)
11                  0.567                 +0.013  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 76  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.523      t = 16.532
2   N/A (Continuous)         0.535      t = 16.915
3   N/A (Continuous)         0.535      t = 16.905
4                106  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         0.873      t = 27.622
6   N/A (Continuous)         0.859      t = 27.152
7   N/A (Continuous)         0.874      t = 27.631
8                 54  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         0.041       t = 1.281
10  N/A (Continuous)         0.121       t = 3.836
11  N/A (Continuous)         0.090       t = 2.834

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \

## k = 1 | gpt 4o

In [ ]:
df = pd.read_csv("files/experiment_comarison/k_1/seal_k_1_model_4_o.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_outputs,self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_outputs,crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_run,self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_run,crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_status,self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_status,crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_error,...,basic_rag_k_1_model_gpt-4o_v_315-bfa73703_total_cost,seal_rag_k_1_model_gpt-4o_v_314-9eca2761_total_cost,basic_rag_k_1_model_gpt-4o_v_315-bfa73703_f1,seal_rag_k_1_model_gpt-4o_v_314-9eca2761_f1,basic_rag_k_1_model_gpt-4o_v_315-bfa73703_precision,seal_rag_k_1_model_gpt-4o_v_314-9eca2761_precision,basic_rag_k_1_model_gpt-4o_v_315-bfa73703_final_answer_correct,seal_rag_k_1_model_gpt-4o_v_314-9eca2761_final_answer_correct,basic_rag_k_1_model_gpt-4o_v_315-bfa73703_recall,seal_rag_k_1_model_gpt-4o_v_314-9eca2761_recall
0,0004211d-fdd0-46a4-ba01-3a5d916924e9,"{""context"": ""{'title': ['Clayton Oliver', 'Ste...","{""answer"": ""1.95 m""}","{""response"": ""195 cm"", ""retrieved_docs_list"": ...","{""response"": ""I don't know."", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000565,0.032835,0.6667,1.0000,1,1.0,0,1,0.5,1.0
1,009df37c-3a8f-4a00-b8ed-342f7754257e,"{""context"": ""{'title': [\""2012\u201313 VCU Ram...","{""answer"": ""1838""}","{""response"": ""1968"", ""retrieved_docs_list"": [""...","{""response"": ""1838"", ""retrieved_docs_list"": []...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000890,0.034978,0.6667,0.6667,1,1.0,0,0,0.5,0.5
2,00e0d7de-631c-47fc-b651-3e69c2029606,"{""context"": ""{'title': ['All I Wanna Do Is Mak...","{""answer"": ""2000""}","{""response"": ""January 2000"", ""retrieved_docs_l...","{""response"": ""I don't know."", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000772,0.014955,0.6667,0.6667,1,1.0,1,1,0.5,0.5
3,0169d92a-754a-407c-afd8-5372b4b493a5,"{""context"": ""{'title': ['Alle tiders kupp', 'V...","{""answer"": ""Fomento Econ\u00f3mico Mexicano""}","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000532,0.015510,0.6667,0.6667,1,1.0,0,0,0.5,0.5
4,016dfba5-d311-462a-8ce5-c9db85d2159e,"{""context"": ""{'title': ['Baidu Baike', 'Social...","{""answer"": ""Wikimedia Foundation""}","{""response"": ""ByteDance"", ""retrieved_docs_list...","{""response"": ""Wikipedia"", ""retrieved_docs_list...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000687,0.064340,0.6667,1.0000,1,1.0,0,1,0.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,fdf4d662-d51a-4c36-a798-e5f9bc5bcc38,"{""context"": ""{'title': ['Archdeaconry of St An...","{""answer"": ""87""}","{""response"": ""34 parish churches"", ""retrieved_...","{""response"": ""Eighty-nine churches"", ""retrieve...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000562,0.030558,0.6667,0.5000,1,0.5,0,0,0.5,0.5
996,fe72dc28-9b5f-41a7-ab23-bdb8e2ecaa97,"{""context"": ""{'title': ['Tralee Speedway', 'Di...","{""answer"": ""Dirt track racing""}","{""response"": ""Dirt track racing."", ""retrieved_...","{""response"": ""Dirt track racing"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000647,0.013848,0.6667,0.6667,1,1.0,1,1,0.5,0.5
997,feab479e-056d-4066-9cf8-b687d34398b0,"{""context"": ""{'title': [\""2015 Rogers Cup \u20...","{""answer"": ""Roberta Vinci""}","{""response"": ""Roberta Vinci."", ""retrieved_docs...","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.001342,0.035713,0.6667,1.0000,1,1.0,1,1,0.5,1.0
998,ff316509-701e-4e84-ae05-17e9b2b3c080,"{""context"": ""{'title': ['Lana Del Rey (EP)', '...","{""answer"": ""Taylor Swift""}","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000650,0.015637,0.6667,0.6667,1,1.0,1,1,0.5,0.5
999,ffd0e20e-29db-4cb6-bbbe-c6d4f0f2ac85,"{""context"": ""{'title': ['Fat Cat Brewery', 'Th...","{""answer"": ""46 Albert Square, Walford, London ...","{""response"": ""46 Albert Square, Walford, Londo...","{""response"": ""The Queen Victoria"", ""retrieved_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000880,0.033315,0.6667,1.0000,1,1.0,0,1,0.5,1.0

In [23]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_outputs',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_outputs',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_run',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_run',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_status',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_status',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_error',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_error',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_latency',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_latency',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_tokens',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_tokens',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_total_cost',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_total_cost',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_final_answer_correct',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_final_answer_correct',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_f1',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_f1',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_recall',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_recall',
 'crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_precision',
 'self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_precision',
 'id.1',
 'inputs.1',
 'reference_outputs.1',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_outputs',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_outputs',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_run',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_run',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_status',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_status',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_error',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_error',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_latency',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_latency',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_tokens',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_tokens',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_total_cost',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_total_cost',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_f1',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_f1',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_precision',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_precision',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_final_answer_correct',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_final_answer_correct',
 'basic_rag_k_1_model_gpt-4o_v_315-bfa73703_recall',
 'seal_rag_k_1_model_gpt-4o_v_314-9eca2761_recall']

In [24]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_k_1_model_gpt-4o_v_314-9eca2761_final_answer_correct
   ✅ precision            → seal_rag_k_1_model_gpt-4o_v_314-9eca2761_precision
   ✅ recall               → seal_rag_k_1_model_gpt-4o_v_314-9eca2761_recall
   ✅ f1                   → seal_rag_k_1_model_gpt-4o_v_314-9eca2761_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_final_answer_correct
   ✅ precision            → self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_precision
   ✅ recall               → self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_recall
   ✅ f1                   → self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_final_answer_correct
   ✅ precision            → crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_precision
   ✅ recall               → crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_recall
   ✅ f1                   → crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_k_1_model_gpt-4o_v_315-bfa73703_final_answer_correct
   ✅ precision            → basic_rag_k_1_model_gpt-4o_v_315-bfa73703_precision
   ✅ recall               → basic_rag_k_1_model_gpt-4o_v_315-bfa73703_recall
   ✅ f1                   → basic_rag_k_1_model_gpt-4o_v_315-bfa73703_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_final_answer_correct
   SELF_RAG: self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 72.8% accuracy
   SELF_RAG: 59.4% accuracy
   Difference: -13.4%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    197       75      272
         Right    209      519      728
--------------------------------------------------
         Total    406      594     1000

🔍 INTERPRETATION:
   Both wrong: 197 questions
   SELF_RAG wins:  75 questions (when SEAL RAG fails)
   SEAL RAG wins: 209 questions (when SELF_RAG fails)
   Both right: 519 questions
   Disagreements: 284 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.8x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_precision
   SELF_RAG: self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9087 ± 0.2754
   SELF_RAG: 0.7470 ± 0.4349
   Mean difference: +0.1617
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 12.6059
   P-value: 0.000000
   Effect size (Cohen's d): 0.3986
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_recall
   SELF_RAG: self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6195 ± 0.2899
   SELF_RAG: 0.3735 ± 0.2175
   Mean difference: +0.2460
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 24.0543
   P-value: 0.000000
   Effect size (Cohen's d): 0.7607
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_f1
   SELF_RAG: self_rag_k_1_model_gpt-4o_v_315-1b7e20ca_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7158 ± 0.2601
   SELF_RAG: 0.4980 ± 0.2900
   Mean difference: +0.2178
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 21.2008
   P-value: 0.000000
   Effect size (Cohen's d): 0.6704
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_final_answer_correct
   CRAG_RAG: crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 72.8% accuracy
   CRAG_RAG: 57.6% accuracy
   Difference: -15.2%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    207       65      272
         Right    217      511      728
--------------------------------------------------
         Total    424      576     1000

🔍 INTERPRETATION:
   Both wrong: 207 questions
   CRAG_RAG wins:  65 questions (when SEAL RAG fails)
   SEAL RAG wins: 217 questions (when CRAG_RAG fails)
   Both right: 511 questions
   Disagreements: 282 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 3.3x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_precision
   CRAG_RAG: crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9087 ± 0.2754
   CRAG_RAG: 0.5350 ± 0.4990
   Mean difference: +0.3737
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 24.3209
   P-value: 0.000000
   Effect size (Cohen's d): 0.7691
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_recall
   CRAG_RAG: crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6195 ± 0.2899
   CRAG_RAG: 0.2675 ± 0.2495
   Mean difference: +0.3520
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 29.4626
   P-value: 0.000000
   Effect size (Cohen's d): 0.9317
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_f1
   CRAG_RAG: crag_rag_k_1_model_gpt-4o_v_315-7642cfdb_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7158 ± 0.2601
   CRAG_RAG: 0.3567 ± 0.3327
   Mean difference: +0.3591
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 28.8112
   P-value: 0.000000
   Effect size (Cohen's d): 0.9111
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_final_answer_correct
   BASIC_RAG: basic_rag_k_1_model_gpt-4o_v_315-bfa73703_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 72.8% accuracy
   BASIC_RAG: 40.8% accuracy
   Difference: -32.0%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    235       37      272
         Right    357      371      728
--------------------------------------------------
         Total    592      408     1000

🔍 INTERPRETATION:
   Both wrong: 235 questions
   BASIC_RAG wins:  37 questions (when SEAL RAG fails)
   SEAL RAG wins: 357 questions (when BASIC_RAG fails)
   Both right: 371 questions
   Disagreements: 394 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 9.6x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_precision
   BASIC_RAG: basic_rag_k_1_model_gpt-4o_v_315-bfa73703_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9087 ± 0.2754
   BASIC_RAG: 0.8500 ± 0.3573
   Mean difference: +0.0587
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 6.9103
   P-value: 0.000000
   Effect size (Cohen's d): 0.2185
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_recall
   BASIC_RAG: basic_rag_k_1_model_gpt-4o_v_315-bfa73703_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6195 ± 0.2899
   BASIC_RAG: 0.4250 ± 0.1786
   Mean difference: +0.1945
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 23.3325
   P-value: 0.000000
   Effect size (Cohen's d): 0.7378
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4o_v_314-9eca2761_f1
   BASIC_RAG: basic_rag_k_1_model_gpt-4o_v_315-bfa73703_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7158 ± 0.2601
   BASIC_RAG: 0.5667 ± 0.2382
   Mean difference: +0.1491
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 20.3338
   P-value: 0.000000
   Effect size (Cohen's d): 0.6430
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name       P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared  2.971482e-15            True          p < 0.001            72.8%                  59.4%                 -13.4%              209               75 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic  6.431548e-34            True          p < 0.001            0.909                  0.747                 +0.162 N/A (Continuous) N/A (Continuous)        0.399      t = 12.606
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic 3.171391e-101            True          p < 0.001            0.620                  0.373                 +0.246 N/A (Continuous) N/A (Continuous)        0.761      t = 24.054
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic  1.156641e-82            True          p < 0.001            0.716                  0.498                 +0.218 N/A (Continuous) N/A (Continuous)        0.670      t = 21.201
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared  2.429504e-19            True          p < 0.001            72.8%                  57.6%                 -15.2%              217               65 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 5.400228e-103            True          p < 0.001            0.909                  0.535                 +0.374 N/A (Continuous) N/A (Continuous)        0.769      t = 24.321
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 8.104319e-138            True          p < 0.001            0.620                  0.268                 +0.352 N/A (Continuous) N/A (Continuous)        0.932      t = 29.463
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 2.343873e-133            True          p < 0.001            0.716                  0.357                 +0.359 N/A (Continuous) N/A (Continuous)        0.911      t = 28.811
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared  4.075398e-58            True          p < 0.001            72.8%                  40.8%                 -32.0%              357               37 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic  8.602342e-12            True          p < 0.001            0.909                  0.850                 +0.059 N/A (Continuous) N/A (Continuous)        0.219       t = 6.910
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic  1.840198e-96            True          p < 0.001            0.620                  0.425                 +0.195 N/A (Continuous) N/A (Continuous)        0.738      t = 23.332
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic  3.445457e-77            True          p < 0.001            0.716                  0.567                 +0.149 N/A (Continuous) N/A (Continuous)        0.643      t = 20.334
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    2.971482e-15            True          p < 0.001            72.8%
1    6.431548e-34            True          p < 0.001            0.909
2   3.171391e-101            True          p < 0.001            0.620
3    1.156641e-82            True          p < 0.001            0.716
4    2.429504e-19            True          p < 0.001            72.8%
5   5.400228e-103            True          p < 0.001            0.909
6   8.104319e-138            True          p < 0.001            0.620
7   2.343873e-133            True          p < 0.001            0.716
8    4.075398e-58            True          p < 0.001            72.8%
9    8.602342e-12            True          p < 0.001            0.909
10   1.840198e-96            True          p < 0.001            0.620
11   3.445457e-77            True          p < 0.001            0.716

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   59.4%                 -13.4%               209
1                   0.747                 +0.162  N/A (Continuous)
2                   0.373                 +0.246  N/A (Continuous)
3                   0.498                 +0.218  N/A (Continuous)
4                   57.6%                 -15.2%               217
5                   0.535                 +0.374  N/A (Continuous)
6                   0.268                 +0.352  N/A (Continuous)
7                   0.357                 +0.359  N/A (Continuous)
8                   40.8%                 -32.0%               357
9                   0.850                 +0.059  N/A (Continuous)
10                  0.425                 +0.195  N/A (Continuous)
11                  0.567                 +0.149  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 75  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.399      t = 12.606
2   N/A (Continuous)         0.761      t = 24.054
3   N/A (Continuous)         0.670      t = 21.201
4                 65  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         0.769      t = 24.321
6   N/A (Continuous)         0.932      t = 29.463
7   N/A (Continuous)         0.911      t = 28.811
8                 37  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         0.219       t = 6.910
10  N/A (Continuous)         0.738      t = 23.332
11  N/A (Continuous)         0.643      t = 20.334

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    2.971482e-15            True          p < 0.001            72.8%
1    6.431548e-34            True          p < 0.001            0.909

## k = 1 | gpt 4.1

In [ ]:
df = pd.read_csv("files/experiment_comarison/k_1/seal_k_1_model_4_1.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_outputs,self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_outputs,seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_run,self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_run,seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_status,self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_status,seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_error,...,basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_total_cost,crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_total_cost,basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_final_answer_correct,crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_final_answer_correct,basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_precision,crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_precision,basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_f1,crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_f1,basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_recall,crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_recall
0,0004211d-fdd0-46a4-ba01-3a5d916924e9,"{""context"": ""{'title': ['Clayton Oliver', 'Ste...","{""answer"": ""1.95 m""}","{""response"": ""1.95 m"", ""retrieved_docs_list"": ...","{""response"": ""1.95 m"", ""retrieved_docs_list"": ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000484,0.003738,0,1,1,0,0.6667,0.0000,0.5,0.0
1,009df37c-3a8f-4a00-b8ed-342f7754257e,"{""context"": ""{'title': [\""2012\u201313 VCU Ram...","{""answer"": ""1838""}","{""response"": ""1968"", ""retrieved_docs_list"": [""...","{""response"": ""1968"", ""retrieved_docs_list"": [""...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000752,0.004128,0,0,1,0,0.6667,0.0000,0.5,0.0
2,00e0d7de-631c-47fc-b651-3e69c2029606,"{""context"": ""{'title': ['All I Wanna Do Is Mak...","{""answer"": ""2000""}","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000610,0.004146,1,1,1,0,0.6667,0.0000,0.5,0.0
3,0169d92a-754a-407c-afd8-5372b4b493a5,"{""context"": ""{'title': ['Alle tiders kupp', 'V...","{""answer"": ""Fomento Econ\u00f3mico Mexicano""}","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000426,0.000876,0,0,1,1,0.6667,0.6667,0.5,0.5
4,016dfba5-d311-462a-8ce5-c9db85d2159e,"{""context"": ""{'title': ['Baidu Baike', 'Social...","{""answer"": ""Wikimedia Foundation""}","{""response"": ""Wikimedia Foundation"", ""retrieve...","{""response"": ""Chinese Wikipedia"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000542,0.003744,0,0,1,0,0.6667,0.0000,0.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,fdf4d662-d51a-4c36-a798-e5f9bc5bcc38,"{""context"": ""{'title': ['Archdeaconry of St An...","{""answer"": ""87""}","{""response"": ""87 parish churches"", ""retrieved_...","{""response"": ""Eighty-seven churches"", ""retriev...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000466,0.003552,0,1,1,0,0.6667,0.0000,0.5,0.0
996,fe72dc28-9b5f-41a7-ab23-bdb8e2ecaa97,"{""context"": ""{'title': ['Tralee Speedway', 'Di...","{""answer"": ""Dirt track racing""}","{""response"": ""Dirt track racing"", ""retrieved_d...","{""response"": ""Dirt track racing"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000510,0.001052,1,1,1,1,0.6667,0.6667,0.5,0.5
997,feab479e-056d-4066-9cf8-b687d34398b0,"{""context"": ""{'title': [\""2015 Rogers Cup \u20...","{""answer"": ""Roberta Vinci""}","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.001074,0.002186,1,0,1,1,0.6667,0.6667,0.5,0.5
998,ff316509-701e-4e84-ae05-17e9b2b3c080,"{""context"": ""{'title': ['Lana Del Rey (EP)', '...","{""answer"": ""Taylor Swift""}","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000520,0.001088,1,1,1,1,0.6667,0.6667,0.5,0.5
999,ffd0e20e-29db-4cb6-bbbe-c6d4f0f2ac85,"{""context"": ""{'title': ['Fat Cat Brewery', 'Th...","{""answer"": ""46 Albert Square, Walford, London ...","{""response"": ""46 Albert Square, Walford"", ""ret...","{""response"": ""The Queen Victoria"", ""retrieved_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000712,0.004192,0,0,1,0,0.6667,0.0000,0.5,0.0

In [26]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_outputs',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_outputs',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_run',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_run',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_status',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_status',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_error',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_error',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_latency',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_latency',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_tokens',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_tokens',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_total_cost',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_total_cost',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_recall',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_recall',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_precision',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_precision',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_final_answer_correct',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_final_answer_correct',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_f1',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_f1',
 'seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_wrapper',
 'self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_wrapper',
 'id.1',
 'inputs.1',
 'reference_outputs.1',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_outputs',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_outputs',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_run',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_run',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_status',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_status',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_error',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_error',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_latency',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_latency',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_tokens',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_tokens',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_total_cost',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_total_cost',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_final_answer_correct',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_final_answer_correct',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_precision',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_precision',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_f1',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_f1',
 'basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_recall',
 'crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_recall']

In [27]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_final_answer_correct
   ✅ precision            → seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_precision
   ✅ recall               → seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_recall
   ✅ f1                   → seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_final_answer_correct
   ✅ precision            → self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_precision
   ✅ recall               → self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_recall
   ✅ f1                   → self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_final_answer_correct
   ✅ precision            → crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_precision
   ✅ recall               → crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_recall
   ✅ f1                   → crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_final_answer_correct
   ✅ precision            → basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_precision
   ✅ recall               → basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_recall
   ✅ f1                   → basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_final_answer_correct
   SELF_RAG: self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 72.8% accuracy
   SELF_RAG: 63.3% accuracy
   Difference: -9.5%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    183       89      272
         Right    184      544      728
--------------------------------------------------
         Total    367      633     1000

🔍 INTERPRETATION:
   Both wrong: 183 questions
   SELF_RAG wins:  89 questions (when SEAL RAG fails)
   SEAL RAG wins: 184 questions (when SELF_RAG fails)
   Both right: 544 questions
   Disagreements: 273 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.1x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_precision
   SELF_RAG: self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8997 ± 0.2804
   SELF_RAG: 0.7918 ± 0.4062
   Mean difference: +0.1079
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 9.6060
   P-value: 0.000000
   Effect size (Cohen's d): 0.3039
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_recall
   SELF_RAG: self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6607 ± 0.3052
   SELF_RAG: 0.3959 ± 0.2031
   Mean difference: +0.2648
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 27.0214
   P-value: 0.000000
   Effect size (Cohen's d): 0.8549
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_f1
   SELF_RAG: self_rag_k_1_model_gpt-4.1_v_313-68bb3abd_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7401 ± 0.2724
   SELF_RAG: 0.5279 ± 0.2708
   Mean difference: +0.2122
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 22.7200
   P-value: 0.000000
   Effect size (Cohen's d): 0.7188
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_final_answer_correct
   CRAG_RAG: crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 72.8% accuracy
   CRAG_RAG: 57.9% accuracy
   Difference: -14.9%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    191       81      272
         Right    230      498      728
--------------------------------------------------
         Total    421      579     1000

🔍 INTERPRETATION:
   Both wrong: 191 questions
   CRAG_RAG wins:  81 questions (when SEAL RAG fails)
   SEAL RAG wins: 230 questions (when CRAG_RAG fails)
   Both right: 498 questions
   Disagreements: 311 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.8x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_precision
   CRAG_RAG: crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8997 ± 0.2804
   CRAG_RAG: 0.5686 ± 0.4955
   Mean difference: +0.3312
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 22.0625
   P-value: 0.000000
   Effect size (Cohen's d): 0.6980
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_recall
   CRAG_RAG: crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6607 ± 0.3052
   CRAG_RAG: 0.2843 ± 0.2478
   Mean difference: +0.3764
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 31.7073
   P-value: 0.000000
   Effect size (Cohen's d): 1.0032
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_f1
   CRAG_RAG: crag_rag_k_1_model_gpt-4.1_v_313-5fe8c082_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7401 ± 0.2724
   CRAG_RAG: 0.3791 ± 0.3304
   Mean difference: +0.3610
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 29.5753
   P-value: 0.000000
   Effect size (Cohen's d): 0.9357
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_final_answer_correct
   BASIC_RAG: basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 72.8% accuracy
   BASIC_RAG: 40.0% accuracy
   Difference: -32.8%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    230       42      272
         Right    370      358      728
--------------------------------------------------
         Total    600      400     1000

🔍 INTERPRETATION:
   Both wrong: 230 questions
   BASIC_RAG wins:  42 questions (when SEAL RAG fails)
   SEAL RAG wins: 370 questions (when BASIC_RAG fails)
   Both right: 358 questions
   Disagreements: 412 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 8.8x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_precision
   BASIC_RAG: basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8997 ± 0.2804
   BASIC_RAG: 0.8498 ± 0.3574
   Mean difference: +0.0499
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 6.2240
   P-value: 0.000000
   Effect size (Cohen's d): 0.1969
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: negligible

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_recall
   BASIC_RAG: basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6607 ± 0.3052
   BASIC_RAG: 0.4249 ± 0.1787
   Mean difference: +0.2357
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 27.5997
   P-value: 0.000000
   Effect size (Cohen's d): 0.8732
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_1_model_gpt-4.1_v_313-05674c6f_f1
   BASIC_RAG: basic_rag_k_1_model_gpt-4.1_v_313-19ef35d4_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7401 ± 0.2724
   BASIC_RAG: 0.5666 ± 0.2383
   Mean difference: +0.1735
   Sample size: 999 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 23.8490
   P-value: 0.000000
   Effect size (Cohen's d): 0.7545
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name       P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared  1.276817e-08            True          p < 0.001            72.8%                  63.3%                  -9.5%              184               89 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic  5.880797e-21            True          p < 0.001            0.900                  0.792                 +0.108 N/A (Continuous) N/A (Continuous)        0.304       t = 9.606
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic 3.991636e-121            True          p < 0.001            0.661                  0.396                 +0.265 N/A (Continuous) N/A (Continuous)        0.855      t = 27.021
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic  1.949814e-92            True          p < 0.001            0.740                  0.528                 +0.212 N/A (Continuous) N/A (Continuous)        0.719      t = 22.720
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared  4.766817e-17            True          p < 0.001            72.8%                  57.9%                 -14.9%              230               81 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic  3.584138e-88            True          p < 0.001            0.900                  0.569                 +0.331 N/A (Continuous) N/A (Continuous)        0.698      t = 22.062
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic 3.473079e-153            True          p < 0.001            0.661                  0.284                 +0.376 N/A (Continuous) N/A (Continuous)        1.003      t = 31.707
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 1.485419e-138            True          p < 0.001            0.740                  0.379                 +0.361 N/A (Continuous) N/A (Continuous)        0.936      t = 29.575
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared  2.165552e-58            True          p < 0.001            72.8%                  40.0%                 -32.8%              370               42 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic  7.123542e-10            True          p < 0.001            0.900                  0.850                 +0.050 N/A (Continuous) N/A (Continuous)        0.197       t = 6.224
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 4.683671e-125            True          p < 0.001            0.661                  0.425                 +0.236 N/A (Continuous) N/A (Continuous)        0.873      t = 27.600
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic 7.579479e-100            True          p < 0.001            0.740                  0.567                 +0.173 N/A (Continuous) N/A (Continuous)        0.755      t = 23.849
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    1.276817e-08            True          p < 0.001            72.8%
1    5.880797e-21            True          p < 0.001            0.900
2   3.991636e-121            True          p < 0.001            0.661
3    1.949814e-92            True          p < 0.001            0.740
4    4.766817e-17            True          p < 0.001            72.8%
5    3.584138e-88            True          p < 0.001            0.900
6   3.473079e-153            True          p < 0.001            0.661
7   1.485419e-138            True          p < 0.001            0.740
8    2.165552e-58            True          p < 0.001            72.8%
9    7.123542e-10            True          p < 0.001            0.900
10  4.683671e-125            True          p < 0.001            0.661
11  7.579479e-100            True          p < 0.001            0.740

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   63.3%                  -9.5%               184
1                   0.792                 +0.108  N/A (Continuous)
2                   0.396                 +0.265  N/A (Continuous)
3                   0.528                 +0.212  N/A (Continuous)
4                   57.9%                 -14.9%               230
5                   0.569                 +0.331  N/A (Continuous)
6                   0.284                 +0.376  N/A (Continuous)
7                   0.379                 +0.361  N/A (Continuous)
8                   40.0%                 -32.8%               370
9                   0.850                 +0.050  N/A (Continuous)
10                  0.425                 +0.236  N/A (Continuous)
11                  0.567                 +0.173  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 89  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.304       t = 9.606
2   N/A (Continuous)         0.855      t = 27.021
3   N/A (Continuous)         0.719      t = 22.720
4                 81  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         0.698      t = 22.062
6   N/A (Continuous)         1.003      t = 31.707
7   N/A (Continuous)         0.936      t = 29.575
8                 42  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         0.197       t = 6.224
10  N/A (Continuous)         0.873      t = 27.600
11  N/A (Continuous)         0.755      t = 23.849

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    1.276817e-08            True          p < 0.001            72.8%

## k = 3 | gpt 4.1-mini

In [ ]:
df = pd.read_csv("files/experiment_comarison/k_3/seal_k_3_model_4_1_mini.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_outputs,seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_outputs,crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_run,seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_run,crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_status,seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_status,crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_error,...,basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_total_cost,self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_total_cost,basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_recall,self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_recall,basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_f1,self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_f1,basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_precision,self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_precision,basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_final_answer_correct,self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_final_answer_correct
0,0004211d-fdd0-46a4-ba01-3a5d916924e9,"{""context"": ""{'title': ['Clayton Oliver', 'Ste...","{""answer"": ""1.95 m""}","{""response"": ""195 cm"", ""retrieved_docs_list"": ...","{""response"": ""1.95 m"", ""retrieved_docs_list"": ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000193,0.001798,0.5,0.0,0.4,0.0000,0.3333,0.0000,0,0
1,009df37c-3a8f-4a00-b8ed-342f7754257e,"{""context"": ""{'title': [\""2012\u201313 VCU Ram...","{""answer"": ""1838""}","{""response"": ""1968"", ""retrieved_docs_list"": [""...","{""response"": ""1968"", ""retrieved_docs_list"": [""...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000296,0.001472,0.5,0.0,0.4,0.0000,0.3333,0.0000,0,0
2,00e0d7de-631c-47fc-b651-3e69c2029606,"{""context"": ""{'title': ['All I Wanna Do Is Mak...","{""answer"": ""2000""}","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000237,0.002019,1.0,0.0,0.8,0.0000,0.6667,0.0000,1,0
3,0169d92a-754a-407c-afd8-5372b4b493a5,"{""context"": ""{'title': ['Alle tiders kupp', 'V...","{""answer"": ""Fomento Econ\u00f3mico Mexicano""}","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000171,0.000828,1.0,1.0,0.8,0.8000,0.6667,0.6667,0,0
4,016dfba5-d311-462a-8ce5-c9db85d2159e,"{""context"": ""{'title': ['Baidu Baike', 'Social...","{""answer"": ""Wikimedia Foundation""}","{""response"": ""Wikipedia is operated by an indi...","{""response"": ""Pan Haidong"", ""retrieved_docs_li...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000164,0.001251,0.5,0.5,0.4,0.6667,0.3333,1.0000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,fdf4d662-d51a-4c36-a798-e5f9bc5bcc38,"{""context"": ""{'title': ['Archdeaconry of St An...","{""answer"": ""87""}","{""response"": ""87 parish churches"", ""retrieved_...","{""response"": ""Eighty-eight parish churches"", ""...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000145,0.000617,0.5,0.0,0.4,0.0000,0.3333,0.0000,0,0
996,fe72dc28-9b5f-41a7-ab23-bdb8e2ecaa97,"{""context"": ""{'title': ['Tralee Speedway', 'Di...","{""answer"": ""Dirt track racing""}","{""response"": ""Dirt track racing on clay or dir...","{""response"": ""Dirt track racing"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000206,0.000846,0.5,0.5,0.4,0.6667,0.3333,1.0000,1,1
997,feab479e-056d-4066-9cf8-b687d34398b0,"{""context"": ""{'title': [\""2015 Rogers Cup \u20...","{""answer"": ""Roberta Vinci""}","{""response"": ""Roberta Vinci: No. 7; Jorge Loza...","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000289,0.001621,1.0,1.0,0.8,1.0000,0.6667,1.0000,1,1
998,ff316509-701e-4e84-ae05-17e9b2b3c080,"{""context"": ""{'title': ['Lana Del Rey (EP)', '...","{""answer"": ""Taylor Swift""}","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""response"": ""I don't know"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000276,0.000948,0.5,0.5,0.4,0.6667,0.3333,1.0000,1,0
999,ffd0e20e-29db-4cb6-bbbe-c6d4f0f2ac85,"{""context"": ""{'title': ['Fat Cat Brewery', 'Th...","{""answer"": ""46 Albert Square, Walford, London ...","{""response"": ""46 Albert Square"", ""retrieved_do...","{""response"": ""46 Albert Square"", ""retrieved_do...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000254,0.001403,0.5,0.5,0.4,0.5000,0.3333,0.5000,0,0

In [30]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_outputs',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_outputs',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_run',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_run',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_status',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_status',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_error',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_error',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_latency',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_latency',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_tokens',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_tokens',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_total_cost',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_total_cost',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_final_answer_correct',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_final_answer_correct',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_f1',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_f1',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_precision',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_precision',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_recall',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_recall',
 'crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_wrapper',
 'seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_wrapper',
 'id.1',
 'inputs.1',
 'reference_outputs.1',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_outputs',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_outputs',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_run',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_run',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_status',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_status',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_error',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_error',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_latency',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_latency',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_tokens',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_tokens',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_total_cost',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_total_cost',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_recall',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_recall',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_f1',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_f1',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_precision',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_precision',
 'basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_final_answer_correct',
 'self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_final_answer_correct']

In [31]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_final_answer_correct
   ✅ precision            → seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_precision
   ✅ recall               → seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_recall
   ✅ f1                   → seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_final_answer_correct
   ✅ precision            → self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_precision
   ✅ recall               → self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_recall
   ✅ f1                   → self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_final_answer_correct
   ✅ precision            → crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_precision
   ✅ recall               → crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_recall
   ✅ f1                   → crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_final_answer_correct
   ✅ precision            → basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_precision
   ✅ recall               → basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_recall
   ✅ f1                   → basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  0.839       < 0.001***
F1 Score             T-Test         0.848       < 0.001***  0.001**
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_final_answer_correct
   SELF_RAG: self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.6% accuracy
   SELF_RAG: 64.2% accuracy
   Difference: -12.4%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    187       47      234
         Right    171      595      766
--------------------------------------------------
         Total    358      642     1000

🔍 INTERPRETATION:
   Both wrong: 187 questions
   SELF_RAG wins:  47 questions (when SEAL RAG fails)
   SEAL RAG wins: 171 questions (when SELF_RAG fails)
   Both right: 595 questions
   Disagreements: 218 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 3.6x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_precision
   SELF_RAG: self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8637 ± 0.3271
   SELF_RAG: 0.7348 ± 0.3825
   Mean difference: +0.1288
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 9.9072
   P-value: 0.000000
   Effect size (Cohen's d): 0.3133
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_recall
   SELF_RAG: self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4885 ± 0.2273
   SELF_RAG: 0.5650 ± 0.3367
   Mean difference: -0.0765
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -6.6831
   P-value: 0.000000
   Effect size (Cohen's d): -0.2113
   Result: 🟢 SIGNIFICANT - SELF_RAG is significantly better
   Effect size interpretation: small

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_f1
   SELF_RAG: self_rag_k_3_model_gpt-4.1_mini_v_310-0ebf7a92_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6132 ± 0.2435
   SELF_RAG: 0.6112 ± 0.3187
   Mean difference: +0.0020
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 0.1915
   P-value: 0.848134
   Effect size (Cohen's d): 0.0061
   Result: 🔴 NOT SIGNIFICANT - No significant difference
   Effect size interpretation: negligible


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_final_answer_correct
   CRAG_RAG: crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.6% accuracy
   CRAG_RAG: 67.1% accuracy
   Difference: -9.5%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    156       78      234
         Right    173      593      766
--------------------------------------------------
         Total    329      671     1000

🔍 INTERPRETATION:
   Both wrong: 156 questions
   CRAG_RAG wins:  78 questions (when SEAL RAG fails)
   SEAL RAG wins: 173 questions (when CRAG_RAG fails)
   Both right: 593 questions
   Disagreements: 251 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.2x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_precision
   CRAG_RAG: crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8637 ± 0.3271
   CRAG_RAG: 0.3950 ± 0.2596
   Mean difference: +0.4687
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 41.4813
   P-value: 0.000000
   Effect size (Cohen's d): 1.3118
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_recall
   CRAG_RAG: crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4885 ± 0.2273
   CRAG_RAG: 0.4860 ± 0.3556
   Mean difference: +0.0025
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 0.2039
   P-value: 0.838507
   Effect size (Cohen's d): 0.0064
   Result: 🔴 NOT SIGNIFICANT - No significant difference
   Effect size interpretation: negligible

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_f1
   CRAG_RAG: crag_rag_k_3_model_gpt-4.1_mini_v_311-85775432_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6132 ± 0.2435
   CRAG_RAG: 0.4314 ± 0.2938
   Mean difference: +0.1818
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 17.1338
   P-value: 0.000000
   Effect size (Cohen's d): 0.5418
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_final_answer_correct
   BASIC_RAG: basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.6% accuracy
   BASIC_RAG: 64.0% accuracy
   Difference: -12.6%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    181       53      234
         Right    179      587      766
--------------------------------------------------
         Total    360      640     1000

🔍 INTERPRETATION:
   Both wrong: 181 questions
   BASIC_RAG wins:  53 questions (when SEAL RAG fails)
   SEAL RAG wins: 179 questions (when BASIC_RAG fails)
   Both right: 587 questions
   Disagreements: 232 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 3.4x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_precision
   BASIC_RAG: basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8637 ± 0.3271
   BASIC_RAG: 0.4935 ± 0.2048
   Mean difference: +0.3702
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 37.9904
   P-value: 0.000000
   Effect size (Cohen's d): 1.2014
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_recall
   BASIC_RAG: basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4885 ± 0.2273
   BASIC_RAG: 0.7235 ± 0.2922
   Mean difference: -0.2350
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -23.9383
   P-value: 0.000000
   Effect size (Cohen's d): -0.7570
   Result: 🟢 SIGNIFICANT - BASIC_RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_mini_v_311-bca1ff82_f1
   BASIC_RAG: basic_rag_k_3_model_gpt-4.1_mini_v_309-1005c6f1_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6132 ± 0.2435
   BASIC_RAG: 0.5855 ± 0.2376
   Mean difference: +0.0277
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 3.2617
   P-value: 0.001145
   Effect size (Cohen's d): 0.1031
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: negligible


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name       P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared  8.042607e-17            True          p < 0.001            76.6%                  64.2%                 -12.4%              171               47 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic  3.903172e-22            True          p < 0.001            0.864                  0.735                 +0.129 N/A (Continuous) N/A (Continuous)        0.313       t = 9.907
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic  3.882012e-11            True          p < 0.001            0.488                  0.565                 -0.076 N/A (Continuous) N/A (Continuous)       -0.211      t = -6.683
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic  8.481340e-01           False    Not Significant            0.613                  0.611                 +0.002 N/A (Continuous) N/A (Continuous)        0.006       t = 0.192
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared  2.970370e-09            True          p < 0.001            76.6%                  67.1%                  -9.5%              173               78 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 1.742336e-219            True          p < 0.001            0.864                  0.395                 +0.469 N/A (Continuous) N/A (Continuous)        1.312      t = 41.481
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic  8.385072e-01           False    Not Significant            0.488                  0.486                 +0.003 N/A (Continuous) N/A (Continuous)        0.006       t = 0.204
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic  6.829960e-58            True          p < 0.001            0.613                  0.431                 +0.182 N/A (Continuous) N/A (Continuous)        0.542      t = 17.134
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared  2.274415e-16            True          p < 0.001            76.6%                  64.0%                 -12.6%              179               53 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 3.946167e-196            True          p < 0.001            0.864                  0.494                 +0.370 N/A (Continuous) N/A (Continuous)        1.201      t = 37.990
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 1.859220e-100            True          p < 0.001            0.488                  0.724                 -0.235 N/A (Continuous) N/A (Continuous)       -0.757     t = -23.938
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic  1.145140e-03            True           p < 0.01            0.613                  0.586                 +0.028 N/A (Continuous) N/A (Continuous)        0.103       t = 3.262
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    8.042607e-17            True          p < 0.001            76.6%
1    3.903172e-22            True          p < 0.001            0.864
2    3.882012e-11            True          p < 0.001            0.488
3    8.481340e-01           False    Not Significant            0.613
4    2.970370e-09            True          p < 0.001            76.6%
5   1.742336e-219            True          p < 0.001            0.864
6    8.385072e-01           False    Not Significant            0.488
7    6.829960e-58            True          p < 0.001            0.613
8    2.274415e-16            True          p < 0.001            76.6%
9   3.946167e-196            True          p < 0.001            0.864
10  1.859220e-100            True          p < 0.001            0.488
11   1.145140e-03            True           p < 0.01            0.613

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   64.2%                 -12.4%               171
1                   0.735                 +0.129  N/A (Continuous)
2                   0.565                 -0.076  N/A (Continuous)
3                   0.611                 +0.002  N/A (Continuous)
4                   67.1%                  -9.5%               173
5                   0.395                 +0.469  N/A (Continuous)
6                   0.486                 +0.003  N/A (Continuous)
7                   0.431                 +0.182  N/A (Continuous)
8                   64.0%                 -12.6%               179
9                   0.494                 +0.370  N/A (Continuous)
10                  0.724                 -0.235  N/A (Continuous)
11                  0.586                 +0.028  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 47  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.313       t = 9.907
2   N/A (Continuous)        -0.211      t = -6.683
3   N/A (Continuous)         0.006       t = 0.192
4                 78  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         1.312      t = 41.481
6   N/A (Continuous)         0.006       t = 0.204
7   N/A (Continuous)         0.542      t = 17.134
8                 53  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         1.201      t = 37.990
10  N/A (Continuous)        -0.757     t = -23.938
11  N/A (Continuous)         0.103       t = 3.262

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \

## k = 3 | gpt 4o-mini

In [ ]:
df = pd.read_csv("files/experiment_comarison/k_3/seal_k_3_model_4_o_mini.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_outputs,self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_outputs,crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_run,self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_run,crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_status,self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_status,crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_error,...,basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_total_cost,seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_total_cost,basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_precision,seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_precision,basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_recall,seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_recall,basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_final_answer_correct,seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_final_answer_correct,basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_f1,seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_f1
0,0004211d-fdd0-46a4-ba01-3a5d916924e9,"{""context"": ""{'title': ['Clayton Oliver', 'Ste...","{""answer"": ""1.95 m""}","{""response"": ""I don't know."", ""retrieved_docs_...","{""response"": ""Don't know."", ""retrieved_docs_li...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000072,0.002544,0.3333,1.0,0.5,0.5,0,1,0.4,0.6667
1,009df37c-3a8f-4a00-b8ed-342f7754257e,"{""context"": ""{'title': [\""2012\u201313 VCU Ram...","{""answer"": ""1838""}","{""response"": ""1968"", ""retrieved_docs_list"": [""...","{""response"": ""Not specified in context."", ""ret...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000111,0.002888,0.3333,1.0,0.5,0.5,0,1,0.4,0.6667
2,00e0d7de-631c-47fc-b651-3e69c2029606,"{""context"": ""{'title': ['All I Wanna Do Is Mak...","{""answer"": ""2000""}","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""response"": ""Don't know."", ""retrieved_docs_li...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000092,0.004289,0.6667,1.0,1.0,0.5,1,0,0.8,0.6667
3,0169d92a-754a-407c-afd8-5372b4b493a5,"{""context"": ""{'title': ['Alle tiders kupp', 'V...","{""answer"": ""Fomento Econ\u00f3mico Mexicano""}","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000064,0.001363,0.6667,1.0,1.0,0.5,0,0,0.8,0.6667
4,016dfba5-d311-462a-8ce5-c9db85d2159e,"{""context"": ""{'title': ['Baidu Baike', 'Social...","{""answer"": ""Wikimedia Foundation""}","{""response"": ""Baike.com, operated by Pan Haido...","{""response"": ""Chinese Wikipedia"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000062,0.003356,0.3333,1.0,0.5,0.5,0,0,0.4,0.6667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,fdf4d662-d51a-4c36-a798-e5f9bc5bcc38,"{""context"": ""{'title': ['Archdeaconry of St An...","{""answer"": ""87""}","{""response"": ""Eighty-eight parish churches."", ...","{""response"": ""Eighty-eight parish churches."", ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000054,0.001163,0.3333,0.0,0.5,0.0,0,0,0.4,0.0000
996,fe72dc28-9b5f-41a7-ab23-bdb8e2ecaa97,"{""context"": ""{'title': ['Tralee Speedway', 'Di...","{""answer"": ""Dirt track racing""}","{""response"": ""Dirt track racing"", ""retrieved_d...","{""response"": ""Dirt track racing"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000078,0.001359,0.3333,0.5,0.5,0.5,1,1,0.4,0.5000
997,feab479e-056d-4066-9cf8-b687d34398b0,"{""context"": ""{'title': [\""2015 Rogers Cup \u20...","{""answer"": ""Roberta Vinci""}","{""response"": ""Roberta Vinci."", ""retrieved_docs...","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000108,0.001458,0.6667,1.0,1.0,0.5,1,1,0.8,0.6667
998,ff316509-701e-4e84-ae05-17e9b2b3c080,"{""context"": ""{'title': ['Lana Del Rey (EP)', '...","{""answer"": ""Taylor Swift""}","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000103,0.001340,0.3333,1.0,0.5,0.5,1,1,0.4,0.6667
999,ffd0e20e-29db-4cb6-bbbe-c6d4f0f2ac85,"{""context"": ""{'title': ['Fat Cat Brewery', 'Th...","{""answer"": ""46 Albert Square, Walford, London ...","{""response"": ""46 Albert Square"", ""retrieved_do...","{""response"": ""The Queen Victoria"", ""retrieved_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.000095,0.001533,0.3333,1.0,0.5,0.5,0,0,0.4,0.6667

In [33]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_outputs',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_outputs',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_run',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_run',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_status',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_status',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_error',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_error',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_latency',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_latency',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_tokens',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_tokens',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_total_cost',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_total_cost',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_final_answer_correct',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_final_answer_correct',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_recall',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_recall',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_f1',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_f1',
 'crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_precision',
 'self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_precision',
 'id.1',
 'inputs.1',
 'reference_outputs.1',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_outputs',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_outputs',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_run',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_run',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_status',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_status',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_error',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_error',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_latency',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_latency',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_tokens',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_tokens',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_total_cost',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_total_cost',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_precision',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_precision',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_recall',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_recall',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_final_answer_correct',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_final_answer_correct',
 'basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_f1',
 'seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_f1']

In [34]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_final_answer_correct
   ✅ precision            → seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_precision
   ✅ recall               → seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_recall
   ✅ f1                   → seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_final_answer_correct
   ✅ precision            → self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_precision
   ✅ recall               → self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_recall
   ✅ f1                   → self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_final_answer_correct
   ✅ precision            → crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_precision
   ✅ recall               → crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_recall
   ✅ f1                   → crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_final_answer_correct
   ✅ precision            → basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_precision
   ✅ recall               → basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_recall
   ✅ f1                   → basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         0.010**     < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  0.101
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_final_answer_correct
   SELF_RAG: self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 69.1% accuracy
   SELF_RAG: 59.9% accuracy
   Difference: -9.2%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    239       70      309
         Right    162      529      691
--------------------------------------------------
         Total    401      599     1000

🔍 INTERPRETATION:
   Both wrong: 239 questions
   SELF_RAG wins:  70 questions (when SEAL RAG fails)
   SEAL RAG wins: 162 questions (when SELF_RAG fails)
   Both right: 529 questions
   Disagreements: 232 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.3x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_precision
   SELF_RAG: self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8390 ± 0.3609
   SELF_RAG: 0.6633 ± 0.4301
   Mean difference: +0.1757
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 12.2653
   P-value: 0.000000
   Effect size (Cohen's d): 0.3879
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_recall
   SELF_RAG: self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4405 ± 0.2056
   SELF_RAG: 0.4690 ± 0.3364
   Mean difference: -0.0285
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -2.5903
   P-value: 0.009729
   Effect size (Cohen's d): -0.0819
   Result: 🟢 SIGNIFICANT - SELF_RAG is significantly better
   Effect size interpretation: negligible

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_f1
   SELF_RAG: self_rag_k_3_model_gpt-4o_mini_v_312-d812c7b7_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5732 ± 0.2500
   SELF_RAG: 0.5280 ± 0.3427
   Mean difference: +0.0452
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 4.0386
   P-value: 0.000058
   Effect size (Cohen's d): 0.1277
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: negligible


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_final_answer_correct
   CRAG_RAG: crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 69.1% accuracy
   CRAG_RAG: 62.0% accuracy
   Difference: -7.1%
   P-value: 0.000028
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    205      104      309
         Right    175      516      691
--------------------------------------------------
         Total    380      620     1000

🔍 INTERPRETATION:
   Both wrong: 205 questions
   CRAG_RAG wins: 104 questions (when SEAL RAG fails)
   SEAL RAG wins: 175 questions (when CRAG_RAG fails)
   Both right: 516 questions
   Disagreements: 279 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 1.7x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_precision
   CRAG_RAG: crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8390 ± 0.3609
   CRAG_RAG: 0.3030 ± 0.2733
   Mean difference: +0.5360
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 42.9639
   P-value: 0.000000
   Effect size (Cohen's d): 1.3586
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_recall
   CRAG_RAG: crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4405 ± 0.2056
   CRAG_RAG: 0.3625 ± 0.3528
   Mean difference: +0.0780
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 6.6385
   P-value: 0.000000
   Effect size (Cohen's d): 0.2099
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_f1
   CRAG_RAG: crag_rag_k_3_model_gpt-4o_mini_v_313-bf757073_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5732 ± 0.2500
   CRAG_RAG: 0.3268 ± 0.3019
   Mean difference: +0.2464
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 22.6373
   P-value: 0.000000
   Effect size (Cohen's d): 0.7159
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_final_answer_correct
   BASIC_RAG: basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 69.1% accuracy
   BASIC_RAG: 62.8% accuracy
   Difference: -6.3%
   P-value: 0.000039
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    227       82      309
         Right    145      546      691
--------------------------------------------------
         Total    372      628     1000

🔍 INTERPRETATION:
   Both wrong: 227 questions
   BASIC_RAG wins:  82 questions (when SEAL RAG fails)
   SEAL RAG wins: 145 questions (when BASIC_RAG fails)
   Both right: 546 questions
   Disagreements: 227 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 1.8x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_precision
   BASIC_RAG: basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8390 ± 0.3609
   BASIC_RAG: 0.4942 ± 0.2042
   Mean difference: +0.3448
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 33.6691
   P-value: 0.000000
   Effect size (Cohen's d): 1.0647
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_recall
   BASIC_RAG: basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.4405 ± 0.2056
   BASIC_RAG: 0.7245 ± 0.2914
   Mean difference: -0.2840
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -32.8112
   P-value: 0.000000
   Effect size (Cohen's d): -1.0376
   Result: 🟢 SIGNIFICANT - BASIC_RAG is significantly better
   Effect size interpretation: large

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_mini_v_311-56340dc9_f1
   BASIC_RAG: basic_rag_k_3_model_gpt-4o_mini_v_312-f0d9fd12_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.5732 ± 0.2500
   BASIC_RAG: 0.5863 ± 0.2370
   Mean difference: -0.0131
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -1.6409
   P-value: 0.101136
   Effect size (Cohen's d): -0.0519
   Result: 🔴 NOT SIGNIFICANT - No significant difference
   Effect size interpretation: negligible


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name       P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared  2.308781e-09            True          p < 0.001            69.1%                  59.9%                  -9.2%              162               70 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic  2.577308e-32            True          p < 0.001            0.839                  0.663                 +0.176 N/A (Continuous) N/A (Continuous)        0.388      t = 12.265
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic  9.729444e-03            True           p < 0.01            0.441                  0.469                 -0.029 N/A (Continuous) N/A (Continuous)       -0.082      t = -2.590
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic  5.789995e-05            True          p < 0.001            0.573                  0.528                 +0.045 N/A (Continuous) N/A (Continuous)        0.128       t = 4.039
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared  2.779844e-05            True          p < 0.001            69.1%                  62.0%                  -7.1%              175              104 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 2.966816e-229            True          p < 0.001            0.839                  0.303                 +0.536 N/A (Continuous) N/A (Continuous)        1.359      t = 42.964
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic  5.191065e-11            True          p < 0.001            0.441                  0.362                 +0.078 N/A (Continuous) N/A (Continuous)        0.210       t = 6.639
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic  6.491026e-92            True          p < 0.001            0.573                  0.327                 +0.246 N/A (Continuous) N/A (Continuous)        0.716      t = 22.637
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared  3.870375e-05            True          p < 0.001            69.1%                  62.8%                  -6.3%              145               82 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 1.073090e-166            True          p < 0.001            0.839                  0.494                 +0.345 N/A (Continuous) N/A (Continuous)        1.065      t = 33.669
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic 8.246675e-161            True          p < 0.001            0.441                  0.725                 -0.284 N/A (Continuous) N/A (Continuous)       -1.038     t = -32.811
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic  1.011364e-01           False    Not Significant            0.573                  0.586                 -0.013 N/A (Continuous) N/A (Continuous)       -0.052      t = -1.641
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    2.308781e-09            True          p < 0.001            69.1%
1    2.577308e-32            True          p < 0.001            0.839
2    9.729444e-03            True           p < 0.01            0.441
3    5.789995e-05            True          p < 0.001            0.573
4    2.779844e-05            True          p < 0.001            69.1%
5   2.966816e-229            True          p < 0.001            0.839
6    5.191065e-11            True          p < 0.001            0.441
7    6.491026e-92            True          p < 0.001            0.573
8    3.870375e-05            True          p < 0.001            69.1%
9   1.073090e-166            True          p < 0.001            0.839
10  8.246675e-161            True          p < 0.001            0.441
11   1.011364e-01           False    Not Significant            0.573

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   59.9%                  -9.2%               162
1                   0.663                 +0.176  N/A (Continuous)
2                   0.469                 -0.029  N/A (Continuous)
3                   0.528                 +0.045  N/A (Continuous)
4                   62.0%                  -7.1%               175
5                   0.303                 +0.536  N/A (Continuous)
6                   0.362                 +0.078  N/A (Continuous)
7                   0.327                 +0.246  N/A (Continuous)
8                   62.8%                  -6.3%               145
9                   0.494                 +0.345  N/A (Continuous)
10                  0.725                 -0.284  N/A (Continuous)
11                  0.586                 -0.013  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 70  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.388      t = 12.265
2   N/A (Continuous)        -0.082      t = -2.590
3   N/A (Continuous)         0.128       t = 4.039
4                104  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         1.359      t = 42.964
6   N/A (Continuous)         0.210       t = 6.639
7   N/A (Continuous)         0.716      t = 22.637
8                 82  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         1.065      t = 33.669
10  N/A (Continuous)        -1.038     t = -32.811
11  N/A (Continuous)        -0.052      t = -1.641

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \

## k = 3 | gpt 4o

In [ ]:
df = pd.read_csv("files/experiment_comarison/k_3/seal_k_3_model_4_o.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_outputs,self_rag_k_3_model_gpt-4o_v_304-1cb5682e_outputs,seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_run,self_rag_k_3_model_gpt-4o_v_304-1cb5682e_run,seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_status,self_rag_k_3_model_gpt-4o_v_304-1cb5682e_status,seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_error,...,basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_wrapper,crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_wrapper,basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_final_answer_correct,crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_final_answer_correct,basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_precision,crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_precision,basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_recall,crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_recall,basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_f1,crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_f1
0,0004211d-fdd0-46a4-ba01-3a5d916924e9,"{""context"": ""{'title': ['Clayton Oliver', 'Ste...","{""answer"": ""1.95 m""}","{""response"": ""1.95 m"", ""retrieved_docs_list"": ...","{""response"": ""I don't know."", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,0,1.0,0.3333,0.0,0.5,0.0,0.4,0.0
1,009df37c-3a8f-4a00-b8ed-342f7754257e,"{""context"": ""{'title': [\""2012\u201313 VCU Ram...","{""answer"": ""1838""}","{""response"": ""1838"", ""retrieved_docs_list"": [""...","{""response"": ""1968"", ""retrieved_docs_list"": []...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,0,0.0,0.3333,0.0,0.5,0.0,0.4,0.0
2,00e0d7de-631c-47fc-b651-3e69c2029606,"{""context"": ""{'title': ['All I Wanna Do Is Mak...","{""answer"": ""2000""}","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,1,1.0,0.6667,0.0,1.0,0.0,0.8,0.0
3,0169d92a-754a-407c-afd8-5372b4b493a5,"{""context"": ""{'title': ['Alle tiders kupp', 'V...","{""answer"": ""Fomento Econ\u00f3mico Mexicano""}","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,0,0.0,0.6667,0.5,1.0,0.5,0.8,0.5
4,016dfba5-d311-462a-8ce5-c9db85d2159e,"{""context"": ""{'title': ['Baidu Baike', 'Social...","{""answer"": ""Wikimedia Foundation""}","{""response"": ""Pan Haidong"", ""retrieved_docs_li...","{""response"": ""Chinese Wikipedia"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,0,0.0,0.3333,0.0,0.5,0.0,0.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,fdf4d662-d51a-4c36-a798-e5f9bc5bcc38,"{""context"": ""{'title': ['Archdeaconry of St An...","{""answer"": ""87""}","{""response"": ""Eighty-eight churches."", ""retrie...","{""response"": ""Eighty-eight parish churches."", ...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,0,1.0,0.3333,0.0,0.5,0.0,0.4,0.0
996,fe72dc28-9b5f-41a7-ab23-bdb8e2ecaa97,"{""context"": ""{'title': ['Tralee Speedway', 'Di...","{""answer"": ""Dirt track racing""}","{""response"": ""Dirt track racing."", ""retrieved_...","{""response"": ""Dirt track racing"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,1,1.0,0.3333,0.5,0.5,0.5,0.4,0.5
997,feab479e-056d-4066-9cf8-b687d34398b0,"{""context"": ""{'title': [\""2015 Rogers Cup \u20...","{""answer"": ""Roberta Vinci""}","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,1,1.0,0.6667,0.5,1.0,0.5,0.8,0.5
998,ff316509-701e-4e84-ae05-17e9b2b3c080,"{""context"": ""{'title': ['Lana Del Rey (EP)', '...","{""answer"": ""Taylor Swift""}","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,1,1.0,0.3333,0.5,0.5,0.5,0.4,0.5
999,ffd0e20e-29db-4cb6-bbbe-c6d4f0f2ac85,"{""context"": ""{'title': ['Fat Cat Brewery', 'Th...","{""answer"": ""46 Albert Square, Walford, London ...","{""response"": ""46 Albert Square"", ""retrieved_do...","{""response"": ""The Queen Victoria"", ""retrieved_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,NaN,NaN,0,1.0,0.3333,0.0,0.5,0.0,0.4,0.0

In [36]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_outputs',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_outputs',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_run',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_run',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_status',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_status',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_error',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_error',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_latency',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_latency',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_tokens',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_tokens',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_total_cost',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_total_cost',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_recall',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_recall',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_final_answer_correct',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_final_answer_correct',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_f1',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_f1',
 'seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_precision',
 'self_rag_k_3_model_gpt-4o_v_304-1cb5682e_precision',
 'id.1',
 'inputs.1',
 'reference_outputs.1',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_outputs',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_outputs',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_run',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_run',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_status',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_status',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_error',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_error',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_latency',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_latency',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_tokens',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_tokens',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_total_cost',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_total_cost',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_wrapper',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_wrapper',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_final_answer_correct',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_final_answer_correct',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_precision',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_precision',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_recall',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_recall',
 'basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_f1',
 'crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_f1']

In [37]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_final_answer_correct
   ✅ precision            → seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_precision
   ✅ recall               → seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_recall
   ✅ f1                   → seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_k_3_model_gpt-4o_v_304-1cb5682e_final_answer_correct
   ✅ precision            → self_rag_k_3_model_gpt-4o_v_304-1cb5682e_precision
   ✅ recall               → self_rag_k_3_model_gpt-4o_v_304-1cb5682e_recall
   ✅ f1                   → self_rag_k_3_model_gpt-4o_v_304-1cb5682e_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_final_answer_correct
   ✅ precision            → crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_precision
   ✅ recall               → crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_recall
   ✅ f1                   → crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_final_answer_correct
   ✅ precision            → basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_precision
   ✅ recall               → basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_recall
   ✅ f1                   → basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      < 0.001***  < 0.001***  < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  < 0.001***  < 0.001***
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_final_answer_correct
   SELF_RAG: self_rag_k_3_model_gpt-4o_v_304-1cb5682e_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.7% accuracy
   SELF_RAG: 71.0% accuracy
   Difference: -5.7%
   P-value: 0.000016
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    177       56      233
         Right    113      654      767
--------------------------------------------------
         Total    290      710     1000

🔍 INTERPRETATION:
   Both wrong: 177 questions
   SELF_RAG wins:  56 questions (when SEAL RAG fails)
   SEAL RAG wins: 113 questions (when SELF_RAG fails)
   Both right: 654 questions
   Disagreements: 169 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.0x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_precision
   SELF_RAG: self_rag_k_3_model_gpt-4o_v_304-1cb5682e_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8925 ± 0.2798
   SELF_RAG: 0.7585 ± 0.3796
   Mean difference: +0.1340
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 11.6701
   P-value: 0.000000
   Effect size (Cohen's d): 0.3690
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_recall
   SELF_RAG: self_rag_k_3_model_gpt-4o_v_304-1cb5682e_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6810 ± 0.3071
   SELF_RAG: 0.5470 ± 0.3208
   Mean difference: +0.1340
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 11.6115
   P-value: 0.000000
   Effect size (Cohen's d): 0.3672
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_f1
   SELF_RAG: self_rag_k_3_model_gpt-4o_v_304-1cb5682e_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7507 ± 0.2733
   SELF_RAG: 0.6102 ± 0.3099
   Mean difference: +0.1405
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 13.6586
   P-value: 0.000000
   Effect size (Cohen's d): 0.4319
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_final_answer_correct
   CRAG_RAG: crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.7% accuracy
   CRAG_RAG: 69.0% accuracy
   Difference: -7.7%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    163       70      233
         Right    147      620      767
--------------------------------------------------
         Total    310      690     1000

🔍 INTERPRETATION:
   Both wrong: 163 questions
   CRAG_RAG wins:  70 questions (when SEAL RAG fails)
   SEAL RAG wins: 147 questions (when CRAG_RAG fails)
   Both right: 620 questions
   Disagreements: 217 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.1x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_precision
   CRAG_RAG: crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8925 ± 0.2798
   CRAG_RAG: 0.3677 ± 0.2631
   Mean difference: +0.5248
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 50.8516
   P-value: 0.000000
   Effect size (Cohen's d): 1.6081
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_recall
   CRAG_RAG: crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6810 ± 0.3071
   CRAG_RAG: 0.4415 ± 0.3499
   Mean difference: +0.2395
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 18.2055
   P-value: 0.000000
   Effect size (Cohen's d): 0.5757
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_f1
   CRAG_RAG: crag_rag_k_3_model_gpt-4o_max_loop_5_v2-03a122c5_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7507 ± 0.2733
   CRAG_RAG: 0.3972 ± 0.2939
   Mean difference: +0.3535
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 31.7428
   P-value: 0.000000
   Effect size (Cohen's d): 1.0038
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_final_answer_correct
   BASIC_RAG: basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.7% accuracy
   BASIC_RAG: 68.0% accuracy
   Difference: -8.7%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    177       56      233
         Right    143      624      767
--------------------------------------------------
         Total    320      680     1000

🔍 INTERPRETATION:
   Both wrong: 177 questions
   BASIC_RAG wins:  56 questions (when SEAL RAG fails)
   SEAL RAG wins: 143 questions (when BASIC_RAG fails)
   Both right: 624 questions
   Disagreements: 199 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.6x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_precision
   BASIC_RAG: basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.8925 ± 0.2798
   BASIC_RAG: 0.4942 ± 0.2042
   Mean difference: +0.3983
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 46.2460
   P-value: 0.000000
   Effect size (Cohen's d): 1.4624
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_recall
   BASIC_RAG: basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.6810 ± 0.3071
   BASIC_RAG: 0.7245 ± 0.2914
   Mean difference: -0.0435
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: -4.5241
   P-value: 0.000007
   Effect size (Cohen's d): -0.1431
   Result: 🟢 SIGNIFICANT - BASIC_RAG is significantly better
   Effect size interpretation: negligible

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4o_max_loop_5_v200_old_1-24a0719b_f1
   BASIC_RAG: basic_rag_k_3_model_gpt-4o_max_loop_5_v2-34ab6a2c_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7507 ± 0.2733
   BASIC_RAG: 0.5863 ± 0.2370
   Mean difference: +0.1644
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 20.1915
   P-value: 0.000000
   Effect size (Cohen's d): 0.6385
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name       P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared  1.649667e-05            True          p < 0.001            76.7%                  71.0%                  -5.7%              113               56 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic  1.365649e-29            True          p < 0.001            0.893                  0.759                 +0.134 N/A (Continuous) N/A (Continuous)        0.369      t = 11.670
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic  2.499994e-29            True          p < 0.001            0.681                  0.547                 +0.134 N/A (Continuous) N/A (Continuous)        0.367      t = 11.612
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic  4.571183e-39            True          p < 0.001            0.751                  0.610                 +0.141 N/A (Continuous) N/A (Continuous)        0.432      t = 13.659
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared  2.479859e-07            True          p < 0.001            76.7%                  69.0%                  -7.7%              147               70 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 1.974965e-279            True          p < 0.001            0.893                  0.368                 +0.525 N/A (Continuous) N/A (Continuous)        1.608      t = 50.852
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic  3.544572e-64            True          p < 0.001            0.681                  0.442                 +0.239 N/A (Continuous) N/A (Continuous)        0.576      t = 18.206
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 1.795600e-153            True          p < 0.001            0.751                  0.397                 +0.354 N/A (Continuous) N/A (Continuous)        1.004      t = 31.743
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared  1.084984e-09            True          p < 0.001            76.7%                  68.0%                  -8.7%              143               56 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 1.625860e-250            True          p < 0.001            0.893                  0.494                 +0.398 N/A (Continuous) N/A (Continuous)        1.462      t = 46.246
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic  6.792501e-06            True          p < 0.001            0.681                  0.725                 -0.043 N/A (Continuous) N/A (Continuous)       -0.143      t = -4.524
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic  2.670728e-76            True          p < 0.001            0.751                  0.586                 +0.164 N/A (Continuous) N/A (Continuous)        0.639      t = 20.192
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    1.649667e-05            True          p < 0.001            76.7%
1    1.365649e-29            True          p < 0.001            0.893
2    2.499994e-29            True          p < 0.001            0.681
3    4.571183e-39            True          p < 0.001            0.751
4    2.479859e-07            True          p < 0.001            76.7%
5   1.974965e-279            True          p < 0.001            0.893
6    3.544572e-64            True          p < 0.001            0.681
7   1.795600e-153            True          p < 0.001            0.751
8    1.084984e-09            True          p < 0.001            76.7%
9   1.625860e-250            True          p < 0.001            0.893
10   6.792501e-06            True          p < 0.001            0.681
11   2.670728e-76            True          p < 0.001            0.751

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   71.0%                  -5.7%               113
1                   0.759                 +0.134  N/A (Continuous)
2                   0.547                 +0.134  N/A (Continuous)
3                   0.610                 +0.141  N/A (Continuous)
4                   69.0%                  -7.7%               147
5                   0.368                 +0.525  N/A (Continuous)
6                   0.442                 +0.239  N/A (Continuous)
7                   0.397                 +0.354  N/A (Continuous)
8                   68.0%                  -8.7%               143
9                   0.494                 +0.398  N/A (Continuous)
10                  0.725                 -0.043  N/A (Continuous)
11                  0.586                 +0.164  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 56  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.369      t = 11.670
2   N/A (Continuous)         0.367      t = 11.612
3   N/A (Continuous)         0.432      t = 13.659
4                 70  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         1.608      t = 50.852
6   N/A (Continuous)         0.576      t = 18.206
7   N/A (Continuous)         1.004      t = 31.743
8                 56  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         1.462      t = 46.246
10  N/A (Continuous)        -0.143      t = -4.524
11  N/A (Continuous)         0.639      t = 20.192

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared

## k = 3 | gpt 4.1

In [ ]:
df = pd.read_csv("files/experiment_comarison/k_3/seal_k_3_model_4_1.csv")
#df = df.iloc[:, 30:]
df

,id,inputs,reference_outputs,basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_outputs,self_rag_k_3_model_gpt-4.1_v_309-7011eafe_outputs,basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_run,self_rag_k_3_model_gpt-4.1_v_309-7011eafe_run,basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_status,self_rag_k_3_model_gpt-4.1_v_309-7011eafe_status,basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_error,...,crag_rag_k_3_model_gpt-4.1_v_308-899087b5_precision,seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_precision,crag_rag_k_3_model_gpt-4.1_v_308-899087b5_f1,seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_f1,crag_rag_k_3_model_gpt-4.1_v_308-899087b5_wrapper,seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_wrapper,crag_rag_k_3_model_gpt-4.1_v_308-899087b5_recall,seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_recall,crag_rag_k_3_model_gpt-4.1_v_308-899087b5_final_answer_correct,seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_final_answer_correct
0,0004211d-fdd0-46a4-ba01-3a5d916924e9,"{""context"": ""{'title': ['Clayton Oliver', 'Ste...","{""answer"": ""1.95 m""}","{""response"": ""I don't know."", ""retrieved_docs_...","{""response"": ""I don't know."", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.0000,1.0,0.0,1.0000,NaN,NaN,0.0,1.0,0,1.0
1,009df37c-3a8f-4a00-b8ed-342f7754257e,"{""context"": ""{'title': [\""2012\u201313 VCU Ram...","{""answer"": ""1838""}","{""response"": ""The context does not provide the...","{""response"": ""1968"", ""retrieved_docs_list"": [""...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.0000,1.0,0.0,0.6667,NaN,NaN,0.0,0.5,1,0.0
2,00e0d7de-631c-47fc-b651-3e69c2029606,"{""context"": ""{'title': ['All I Wanna Do Is Mak...","{""answer"": ""2000""}","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""response"": ""March 14, 2000"", ""retrieved_docs...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.0000,0.5,0.0,0.5000,NaN,NaN,0.0,0.5,1,1.0
3,0169d92a-754a-407c-afd8-5372b4b493a5,"{""context"": ""{'title': ['Alle tiders kupp', 'V...","{""answer"": ""Fomento Econ\u00f3mico Mexicano""}","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""response"": ""Coca-Cola FEMSA"", ""retrieved_doc...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.6667,0.5,0.8,0.5000,NaN,NaN,1.0,0.5,0,0.0
4,016dfba5-d311-462a-8ce5-c9db85d2159e,"{""context"": ""{'title': ['Baidu Baike', 'Social...","{""answer"": ""Wikimedia Foundation""}","{""response"": ""Pan Haidong"", ""retrieved_docs_li...","{""response"": ""Pan Haidong"", ""retrieved_docs_li...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.3333,1.0,0.4,0.6667,NaN,NaN,0.5,0.5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,fdf4d662-d51a-4c36-a798-e5f9bc5bcc38,"{""context"": ""{'title': ['Archdeaconry of St An...","{""answer"": ""87""}","{""response"": ""Eighty-eight parish churches."", ...","{""response"": ""Eighty-eight parish churches"", ""...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.0000,0.5,0.0,0.5000,NaN,NaN,0.0,0.5,0,0.0
996,fe72dc28-9b5f-41a7-ab23-bdb8e2ecaa97,"{""context"": ""{'title': ['Tralee Speedway', 'Di...","{""answer"": ""Dirt track racing""}","{""response"": ""Dirt track racing"", ""retrieved_d...","{""response"": ""Dirt track racing"", ""retrieved_d...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.3333,0.5,0.4,0.5000,NaN,NaN,0.5,0.5,1,1.0
997,feab479e-056d-4066-9cf8-b687d34398b0,"{""context"": ""{'title': [\""2015 Rogers Cup \u20...","{""answer"": ""Roberta Vinci""}","{""response"": ""Roberta Vinci."", ""retrieved_docs...","{""response"": ""Roberta Vinci"", ""retrieved_docs_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.6667,1.0,0.8,1.0000,NaN,NaN,1.0,1.0,1,1.0
998,ff316509-701e-4e84-ae05-17e9b2b3c080,"{""context"": ""{'title': ['Lana Del Rey (EP)', '...","{""answer"": ""Taylor Swift""}","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""response"": ""Taylor Swift"", ""retrieved_docs_l...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.5000,1.0,0.5,0.6667,NaN,NaN,0.5,0.5,1,1.0
999,ffd0e20e-29db-4cb6-bbbe-c6d4f0f2ac85,"{""context"": ""{'title': ['Fat Cat Brewery', 'Th...","{""answer"": ""46 Albert Square, Walford, London ...","{""response"": ""The Queen Victoria public house....","{""response"": ""The Queen Victoria"", ""retrieved_...","{""inputs"": {""inputs"": {""context"": ""{'title': [...","{""inputs"": {""inputs"": {""context"": ""{'title': [...",success,success,NaN,...,0.0000,1.0,0.0,1.0000,NaN,NaN,0.0,1.0,0,1.0

In [42]:
df.columns.to_list()

['id',
 'inputs',
 'reference_outputs',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_outputs',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_outputs',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_run',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_run',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_status',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_status',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_error',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_error',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_latency',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_latency',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_tokens',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_tokens',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_total_cost',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_total_cost',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_recall',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_recall',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_precision',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_precision',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_final_answer_correct',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_final_answer_correct',
 'basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_f1',
 'self_rag_k_3_model_gpt-4.1_v_309-7011eafe_f1',
 'id.1',
 'inputs.1',
 'reference_outputs.1',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_outputs',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_outputs',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_run',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_run',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_status',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_status',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_error',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_error',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_latency',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_latency',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_tokens',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_tokens',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_total_cost',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_total_cost',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_precision',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_precision',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_f1',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_f1',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_wrapper',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_wrapper',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_recall',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_recall',
 'crag_rag_k_3_model_gpt-4.1_v_308-899087b5_final_answer_correct',
 'seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_final_answer_correct']

In [43]:
# Run complete analysis
results = analyze_rag_experiments_complete(df)

# Access the summary table
summary_table = results['summary_table']
print(summary_table)

# Access detailed results
detailed_results = results['detailed_results']

# Save summary to CSV
#summary_table.to_csv('rag_comparison_summary.csv', index=False)

# Filter for significant results only
significant_only = summary_table[summary_table['Is_Significant'] == True]
print("\nSignificant results only:")
print(significant_only)

# Get specific comparison
seal_vs_crag_accuracy = summary_table[
    (summary_table['Comparison_Method'] == 'CRAG_RAG') & 
    (summary_table['Metric'] == 'Accuracy')
]

🚀 COMPREHENSIVE RAG METHOD COMPARISON
================================================================================
📊 BASE METHOD: SEAL RAG
================================================================================
🔍 COLUMN DETECTION RESULTS
====================================================================================================

📊 SEAL RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_final_answer_correct
   ✅ precision            → seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_precision
   ✅ recall               → seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_recall
   ✅ f1                   → seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_f1

📊 SELF_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → self_rag_k_3_model_gpt-4.1_v_309-7011eafe_final_answer_correct
   ✅ precision            → self_rag_k_3_model_gpt-4.1_v_309-7011eafe_precision
   ✅ recall               → self_rag_k_3_model_gpt-4.1_v_309-7011eafe_recall
   ✅ f1                   → self_rag_k_3_model_gpt-4.1_v_309-7011eafe_f1

📊 CRAG_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → crag_rag_k_3_model_gpt-4.1_v_308-899087b5_final_answer_correct
   ✅ precision            → crag_rag_k_3_model_gpt-4.1_v_308-899087b5_precision
   ✅ recall               → crag_rag_k_3_model_gpt-4.1_v_308-899087b5_recall
   ✅ f1                   → crag_rag_k_3_model_gpt-4.1_v_308-899087b5_f1

📊 BASIC_RAG:
--------------------------------------------------------------------------------
   ✅ final_answer_correct → basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_final_answer_correct
   ✅ precision            → basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_precision
   ✅ recall               → basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_recall
   ✅ f1                   → basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_f1

====================================================================================================

📋 SUMMARY TABLE - P-VALUES
--------------------------------------------------------------------------------
Metric               Test Type       vs SELF_RAG  vs CRAG_RAG  vs BASIC_RAG
--------------------------------------------------------------------------------
Accuracy             McNemar's      0.031*      0.002**     < 0.001***
Precision            T-Test         < 0.001***  < 0.001***  < 0.001***
Recall               T-Test         < 0.001***  < 0.001***  0.347
F1 Score             T-Test         < 0.001***  < 0.001***  < 0.001***
--------------------------------------------------------------------------------
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)


🎯 DETAILED ANALYSIS: SEAL RAG vs SELF_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_final_answer_correct
   SELF_RAG: self_rag_k_3_model_gpt-4.1_v_309-7011eafe_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.2% accuracy
   SELF_RAG: 73.1% accuracy
   Difference: -3.1%
   P-value: 0.030815
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs SELF_RAG
============================================================
                    SELF_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    157       81      238
         Right    112      650      762
--------------------------------------------------
         Total    269      731     1000

🔍 INTERPRETATION:
   Both wrong: 157 questions
   SELF_RAG wins:  81 questions (when SEAL RAG fails)
   SEAL RAG wins: 112 questions (when SELF_RAG fails)
   Both right: 650 questions
   Disagreements: 193 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 1.4x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_precision
   SELF_RAG: self_rag_k_3_model_gpt-4.1_v_309-7011eafe_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9068 ± 0.2524
   SELF_RAG: 0.7873 ± 0.3336
   Mean difference: +0.1195
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 11.5723
   P-value: 0.000000
   Effect size (Cohen's d): 0.3659
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_recall
   SELF_RAG: self_rag_k_3_model_gpt-4.1_v_309-7011eafe_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7325 ± 0.2971
   SELF_RAG: 0.6145 ± 0.3062
   Mean difference: +0.1180
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 11.4513
   P-value: 0.000000
   Effect size (Cohen's d): 0.3621
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_f1
   SELF_RAG: self_rag_k_3_model_gpt-4.1_v_309-7011eafe_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7893 ± 0.2581
   SELF_RAG: 0.6610 ± 0.2787
   Mean difference: +0.1283
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 14.3819
   P-value: 0.000000
   Effect size (Cohen's d): 0.4548
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: small


🎯 DETAILED ANALYSIS: SEAL RAG vs CRAG_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_final_answer_correct
   CRAG_RAG: crag_rag_k_3_model_gpt-4.1_v_308-899087b5_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.2% accuracy
   CRAG_RAG: 71.6% accuracy
   Difference: -4.6%
   P-value: 0.002414
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs CRAG_RAG
============================================================
                    CRAG_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    151       87      238
         Right    133      629      762
--------------------------------------------------
         Total    284      716     1000

🔍 INTERPRETATION:
   Both wrong: 151 questions
   CRAG_RAG wins:  87 questions (when SEAL RAG fails)
   SEAL RAG wins: 133 questions (when CRAG_RAG fails)
   Both right: 629 questions
   Disagreements: 220 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 1.5x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_precision
   CRAG_RAG: crag_rag_k_3_model_gpt-4.1_v_308-899087b5_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9068 ± 0.2524
   CRAG_RAG: 0.4050 ± 0.2551
   Mean difference: +0.5018
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 52.3171
   P-value: 0.000000
   Effect size (Cohen's d): 1.6544
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_recall
   CRAG_RAG: crag_rag_k_3_model_gpt-4.1_v_308-899087b5_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7325 ± 0.2971
   CRAG_RAG: 0.4980 ± 0.3509
   Mean difference: +0.2345
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 18.6903
   P-value: 0.000000
   Effect size (Cohen's d): 0.5910
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: medium

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_f1
   CRAG_RAG: crag_rag_k_3_model_gpt-4.1_v_308-899087b5_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7893 ± 0.2581
   CRAG_RAG: 0.4422 ± 0.2891
   Mean difference: +0.3471
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 33.3393
   P-value: 0.000000
   Effect size (Cohen's d): 1.0543
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


🎯 DETAILED ANALYSIS: SEAL RAG vs BASIC_RAG
================================================================================

📊 METRIC: ACCURACY
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_final_answer_correct
   BASIC_RAG: basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_final_answer_correct

🔍 TEST TYPE: McNemar's Test (Binary Data)
   SEAL RAG: 76.2% accuracy
   BASIC_RAG: 67.9% accuracy
   Difference: -8.3%
   P-value: 0.000000
   Significant: 🟢 YES

📋 CONTINGENCY MATRIX: SEAL RAG vs BASIC_RAG
============================================================
                    BASIC_RAG
                 Wrong    Right    Total
--------------------------------------------------
SEAL RAG Wrong    163       75      238
         Right    158      604      762
--------------------------------------------------
         Total    321      679     1000

🔍 INTERPRETATION:
   Both wrong: 163 questions
   BASIC_RAG wins:  75 questions (when SEAL RAG fails)
   SEAL RAG wins: 158 questions (when BASIC_RAG fails)
   Both right: 604 questions
   Disagreements: 233 questions (key for statistical test)
   Head-to-head: SEAL RAG wins 2.1x more often

📊 METRIC: PRECISION
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_precision
   BASIC_RAG: basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_precision

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.9068 ± 0.2524
   BASIC_RAG: 0.4935 ± 0.2048
   Mean difference: +0.4133
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 51.2434
   P-value: 0.000000
   Effect size (Cohen's d): 1.6205
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large

📊 METRIC: RECALL
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_recall
   BASIC_RAG: basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_recall

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7325 ± 0.2971
   BASIC_RAG: 0.7235 ± 0.2922
   Mean difference: +0.0090
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 0.9408
   P-value: 0.347024
   Effect size (Cohen's d): 0.0298
   Result: 🔴 NOT SIGNIFICANT - No significant difference
   Effect size interpretation: negligible

📊 METRIC: F1 SCORE
------------------------------------------------------------
📁 COLUMNS USED:
   SEAL RAG: seal_rag_k_3_model_gpt-4.1_v_305-8cb8c3df_f1
   BASIC_RAG: basic_rag_k_3_model_gpt-4.1_v_307-85bf25a2_f1

🔍 TEST TYPE: Paired T-Test (Continuous Data)

📈 CONTINUOUS METRIC RESULTS:
   SEAL RAG: 0.7893 ± 0.2581
   BASIC_RAG: 0.5855 ± 0.2376
   Mean difference: +0.2038
   Sample size: 1000 questions

📊 PAIRED T-TEST RESULTS:
   T-statistic: 25.6119
   P-value: 0.000000
   Effect size (Cohen's d): 0.8099
   Result: 🟢 SIGNIFICANT - SEAL RAG is significantly better
   Effect size interpretation: large


📊 SUMMARY TABLE (DataFrame)
========================================================================================================================
Base_Method Comparison_Method    Metric     Test_Type Statistic_Name       P_Value  Is_Significant Significance_Level Base_Performance Comparison_Performance Performance_Difference        Base_Wins  Comparison_Wins  Effect_Size Statistic_Value
   SEAL RAG          SELF_RAG  Accuracy       McNemar    Chi-squared  3.081549e-02            True           p < 0.05            76.2%                  73.1%                  -3.1%              112               81 N/A (Binary)        χ² = N/A
   SEAL RAG          SELF_RAG Precision Paired T-test    T-statistic  3.743207e-29            True          p < 0.001            0.907                  0.787                 +0.119 N/A (Continuous) N/A (Continuous)        0.366      t = 11.572
   SEAL RAG          SELF_RAG    Recall Paired T-test    T-statistic  1.291930e-28            True          p < 0.001            0.733                  0.615                 +0.118 N/A (Continuous) N/A (Continuous)        0.362      t = 11.451
   SEAL RAG          SELF_RAG  F1 Score Paired T-test    T-statistic  9.158187e-43            True          p < 0.001            0.789                  0.661                 +0.128 N/A (Continuous) N/A (Continuous)        0.455      t = 14.382
   SEAL RAG          CRAG_RAG  Accuracy       McNemar    Chi-squared  2.414149e-03            True           p < 0.01            76.2%                  71.6%                  -4.6%              133               87 N/A (Binary)        χ² = N/A
   SEAL RAG          CRAG_RAG Precision Paired T-test    T-statistic 2.141726e-288            True          p < 0.001            0.907                  0.405                 +0.502 N/A (Continuous) N/A (Continuous)        1.654      t = 52.317
   SEAL RAG          CRAG_RAG    Recall Paired T-test    T-statistic  4.407108e-67            True          p < 0.001            0.733                  0.498                 +0.234 N/A (Continuous) N/A (Continuous)        0.591      t = 18.690
   SEAL RAG          CRAG_RAG  F1 Score Paired T-test    T-statistic 1.959739e-164            True          p < 0.001            0.789                  0.442                 +0.347 N/A (Continuous) N/A (Continuous)        1.054      t = 33.339
   SEAL RAG         BASIC_RAG  Accuracy       McNemar    Chi-squared  7.786871e-08            True          p < 0.001            76.2%                  67.9%                  -8.3%              158               75 N/A (Binary)        χ² = N/A
   SEAL RAG         BASIC_RAG Precision Paired T-test    T-statistic 7.712237e-282            True          p < 0.001            0.907                  0.494                 +0.413 N/A (Continuous) N/A (Continuous)        1.620      t = 51.243
   SEAL RAG         BASIC_RAG    Recall Paired T-test    T-statistic  3.470240e-01           False    Not Significant            0.733                  0.724                 +0.009 N/A (Continuous) N/A (Continuous)        0.030       t = 0.941
   SEAL RAG         BASIC_RAG  F1 Score Paired T-test    T-statistic 1.258067e-111            True          p < 0.001            0.789                  0.586                 +0.204 N/A (Continuous) N/A (Continuous)        0.810      t = 25.612
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
10    SEAL RAG         BASIC_RAG     Recall  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    3.081549e-02            True           p < 0.05            76.2%
1    3.743207e-29            True          p < 0.001            0.907
2    1.291930e-28            True          p < 0.001            0.733
3    9.158187e-43            True          p < 0.001            0.789
4    2.414149e-03            True           p < 0.01            76.2%
5   2.141726e-288            True          p < 0.001            0.907
6    4.407108e-67            True          p < 0.001            0.733
7   1.959739e-164            True          p < 0.001            0.789
8    7.786871e-08            True          p < 0.001            76.2%
9   7.712237e-282            True          p < 0.001            0.907
10   3.470240e-01           False    Not Significant            0.733
11  1.258067e-111            True          p < 0.001            0.789

   Comparison_Performance Performance_Difference         Base_Wins  \
0                   73.1%                  -3.1%               112
1                   0.787                 +0.119  N/A (Continuous)
2                   0.615                 +0.118  N/A (Continuous)
3                   0.661                 +0.128  N/A (Continuous)
4                   71.6%                  -4.6%               133
5                   0.405                 +0.502  N/A (Continuous)
6                   0.498                 +0.234  N/A (Continuous)
7                   0.442                 +0.347  N/A (Continuous)
8                   67.9%                  -8.3%               158
9                   0.494                 +0.413  N/A (Continuous)
10                  0.724                 +0.009  N/A (Continuous)
11                  0.586                 +0.204  N/A (Continuous)

     Comparison_Wins   Effect_Size Statistic_Value
0                 81  N/A (Binary)        χ² = N/A
1   N/A (Continuous)         0.366      t = 11.572
2   N/A (Continuous)         0.362      t = 11.451
3   N/A (Continuous)         0.455      t = 14.382
4                 87  N/A (Binary)        χ² = N/A
5   N/A (Continuous)         1.654      t = 52.317
6   N/A (Continuous)         0.591      t = 18.690
7   N/A (Continuous)         1.054      t = 33.339
8                 75  N/A (Binary)        χ² = N/A
9   N/A (Continuous)         1.620      t = 51.243
10  N/A (Continuous)         0.030       t = 0.941
11  N/A (Continuous)         0.810      t = 25.612

Significant results only:
   Base_Method Comparison_Method     Metric      Test_Type Statistic_Name  \
0     SEAL RAG          SELF_RAG   Accuracy        McNemar    Chi-squared
1     SEAL RAG          SELF_RAG  Precision  Paired T-test    T-statistic
2     SEAL RAG          SELF_RAG     Recall  Paired T-test    T-statistic
3     SEAL RAG          SELF_RAG   F1 Score  Paired T-test    T-statistic
4     SEAL RAG          CRAG_RAG   Accuracy        McNemar    Chi-squared
5     SEAL RAG          CRAG_RAG  Precision  Paired T-test    T-statistic
6     SEAL RAG          CRAG_RAG     Recall  Paired T-test    T-statistic
7     SEAL RAG          CRAG_RAG   F1 Score  Paired T-test    T-statistic
8     SEAL RAG         BASIC_RAG   Accuracy        McNemar    Chi-squared
9     SEAL RAG         BASIC_RAG  Precision  Paired T-test    T-statistic
11    SEAL RAG         BASIC_RAG   F1 Score  Paired T-test    T-statistic

          P_Value  Is_Significant Significance_Level Base_Performance  \
0    3.081549e-02            True           p < 0.05            76.2%
1    3.743207e-29            True          p < 0.001            0.907